#!/usr/bin/env python3
"""
Build GCP Graph Ontology + Resource Taxonomy from step5 resource catalog.

OUTPUTS (written per BASE_DIR):
  gcp_graph_ontology.json      — stable categories, generic node types, edge types, id_kinds
  gcp_resource_taxonomy.json   — per-(service, resource_type) classification + dataset mapping

CLI:
  python build_graph_ontology.py                  # uses BASE_DIR
  python build_graph_ontology.py --base /path/to/gcp
"""

import json
import re
import argparse
from datetime import datetime, timezone
from pathlib import Path

BASE_DIR = Path('/Users/apple/Desktop/data_pythonsdk/gcp')

# ─────────────────────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


# ─────────────────────────────────────────────────────────────────────────────
# ONTOLOGY DEFINITION  (static, GCP-first)
# ─────────────────────────────────────────────────────────────────────────────

CATEGORIES = [
    {"category": "compute",
     "description": "Virtual machines, disks, images, machine types and related compute primitives.",
     "gcp_examples": ["compute.instances", "compute.disks", "compute.machineTypes",
                       "compute.instanceTemplates", "compute.snapshots"]},
    {"category": "network",
     "description": "Virtual networks, subnets, routes, load balancers, DNS, VPN, and interconnect.",
     "gcp_examples": ["compute.networks", "compute.subnetworks", "compute.routes",
                       "compute.forwardingRules", "dns.managedZones",
                       "networkconnectivity.hubs", "compute.vpnGateways"]},
    {"category": "identity",
     "description": "Service accounts, users, groups, workforce pools, workload identity and OAuth clients.",
     "gcp_examples": ["iam.serviceAccounts", "iam.workloadIdentityPools",
                       "iam.workforcePools", "iam.oauthClients",
                       "cloudidentity.groups", "admin.users"]},
    {"category": "access",
     "description": "IAM roles, policies, bindings, permissions, IAP, and access context.",
     "gcp_examples": ["iam.roles", "accesscontextmanager.accessPolicies",
                       "iap.tunnelInstances", "iam.providers"]},
    {"category": "security",
     "description": "Firewalls, security policies, IDS, binary authorization, Security Command Center findings.",
     "gcp_examples": ["compute.firewalls", "compute.firewallPolicies",
                       "compute.securityPolicies", "ids.endpoints",
                       "binaryauthorization.policies", "securitycenter.findings"]},
    {"category": "storage",
     "description": "Object storage buckets, file shares, persistent disks, and backup vaults.",
     "gcp_examples": ["storage.buckets", "file.instances", "backupdr.backupVaults",
                       "netapp.volumes", "storagetransfer.transferJobs"]},
    {"category": "data",
     "description": "Managed databases, data warehouses, analytics datasets, and streaming pipelines.",
     "gcp_examples": ["sqladmin.instances", "bigquery.datasets", "spanner.instances",
                       "bigtableadmin.instances", "datastream.streams",
                       "bigquerydatatransfer.transferConfigs"]},
    {"category": "crypto",
     "description": "KMS key rings, crypto keys, key versions, EKM connections, and secret manager secrets.",
     "gcp_examples": ["cloudkms.keyRings", "cloudkms.cryptoKeys",
                       "cloudkms.cryptoKeyVersions", "secretmanager.secrets",
                       "cloudkms.ekmConnections"]},
    {"category": "cert",
     "description": "TLS/SSL certificates, certificate authorities, certificate maps.",
     "gcp_examples": ["certificatemanager.certificates", "privateca.caPools",
                       "privateca.certificateAuthorities", "compute.sslCertificates"]},
    {"category": "kubernetes",
     "description": "GKE clusters, node pools, backup plans, hub memberships, and on-prem clusters.",
     "gcp_examples": ["container.clusters", "container.nodePools",
                       "gkebackup.backupPlans", "gkehub.memberships",
                       "gkeonprem.vmwareClusters"]},
    {"category": "app",
     "description": "Serverless apps, Cloud Run services/jobs, App Engine apps, Cloud Functions.",
     "gcp_examples": ["run.services", "run.jobs", "appengine.services",
                       "cloudfunctions.functions", "appengine.versions"]},
    {"category": "observability",
     "description": "Logging sinks, metrics, alerting policies, dashboards, trace, profiler.",
     "gcp_examples": ["logging.sinks", "monitoring.alertPolicies",
                       "monitoring.dashboards", "cloudtrace.traces",
                       "cloudprofiler.profiles"]},
    {"category": "messaging",
     "description": "Pub/Sub topics and subscriptions, Kafka clusters, event arc triggers.",
     "gcp_examples": ["pubsub.topics", "pubsub.subscriptions",
                       "managedkafka.clusters", "eventarc.triggers",
                       "pubsublite.topics"]},
    {"category": "devops",
     "description": "CI/CD pipelines, source repos, artifact registries, build triggers, deploy targets.",
     "gcp_examples": ["cloudbuild.builds", "artifactregistry.repositories",
                       "clouddeploy.deliveryPipelines", "cloudbuild.triggers",
                       "developerconnect.connections"]},
    {"category": "governance",
     "description": "Organization policies, resource hierarchy, billing, asset inventory, recommendations.",
     "gcp_examples": ["orgpolicy.policies", "cloudresourcemanager.projects",
                       "cloudresourcemanager.folders", "cloudbilling.billingAccounts",
                       "recommender.recommendations", "cloudasset.assets"]},
    {"category": "other",
     "description": "Resources that do not map clearly to any other category.",
     "gcp_examples": []},
]

GENERIC_NODE_TYPES = [
    # ── compute ──
    {"type": "compute.instance",
     "category": "compute",
     "description": "A virtual machine instance.",
     "gcp_example_resource_types": ["compute.instances", "compute.instanceGroupManagers"],
     "primary_identifier_kinds": ["gcp_full_name", "tuple"]},
    {"type": "compute.disk",
     "category": "compute",
     "description": "A persistent block-storage disk.",
     "gcp_example_resource_types": ["compute.disks", "compute.snapshots"],
     "primary_identifier_kinds": ["gcp_full_name", "tuple"]},
    {"type": "compute.image",
     "category": "compute",
     "description": "A disk image or machine image.",
     "gcp_example_resource_types": ["compute.images", "compute.machineImages"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "compute.instanceTemplate",
     "category": "compute",
     "description": "A template for creating VM instances.",
     "gcp_example_resource_types": ["compute.instanceTemplates"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "compute.instanceGroup",
     "category": "compute",
     "description": "A managed or unmanaged group of VM instances.",
     "gcp_example_resource_types": ["compute.instanceGroups", "compute.instanceGroupManagers"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "compute.accelerator",
     "category": "compute",
     "description": "GPU / TPU accelerator type or reservation.",
     "gcp_example_resource_types": ["compute.acceleratorTypes", "tpu.nodes"],
     "primary_identifier_kinds": ["gcp_full_name", "tuple"]},
    {"type": "compute.reservation",
     "category": "compute",
     "description": "Capacity reservation for VMs.",
     "gcp_example_resource_types": ["compute.reservations"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    # ── network ──
    {"type": "network.vpc",
     "category": "network",
     "description": "A Virtual Private Cloud network.",
     "gcp_example_resource_types": ["compute.networks"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "network.subnet",
     "category": "network",
     "description": "A subnet within a VPC.",
     "gcp_example_resource_types": ["compute.subnetworks"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "network.firewall",
     "category": "network",
     "description": "A firewall rule or firewall policy.",
     "gcp_example_resource_types": ["compute.firewalls", "compute.firewallPolicies"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "network.route",
     "category": "network",
     "description": "A routing rule in a VPC.",
     "gcp_example_resource_types": ["compute.routes", "compute.routers"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "network.loadBalancer",
     "category": "network",
     "description": "A load balancer frontend or backend.",
     "gcp_example_resource_types": ["compute.forwardingRules", "compute.backendServices",
                                      "compute.targetHttpProxies", "compute.urlMaps"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "network.vpn",
     "category": "network",
     "description": "A VPN gateway or tunnel.",
     "gcp_example_resource_types": ["compute.vpnGateways", "compute.vpnTunnels"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "network.interconnect",
     "category": "network",
     "description": "Dedicated or partner interconnect attachments.",
     "gcp_example_resource_types": ["compute.interconnects", "compute.interconnectAttachments"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "network.dnsZone",
     "category": "network",
     "description": "A managed DNS zone.",
     "gcp_example_resource_types": ["dns.managedZones", "dns.policies"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "network.hub",
     "category": "network",
     "description": "A network connectivity hub or spoke.",
     "gcp_example_resource_types": ["networkconnectivity.hubs", "networkconnectivity.spokes"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "network.endpoint",
     "category": "network",
     "description": "A network endpoint group or private endpoint.",
     "gcp_example_resource_types": ["compute.networkEndpointGroups", "vpcaccess.connectors"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "network.address",
     "category": "network",
     "description": "A static or ephemeral IP address.",
     "gcp_example_resource_types": ["compute.addresses", "compute.globalAddresses"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    # ── identity ──
    {"type": "identity.serviceAccount",
     "category": "identity",
     "description": "A GCP service account used by workloads.",
     "gcp_example_resource_types": ["iam.serviceAccounts"],
     "primary_identifier_kinds": ["email", "gcp_full_name"]},
    {"type": "identity.serviceAccountKey",
     "category": "identity",
     "description": "A key belonging to a service account.",
     "gcp_example_resource_types": ["iam.keys"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "identity.user",
     "category": "identity",
     "description": "A human user identity (Google account).",
     "gcp_example_resource_types": ["admin.users", "cloudidentity.users"],
     "primary_identifier_kinds": ["email", "raw_id"]},
    {"type": "identity.group",
     "category": "identity",
     "description": "A Google group or Cloud Identity group.",
     "gcp_example_resource_types": ["cloudidentity.groups", "admin.groups"],
     "primary_identifier_kinds": ["email", "gcp_full_name"]},
    {"type": "identity.workloadIdentityPool",
     "category": "identity",
     "description": "A workload identity pool for external identities.",
     "gcp_example_resource_types": ["iam.workloadIdentityPools", "iam.providers"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "identity.workforcePool",
     "category": "identity",
     "description": "A workforce identity pool for human users.",
     "gcp_example_resource_types": ["iam.workforcePools"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "identity.oauthClient",
     "category": "identity",
     "description": "An OAuth 2.0 client application.",
     "gcp_example_resource_types": ["iam.oauthClients"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    # ── access ──
    {"type": "access.role",
     "category": "access",
     "description": "An IAM role (predefined or custom).",
     "gcp_example_resource_types": ["iam.roles"],
     "primary_identifier_kinds": ["gcp_full_name", "raw_id"]},
    {"type": "access.policy",
     "category": "access",
     "description": "An IAM or org policy binding.",
     "gcp_example_resource_types": ["accesscontextmanager.accessPolicies",
                                      "orgpolicy.policies"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "access.accessLevel",
     "category": "access",
     "description": "An access context manager access level.",
     "gcp_example_resource_types": ["accesscontextmanager.accessLevels"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "access.servicePerimeter",
     "category": "access",
     "description": "A VPC Service Control perimeter.",
     "gcp_example_resource_types": ["accesscontextmanager.servicePerimeters"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    # ── security ──
    {"type": "security.firewallPolicy",
     "category": "security",
     "description": "A hierarchical or network firewall policy.",
     "gcp_example_resource_types": ["compute.firewallPolicies",
                                      "networksecurity.firewallEndpoints"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "security.securityPolicy",
     "category": "security",
     "description": "A Cloud Armor or backend security policy.",
     "gcp_example_resource_types": ["compute.securityPolicies"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "security.finding",
     "category": "security",
     "description": "A Security Command Center finding or source.",
     "gcp_example_resource_types": ["securitycenter.findings", "securitycenter.sources"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "security.idsEndpoint",
     "category": "security",
     "description": "An intrusion detection system endpoint.",
     "gcp_example_resource_types": ["ids.endpoints"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "security.binaryAuthPolicy",
     "category": "security",
     "description": "A binary authorization policy or attestor.",
     "gcp_example_resource_types": ["binaryauthorization.policies",
                                      "binaryauthorization.attestors"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "security.dlpInspectTemplate",
     "category": "security",
     "description": "A Cloud DLP inspect or de-identify template.",
     "gcp_example_resource_types": ["dlp.inspectTemplates", "dlp.deidentifyTemplates"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    # ── storage ──
    {"type": "storage.bucket",
     "category": "storage",
     "description": "A Cloud Storage bucket.",
     "gcp_example_resource_types": ["storage.buckets"],
     "primary_identifier_kinds": ["gcp_full_name", "raw_id"]},
    {"type": "storage.fileShare",
     "category": "storage",
     "description": "A Filestore instance or NFS share.",
     "gcp_example_resource_types": ["file.instances", "file.shares"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "storage.backupVault",
     "category": "storage",
     "description": "A backup vault or backup plan.",
     "gcp_example_resource_types": ["backupdr.backupVaults", "backupdr.backupPlans",
                                      "gkebackup.backupPlans"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "storage.netappVolume",
     "category": "storage",
     "description": "A NetApp volume or storage pool.",
     "gcp_example_resource_types": ["netapp.volumes", "netapp.storagePools"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    # ── data ──
    {"type": "data.sqlInstance",
     "category": "data",
     "description": "A Cloud SQL managed database instance.",
     "gcp_example_resource_types": ["sqladmin.instances", "sqladmin.databases"],
     "primary_identifier_kinds": ["gcp_full_name", "raw_id"]},
    {"type": "data.spannerInstance",
     "category": "data",
     "description": "A Cloud Spanner instance or database.",
     "gcp_example_resource_types": ["spanner.instances", "spanner.databases"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "data.bigqueryDataset",
     "category": "data",
     "description": "A BigQuery dataset or table.",
     "gcp_example_resource_types": ["bigquery.datasets", "bigquery.tables"],
     "primary_identifier_kinds": ["gcp_full_name", "raw_id"]},
    {"type": "data.bigtableInstance",
     "category": "data",
     "description": "A Bigtable instance or cluster.",
     "gcp_example_resource_types": ["bigtableadmin.instances", "bigtableadmin.clusters"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "data.firestoreDatabase",
     "category": "data",
     "description": "A Firestore database or collection.",
     "gcp_example_resource_types": ["firestore.databases", "datastore.indexes"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "data.datastreamJob",
     "category": "data",
     "description": "A Datastream or Dataflow streaming pipeline.",
     "gcp_example_resource_types": ["datastream.streams", "dataflow.jobs"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "data.redisInstance",
     "category": "data",
     "description": "A Redis or Memcache managed cache instance.",
     "gcp_example_resource_types": ["redis.instances", "memcache.instances"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "data.dataprocCluster",
     "category": "data",
     "description": "A Dataproc managed Hadoop/Spark cluster.",
     "gcp_example_resource_types": ["dataproc.clusters", "dataproc.jobs"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    # ── crypto ──
    {"type": "crypto.keyRing",
     "category": "crypto",
     "description": "A KMS key ring grouping crypto keys.",
     "gcp_example_resource_types": ["cloudkms.keyRings"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "crypto.kmsKey",
     "category": "crypto",
     "description": "A KMS crypto key (symmetric or asymmetric).",
     "gcp_example_resource_types": ["cloudkms.cryptoKeys"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "crypto.kmsKeyVersion",
     "category": "crypto",
     "description": "A specific version of a KMS crypto key.",
     "gcp_example_resource_types": ["cloudkms.cryptoKeyVersions"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "crypto.secret",
     "category": "crypto",
     "description": "A Secret Manager secret or version.",
     "gcp_example_resource_types": ["secretmanager.secrets", "secretmanager.versions"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "crypto.ekmConnection",
     "category": "crypto",
     "description": "An External Key Manager connection.",
     "gcp_example_resource_types": ["cloudkms.ekmConnections"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    # ── cert ──
    {"type": "cert.certificate",
     "category": "cert",
     "description": "A TLS/SSL certificate (managed or self-managed).",
     "gcp_example_resource_types": ["certificatemanager.certificates",
                                      "compute.sslCertificates"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "cert.certificateAuthority",
     "category": "cert",
     "description": "A Certificate Authority Service CA or CA pool.",
     "gcp_example_resource_types": ["privateca.certificateAuthorities",
                                      "privateca.caPools"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "cert.certificateMap",
     "category": "cert",
     "description": "A certificate map binding certs to load balancers.",
     "gcp_example_resource_types": ["certificatemanager.certificateMaps"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "cert.sslPolicy",
     "category": "cert",
     "description": "An SSL/TLS policy applied to load balancers.",
     "gcp_example_resource_types": ["compute.sslPolicies"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    # ── kubernetes ──
    {"type": "k8s.cluster",
     "category": "kubernetes",
     "description": "A GKE or Anthos Kubernetes cluster.",
     "gcp_example_resource_types": ["container.clusters", "gkeonprem.vmwareClusters"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "k8s.nodePool",
     "category": "kubernetes",
     "description": "A node pool within a GKE cluster.",
     "gcp_example_resource_types": ["container.nodePools"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "k8s.backupPlan",
     "category": "kubernetes",
     "description": "A GKE backup plan or restore plan.",
     "gcp_example_resource_types": ["gkebackup.backupPlans", "gkebackup.restorePlans"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "k8s.hubMembership",
     "category": "kubernetes",
     "description": "A GKE Hub fleet membership.",
     "gcp_example_resource_types": ["gkehub.memberships", "gkehub.features"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    # ── app ──
    {"type": "app.cloudRunService",
     "category": "app",
     "description": "A Cloud Run service or job.",
     "gcp_example_resource_types": ["run.services", "run.jobs"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "app.cloudFunction",
     "category": "app",
     "description": "A Cloud Functions function (gen1 or gen2).",
     "gcp_example_resource_types": ["cloudfunctions.functions"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "app.appEngineService",
     "category": "app",
     "description": "An App Engine service or version.",
     "gcp_example_resource_types": ["appengine.services", "appengine.versions"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "app.workflow",
     "category": "app",
     "description": "A Cloud Workflows workflow or execution.",
     "gcp_example_resource_types": ["workflows.workflows", "workflowexecutions.executions"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "app.scheduler",
     "category": "app",
     "description": "A Cloud Scheduler job.",
     "gcp_example_resource_types": ["cloudscheduler.jobs"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "app.apiConfig",
     "category": "app",
     "description": "An API Gateway API or config.",
     "gcp_example_resource_types": ["apigateway.apis", "apigateway.apiConfigs",
                                      "apigee.apis"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    # ── observability ──
    {"type": "observability.logSink",
     "category": "observability",
     "description": "A Cloud Logging sink exporting logs.",
     "gcp_example_resource_types": ["logging.sinks", "logging.views"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "observability.logBucket",
     "category": "observability",
     "description": "A Cloud Logging log bucket.",
     "gcp_example_resource_types": ["logging.buckets"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "observability.alertPolicy",
     "category": "observability",
     "description": "A Cloud Monitoring alerting policy.",
     "gcp_example_resource_types": ["monitoring.alertPolicies",
                                      "monitoring.notificationChannels"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "observability.dashboard",
     "category": "observability",
     "description": "A Cloud Monitoring dashboard.",
     "gcp_example_resource_types": ["monitoring.dashboards"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "observability.metricDescriptor",
     "category": "observability",
     "description": "A Cloud Monitoring metric or metric descriptor.",
     "gcp_example_resource_types": ["monitoring.metricDescriptors",
                                      "monitoring.timeSeries"],
     "primary_identifier_kinds": ["gcp_full_name", "raw_id"]},
    {"type": "observability.uptimeCheck",
     "category": "observability",
     "description": "A Cloud Monitoring uptime check.",
     "gcp_example_resource_types": ["monitoring.uptimeCheckConfigs"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    # ── messaging ──
    {"type": "messaging.topic",
     "category": "messaging",
     "description": "A Pub/Sub topic or Pub/Sub Lite topic.",
     "gcp_example_resource_types": ["pubsub.topics", "pubsublite.topics"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "messaging.subscription",
     "category": "messaging",
     "description": "A Pub/Sub subscription or snapshot.",
     "gcp_example_resource_types": ["pubsub.subscriptions", "pubsub.snapshots"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "messaging.kafkaCluster",
     "category": "messaging",
     "description": "A Managed Kafka cluster or topic.",
     "gcp_example_resource_types": ["managedkafka.clusters", "managedkafka.topics"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "messaging.eventarcTrigger",
     "category": "messaging",
     "description": "An Eventarc trigger.",
     "gcp_example_resource_types": ["eventarc.triggers", "eventarc.channels"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    # ── devops ──
    {"type": "devops.artifactRepo",
     "category": "devops",
     "description": "An Artifact Registry repository.",
     "gcp_example_resource_types": ["artifactregistry.repositories",
                                      "artifactregistry.packages"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "devops.buildTrigger",
     "category": "devops",
     "description": "A Cloud Build trigger or build.",
     "gcp_example_resource_types": ["cloudbuild.triggers", "cloudbuild.builds"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "devops.deployPipeline",
     "category": "devops",
     "description": "A Cloud Deploy delivery pipeline or release.",
     "gcp_example_resource_types": ["clouddeploy.deliveryPipelines",
                                      "clouddeploy.releases"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "devops.sourceRepo",
     "category": "devops",
     "description": "A source code repository or connection.",
     "gcp_example_resource_types": ["developerconnect.connections",
                                      "securesourcemanager.repositories"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "devops.composerEnvironment",
     "category": "devops",
     "description": "A Cloud Composer (Airflow) environment.",
     "gcp_example_resource_types": ["composer.environments"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    # ── governance ──
    {"type": "governance.project",
     "category": "governance",
     "description": "A GCP project.",
     "gcp_example_resource_types": ["cloudresourcemanager.projects"],
     "primary_identifier_kinds": ["gcp_full_name", "raw_id"]},
    {"type": "governance.folder",
     "category": "governance",
     "description": "A GCP resource hierarchy folder.",
     "gcp_example_resource_types": ["cloudresourcemanager.folders"],
     "primary_identifier_kinds": ["gcp_full_name", "raw_id"]},
    {"type": "governance.organization",
     "category": "governance",
     "description": "A GCP organization node.",
     "gcp_example_resource_types": ["cloudresourcemanager.organizations"],
     "primary_identifier_kinds": ["gcp_full_name", "raw_id"]},
    {"type": "governance.billingAccount",
     "category": "governance",
     "description": "A Cloud Billing account.",
     "gcp_example_resource_types": ["cloudbilling.billingAccounts"],
     "primary_identifier_kinds": ["raw_id", "gcp_full_name"]},
    {"type": "governance.orgPolicy",
     "category": "governance",
     "description": "An organization policy constraint or policy.",
     "gcp_example_resource_types": ["orgpolicy.policies", "orgpolicy.constraints"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "governance.recommendation",
     "category": "governance",
     "description": "A recommender insight or recommendation.",
     "gcp_example_resource_types": ["recommender.recommendations",
                                      "recommender.insights"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    {"type": "governance.assetFeed",
     "category": "governance",
     "description": "A Cloud Asset Inventory feed or saved query.",
     "gcp_example_resource_types": ["cloudasset.feeds", "cloudasset.savedQueries"],
     "primary_identifier_kinds": ["gcp_full_name"]},
    # ── other ──
    {"type": "other.unknown",
     "category": "other",
     "description": "Resource type that could not be confidently classified.",
     "gcp_example_resource_types": [],
     "primary_identifier_kinds": ["gcp_full_name", "raw_id", "constructed"]},
]

EDGE_TYPES = [
    {"type": "CHILD_OF",
     "category": "hierarchy",
     "direction": "child -> parent",
     "description": "The source is a direct child of the target in the GCP resource hierarchy.",
     "gcp_examples": [
         {"from": "governance.project", "to": "governance.folder",
          "example": "project CHILD_OF folder"},
         {"from": "governance.folder", "to": "governance.organization",
          "example": "folder CHILD_OF organization"},
         {"from": "compute.disk", "to": "compute.instance",
          "example": "disk CHILD_OF instance (boot disk)"},
     ]},
    {"type": "CONTAINS",
     "category": "hierarchy",
     "direction": "parent -> child",
     "description": "The source resource logically contains the target (inverse of CHILD_OF).",
     "gcp_examples": [
         {"from": "governance.organization", "to": "governance.folder",
          "example": "organization CONTAINS folder"},
         {"from": "cloudkms.keyRing", "to": "crypto.kmsKey",
          "example": "keyRing CONTAINS cryptoKey"},
         {"from": "k8s.cluster", "to": "k8s.nodePool",
          "example": "cluster CONTAINS nodePool"},
     ]},
    {"type": "REFERENCES",
     "category": "reference",
     "direction": "source -> target",
     "description": "The source resource references the target by name or ID without a strong dependency.",
     "gcp_examples": [
         {"from": "compute.instance", "to": "compute.image",
          "example": "instance REFERENCES sourceImage"},
         {"from": "compute.instanceTemplate", "to": "compute.disk",
          "example": "instanceTemplate REFERENCES diskType"},
         {"from": "monitoring.alertPolicy", "to": "monitoring.notificationChannel",
          "example": "alertPolicy REFERENCES notificationChannelName"},
     ]},
    {"type": "USES",
     "category": "reference",
     "direction": "source -> target",
     "description": "The source resource actively uses the target as a dependency (stronger than REFERENCES).",
     "gcp_examples": [
         {"from": "run.service", "to": "iam.serviceAccount",
          "example": "cloudRunService USES serviceAccount (as runtime identity)"},
         {"from": "compute.instance", "to": "compute.machineType",
          "example": "instance USES machineType"},
         {"from": "composer.environment", "to": "storage.bucket",
          "example": "composerEnvironment USES GCS bucket for DAGs"},
     ]},
    {"type": "ATTACHED_TO",
     "category": "attachment",
     "direction": "source -> target",
     "description": "The source resource is attached or bound to the target at the infrastructure level.",
     "gcp_examples": [
         {"from": "compute.disk", "to": "compute.instance",
          "example": "disk ATTACHED_TO instance"},
         {"from": "compute.address", "to": "compute.forwardingRule",
          "example": "staticIP ATTACHED_TO forwardingRule"},
         {"from": "cert.certificate", "to": "network.loadBalancer",
          "example": "sslCert ATTACHED_TO targetHttpsProxy"},
     ]},
    {"type": "EXPOSES",
     "category": "networking",
     "direction": "source -> target",
     "description": "The source resource exposes the target service or port to a network.",
     "gcp_examples": [
         {"from": "network.loadBalancer", "to": "app.cloudRunService",
          "example": "forwardingRule EXPOSES cloudRunService"},
         {"from": "compute.instance", "to": "network.endpoint",
          "example": "instance EXPOSES networkEndpoint"},
         {"from": "apigateway.gateway", "to": "app.apiConfig",
          "example": "gateway EXPOSES apiConfig"},
     ]},
    {"type": "ALLOWS",
     "category": "networking",
     "direction": "security_rule -> target_resource",
     "description": "A firewall rule or policy allows traffic to/from the target.",
     "gcp_examples": [
         {"from": "network.firewall", "to": "compute.instance",
          "example": "firewallRule ALLOWS ingress to instance (via targetTag)"},
         {"from": "security.securityPolicy", "to": "network.loadBalancer",
          "example": "armorPolicy ALLOWS traffic to backendService"},
         {"from": "access.servicePerimeter", "to": "governance.project",
          "example": "servicePerimeter ALLOWS access to project APIs"},
     ]},
    {"type": "CONNECTS_TO",
     "category": "networking",
     "direction": "source -> target",
     "description": "The source resource establishes a network connection to the target.",
     "gcp_examples": [
         {"from": "network.vpn", "to": "network.hub",
          "example": "vpnTunnel CONNECTS_TO networkConnectivityHub"},
         {"from": "network.interconnect", "to": "network.vpc",
          "example": "interconnectAttachment CONNECTS_TO VPC network"},
         {"from": "vpcaccess.connector", "to": "network.vpc",
          "example": "vpcConnector CONNECTS_TO VPC network"},
     ]},
    {"type": "ROUTES_TO",
     "category": "networking",
     "direction": "source -> target",
     "description": "The source routes traffic to the target destination.",
     "gcp_examples": [
         {"from": "network.route", "to": "network.vpc",
          "example": "route ROUTES_TO nextHopGateway"},
         {"from": "network.loadBalancer", "to": "compute.instanceGroup",
          "example": "backendService ROUTES_TO instanceGroup"},
         {"from": "compute.router", "to": "network.vpn",
          "example": "cloudRouter ROUTES_TO vpnTunnel via BGP"},
     ]},
    {"type": "MEMBER_OF",
     "category": "identity",
     "direction": "member -> group_or_policy",
     "description": "The source identity is a member of the target group or policy binding.",
     "gcp_examples": [
         {"from": "identity.user", "to": "identity.group",
          "example": "user MEMBER_OF cloudIdentityGroup"},
         {"from": "identity.serviceAccount", "to": "identity.group",
          "example": "serviceAccount MEMBER_OF group (IAM binding)"},
         {"from": "k8s.cluster", "to": "k8s.hubMembership",
          "example": "cluster MEMBER_OF gkeHubFleet"},
     ]},
    {"type": "ASSUMES",
     "category": "identity",
     "direction": "workload -> serviceAccount",
     "description": "The source workload or identity assumes / impersonates the target service account.",
     "gcp_examples": [
         {"from": "compute.instance", "to": "identity.serviceAccount",
          "example": "instance ASSUMES serviceAccount (attached SA)"},
         {"from": "run.service", "to": "identity.serviceAccount",
          "example": "cloudRunService ASSUMES serviceAccount (runtime SA)"},
         {"from": "iam.workloadIdentityPool", "to": "identity.serviceAccount",
          "example": "externalIdentity via workloadIdentityPool ASSUMES serviceAccount"},
     ]},
    {"type": "BOUND_TO",
     "category": "identity",
     "direction": "policy -> resource",
     "description": "An IAM policy or binding is bound to a GCP resource.",
     "gcp_examples": [
         {"from": "access.policy", "to": "governance.project",
          "example": "iamPolicy BOUND_TO project"},
         {"from": "access.policy", "to": "storage.bucket",
          "example": "iamPolicy BOUND_TO bucket"},
         {"from": "orgpolicy.policy", "to": "governance.organization",
          "example": "orgPolicy BOUND_TO organization node"},
     ]},
    {"type": "GRANTS",
     "category": "access",
     "direction": "binding -> (member, role)",
     "description": "An IAM binding grants a role to a member on a resource.",
     "gcp_examples": [
         {"from": "access.policy", "to": "access.role",
          "example": "iamBinding GRANTS roles/storage.admin to serviceAccount"},
         {"from": "access.policy", "to": "identity.serviceAccount",
          "example": "iamPolicy GRANTS editor role to user@example.com"},
         {"from": "iam.workloadIdentityPool", "to": "access.role",
          "example": "workloadIdentityPool GRANTS roles/iam.workloadIdentityUser"},
     ]},
    {"type": "ENCRYPTED_BY",
     "category": "crypto",
     "direction": "resource -> key",
     "description": "The source resource's data is encrypted using the target KMS key.",
     "gcp_examples": [
         {"from": "storage.bucket", "to": "crypto.kmsKey",
          "example": "bucket ENCRYPTED_BY cloudKMSKey (CMEK)"},
         {"from": "compute.disk", "to": "crypto.kmsKey",
          "example": "persistentDisk ENCRYPTED_BY kmsKeyName"},
         {"from": "bigquery.dataset", "to": "crypto.kmsKey",
          "example": "bigqueryDataset ENCRYPTED_BY kmsKey (defaultEncryptionConfiguration)"},
     ]},
    {"type": "USES_KEY",
     "category": "crypto",
     "direction": "resource -> key_or_version",
     "description": "The source uses a KMS key or key version for signing, decryption, or wrapping.",
     "gcp_examples": [
         {"from": "cert.certificateAuthority", "to": "crypto.kmsKey",
          "example": "certificateAuthority USES_KEY cloudKMSKeyVersion for signing"},
         {"from": "cloudkms.importJob", "to": "crypto.kmsKey",
          "example": "importJob USES_KEY wrappingPublicKey"},
         {"from": "cloudkms.ekmConnection", "to": "crypto.kmsKey",
          "example": "ekmConnection USES_KEY external key via EKM"},
     ]},
    {"type": "USES_CERT",
     "category": "cert",
     "direction": "resource -> certificate",
     "description": "The source resource uses a TLS/SSL certificate for serving or authentication.",
     "gcp_examples": [
         {"from": "network.loadBalancer", "to": "cert.certificate",
          "example": "targetHttpsProxy USES_CERT sslCertificate"},
         {"from": "compute.instance", "to": "cert.certificate",
          "example": "managedSSLCert USES_CERT on loadBalancer frontend"},
         {"from": "cert.certificateMap", "to": "cert.certificate",
          "example": "certificateMapEntry USES_CERT certificate"},
     ]},
    {"type": "ISSUED_BY",
     "category": "cert",
     "direction": "certificate -> authority",
     "description": "The source certificate was issued by the target certificate authority.",
     "gcp_examples": [
         {"from": "cert.certificate", "to": "cert.certificateAuthority",
          "example": "privateCACert ISSUED_BY certificateAuthority"},
         {"from": "cert.certificate", "to": "privateca.caPool",
          "example": "certificate ISSUED_BY caPool"},
     ]},
    {"type": "TRUSTS",
     "category": "cert",
     "direction": "resource -> authority_or_pool",
     "description": "The source resource trusts certificates from the target authority or pool.",
     "gcp_examples": [
         {"from": "k8s.cluster", "to": "cert.certificateAuthority",
          "example": "gkeCluster TRUSTS privateCertificateAuthority"},
         {"from": "iam.workloadIdentityPool", "to": "identity.oauthClient",
          "example": "workloadIdentityPool TRUSTS external OIDC issuer"},
     ]},
]

ID_KINDS = [
    "gcp_full_name",   # projects/{p}/locations/{l}/.../{id}
    "constructed",     # built from fields + transforms (e.g. sites/{url_encoded_site})
    "tuple",           # (project, zone, name) — no canonical full-name path
    "raw_id",          # bare numeric or string id
    "email",           # service account email, user email
    "url",             # URL as identifier (e.g. reviewedSite domain)
]


# ─────────────────────────────────────────────────────────────────────────────
# CLASSIFICATION RULES  (deterministic heuristics)
# ─────────────────────────────────────────────────────────────────────────────

# (service_keyword_patterns, resource_keyword_patterns) → (category, generic_node_type, base_confidence)
# Evaluated in order; first match wins.  Both are checked against lowercased strings.

_RULES = [
    # ── kubernetes ──────────────────────────────────────────────────────────
    (r'container|gkebackup|gkehub|gkeonprem|hypercomputecluster',
     r'cluster',             'kubernetes', 'k8s.cluster',            0.95),
    (r'container|gkebackup|gkehub|gkeonprem',
     r'nodepool|node_pool',  'kubernetes', 'k8s.nodePool',           0.95),
    (r'gkebackup',
     r'backup|restore',      'kubernetes', 'k8s.backupPlan',         0.90),
    (r'gkehub',
     r'membership|feature',  'kubernetes', 'k8s.hubMembership',      0.90),
    # container sub-resources that aren't clusters
    (r'container',
     r'operation|location|zone|region|usablesubnetwork|well.known', 'governance', 'governance.project', 0.70),
    (r'container',
     r'.*',                  'kubernetes', 'k8s.cluster',            0.80),
    # ── crypto / KMS ────────────────────────────────────────────────────────
    (r'cloudkms|kmsinventory',
     r'keyring|key_ring',    'crypto',     'crypto.keyRing',         0.97),
    (r'cloudkms|kmsinventory',
     r'cryptokey(?!version)', 'crypto',    'crypto.kmsKey',          0.97),
    (r'cloudkms|kmsinventory',
     r'cryptokeyversion|key_version', 'crypto', 'crypto.kmsKeyVersion', 0.97),
    (r'cloudkms|kmsinventory',
     r'ekmconnection|ekm',   'crypto',     'crypto.ekmConnection',   0.95),
    (r'cloudkms|kmsinventory',
     r'importjob|keyhandle', 'crypto',     'crypto.kmsKey',          0.88),
    # cloudkms admin/metadata sub-resources
    (r'cloudkms',
     r'operation|location|project|folder|organization|ekm_config|ekmconfig|proposal|retiredresource|singletenanthsm', 'governance', 'governance.project', 0.72),
    (r'cloudkms|kmsinventory',
     r'.*',                  'crypto',     'crypto.kmsKey',          0.80),
    (r'secretmanager|parametermanager',
     r'secret|parameter',    'crypto',     'crypto.secret',          0.95),
    (r'secretmanager',
     r'version|location|operation', 'crypto', 'crypto.secret',       0.87),
    (r'secretmanager|parametermanager',
     r'.*',                  'crypto',     'crypto.secret',          0.85),
    # ── cert ────────────────────────────────────────────────────────────────
    (r'certificatemanager',
     r'certificate(?!map|authority)', 'cert', 'cert.certificate',    0.97),
    (r'certificatemanager',
     r'certificatemap',      'cert',       'cert.certificateMap',    0.97),
    (r'certificatemanager',
     r'.*',                  'cert',       'cert.certificate',       0.85),
    (r'privateca',
     r'capool|ca_pool',      'cert',       'cert.certificateAuthority', 0.95),
    (r'privateca',
     r'certificateauthority|certificate_authority', 'cert', 'cert.certificateAuthority', 0.97),
    (r'privateca',
     r'certificate(?!authority)', 'cert',  'cert.certificate',       0.90),
    (r'privateca',
     r'.*',                  'cert',       'cert.certificateAuthority', 0.80),
    (r'.*',
     r'sslcertificate|ssl_certificate', 'cert', 'cert.certificate',  0.92),
    (r'.*',
     r'sslpolicies|ssl_policy', 'cert',   'cert.sslPolicy',         0.90),
    # ── identity ────────────────────────────────────────────────────────────
    (r'iam|iamcredentials',
     r'serviceaccount(?!key)', 'identity', 'identity.serviceAccount', 0.97),
    (r'iam|iamcredentials',
     r'key',                  'identity', 'identity.serviceAccountKey', 0.90),
    (r'iam|iamcredentials',
     r'workloadidentitypool|workload_identity', 'identity', 'identity.workloadIdentityPool', 0.95),
    (r'iam|iamcredentials',
     r'workforcepool|workforce', 'identity', 'identity.workforcePool', 0.95),
    (r'iam|iamcredentials',
     r'oauthclient|oauth_client', 'identity', 'identity.oauthClient', 0.93),
    (r'iam|iamcredentials',
     r'provider',             'identity',  'identity.workloadIdentityPool', 0.85),
    (r'iam|iamcredentials',
     r'role',                 'access',    'access.role',             0.95),
    # IAM sub-resources: credentials, tokens, operations, namespaces, scimTenants, managedIdentities
    (r'iam',
     r'credential|token',     'identity',  'identity.serviceAccount', 0.82),
    (r'iam',
     r'operation|location',   'governance', 'governance.project',     0.72),
    (r'iam',
     r'namespace|scimtenant', 'identity',  'identity.workloadIdentityPool', 0.78),
    (r'iam',
     r'managedidentit',       'identity',  'identity.serviceAccount', 0.80),
    (r'iam|iamcredentials',
     r'.*',                   'identity',  'identity.serviceAccount', 0.70),
    (r'cloudidentity|admin',
     r'group',                'identity',  'identity.group',          0.93),
    (r'cloudidentity|admin',
     r'user',                 'identity',  'identity.user',           0.93),
    (r'cloudidentity|admin',
     r'.*',                   'identity',  'identity.user',           0.75),
    (r'identitytoolkit',
     r'.*',                   'identity',  'identity.user',           0.75),
    (r'oauth2',
     r'.*',                   'identity',  'identity.oauthClient',    0.75),
    # ── access ──────────────────────────────────────────────────────────────
    (r'accesscontextmanager',
     r'accesslevel|access_level', 'access', 'access.accessLevel',    0.95),
    (r'accesscontextmanager',
     r'serviceperimeter|service_perimeter', 'access', 'access.servicePerimeter', 0.95),
    (r'accesscontextmanager',
     r'.*',                   'access',    'access.policy',           0.85),
    (r'orgpolicy',
     r'policy|constraint',    'governance', 'governance.orgPolicy',   0.93),
    (r'iap',
     r'.*',                   'access',    'access.policy',           0.80),
    # ── security ────────────────────────────────────────────────────────────
    (r'securitycenter|securityposture',
     r'finding',              'security',  'security.finding',        0.95),
    (r'securitycenter|securityposture',
     r'source|muteconfig|notificationconfig', 'security', 'security.finding', 0.88),
    (r'securitycenter|securityposture',
     r'.*',                   'security',  'security.finding',        0.80),
    (r'ids',
     r'endpoint',             'security',  'security.idsEndpoint',    0.95),
    (r'binaryauthorization',
     r'.*',                   'security',  'security.binaryAuthPolicy', 0.90),
    (r'dlp',
     r'.*',                   'security',  'security.dlpInspectTemplate', 0.88),
    (r'webrisk',
     r'.*',                   'security',  'security.finding',        0.80),
    (r'safebrowsing',
     r'.*',                   'security',  'security.finding',        0.75),
    (r'.*',
     r'firewall(?!policy)',   'security',  'security.firewallPolicy', 0.88),
    (r'.*',
     r'firewallpolicies|firewall_policy', 'security', 'security.firewallPolicy', 0.90),
    (r'.*',
     r'securitypolicies|security_policy', 'security', 'security.securityPolicy', 0.90),
    (r'networksecurity',
     r'.*',                   'security',  'security.firewallPolicy', 0.82),
    # ── storage ─────────────────────────────────────────────────────────────
    (r'storage|storagebatchoperations|storagetransfer',
     r'bucket(?!access)',     'storage',   'storage.bucket',          0.97),
    # Storage objects, ACLs, HMAC keys etc. are bucket-related sub-resources
    (r'storage',
     r'object|folder|managedfolder', 'storage', 'storage.bucket',    0.90),
    (r'storage',
     r'bucketaccesscontrol|objectaccesscontrol|defaultobjectaccesscontrol|hmackey|notification|serviceaccount', 'storage', 'storage.bucket', 0.87),
    (r'storage',
     r'operation|anywherecache', 'storage', 'storage.bucket',         0.85),
    (r'storage|storagebatchoperations|storagetransfer',
     r'.*',                   'storage',   'storage.bucket',          0.80),
    (r'file',
     r'.*',                   'storage',   'storage.fileShare',       0.90),
    (r'backupdr',
     r'.*',                   'storage',   'storage.backupVault',     0.88),
    (r'netapp',
     r'volume',               'storage',   'storage.netappVolume',    0.95),
    (r'netapp',
     r'storagepool|storage_pool', 'storage', 'storage.netappVolume',  0.88),
    (r'netapp',
     r'.*',                   'storage',   'storage.netappVolume',    0.80),
    # ── data ────────────────────────────────────────────────────────────────
    (r'sqladmin',
     r'.*',                   'data',      'data.sqlInstance',        0.95),
    (r'oracledatabase',
     r'.*',                   'data',      'data.sqlInstance',        0.88),
    (r'alloydb',
     r'.*',                   'data',      'data.sqlInstance',        0.90),
    (r'spanner',
     r'.*',                   'data',      'data.spannerInstance',    0.95),
    (r'bigquery(?!connection|datapolicy|datatransfer|reservation)',
     r'dataset',              'data',      'data.bigqueryDataset',    0.97),
    (r'bigquery(?!connection|datapolicy|datatransfer|reservation)',
     r'table|model|routine|rowaccesspolicies|tabledata', 'data', 'data.bigqueryDataset', 0.93),
    (r'bigquery(?!connection|datapolicy|datatransfer|reservation)',
     r'job|project',          'data',      'data.bigqueryDataset',    0.88),
    (r'bigquery(?!connection|datapolicy|datatransfer|reservation)',
     r'.*',                   'data',      'data.bigqueryDataset',    0.93),
    (r'bigqueryconnection|bigquerydatapolicy|bigquerydatatransfer|bigqueryreservation',
     r'.*',                   'data',      'data.bigqueryDataset',    0.85),
    (r'bigtableadmin',
     r'.*',                   'data',      'data.bigtableInstance',   0.93),
    (r'datastore|firestore',
     r'.*',                   'data',      'data.firestoreDatabase',  0.90),
    (r'firebase(?!appcheck|appdistribution|apphosting|dynamiclinks|hosting|ml|rules|storage)',
     r'.*',                   'data',      'data.firestoreDatabase',  0.75),
    (r'dataflow|datastream',
     r'.*',                   'data',      'data.datastreamJob',      0.88),
    (r'redis',
     r'.*',                   'data',      'data.redisInstance',      0.95),
    (r'memcache',
     r'.*',                   'data',      'data.redisInstance',      0.90),
    (r'dataproc',
     r'.*',                   'data',      'data.dataprocCluster',    0.93),
    (r'metastore',
     r'.*',                   'data',      'data.dataprocCluster',    0.82),
    (r'dataplex|datacatalog|datalineage|datalabeling|datafusion|datamanager|datamigration|datapipelines|dataform|analyticshub|analyticsdata',
     r'.*',                   'data',      'data.bigqueryDataset',    0.78),
    # ── messaging ───────────────────────────────────────────────────────────
    (r'pubsub(?!lite)',
     r'topic',                'messaging', 'messaging.topic',         0.97),
    (r'pubsub(?!lite)',
     r'subscription|snapshot', 'messaging', 'messaging.subscription', 0.97),
    (r'pubsub(?!lite)',
     r'.*',                   'messaging', 'messaging.topic',         0.85),
    (r'pubsublite',
     r'.*',                   'messaging', 'messaging.topic',         0.90),
    (r'managedkafka',
     r'cluster',              'messaging', 'messaging.kafkaCluster',  0.95),
    (r'managedkafka',
     r'topic|consumer',       'messaging', 'messaging.topic',         0.90),
    (r'managedkafka',
     r'.*',                   'messaging', 'messaging.kafkaCluster',  0.82),
    (r'eventarc',
     r'.*',                   'messaging', 'messaging.eventarcTrigger', 0.90),
    # ── app ─────────────────────────────────────────────────────────────────
    (r'run',
     r'service',              'app',       'app.cloudRunService',     0.97),
    (r'run',
     r'job',                  'app',       'app.cloudRunService',     0.93),
    (r'run',
     r'execution|task|revision|workerpool', 'app', 'app.cloudRunService', 0.90),
    (r'run',
     r'domainmapping|authorizedomain', 'app', 'app.cloudRunService', 0.87),
    (r'run',
     r'configuration|route',  'app',       'app.cloudRunService',     0.85),
    (r'run',
     r'operation|location|instance', 'governance', 'governance.project', 0.75),
    (r'run',
     r'.*',                   'app',       'app.cloudRunService',     0.85),
    (r'cloudfunctions',
     r'.*',                   'app',       'app.cloudFunction',       0.95),
    (r'appengine',
     r'.*',                   'app',       'app.appEngineService',    0.93),
    (r'workflows|workflowexecutions',
     r'.*',                   'app',       'app.workflow',            0.92),
    (r'cloudscheduler|cloudtasks',
     r'.*',                   'app',       'app.scheduler',           0.88),
    (r'apigateway|apigee|apigeeregistry|apihub|apim',
     r'.*',                   'app',       'app.apiConfig',           0.88),
    (r'dialogflow|contactcenteraiplatform|contactcenterinsights',
     r'.*',                   'app',       'app.apiConfig',           0.75),
    # ── observability ────────────────────────────────────────────────────────
    (r'logging',
     r'sink',                 'observability', 'observability.logSink',    0.97),
    (r'logging',
     r'bucket',               'observability', 'observability.logBucket',  0.95),
    (r'logging',
     r'view|exclusion|log(?!s)|logscope', 'observability', 'observability.logSink', 0.88),
    (r'logging',
     r'metric',               'observability', 'observability.metricDescriptor', 0.90),
    (r'logging',
     r'entry|entries|savedquery|recentquery|monitoredresourcedescriptor', 'observability', 'observability.logSink', 0.85),
    # Logging scope containers (billingAccounts, folders, organizations, projects)
    # are governance-level — the resource is the log scope, not the container
    (r'logging',
     r'billingaccount|organization|folder|project|location|operation|link|v2', 'observability', 'observability.logSink', 0.82),
    (r'logging',
     r'.*',                   'observability', 'observability.logSink',    0.82),
    (r'monitoring|observability',
     r'alertpolicies|alertpolicy|alert(?!s)', 'observability', 'observability.alertPolicy', 0.95),
    (r'monitoring|observability',
     r'^alerts$',             'observability', 'observability.alertPolicy', 0.90),
    (r'monitoring|observability',
     r'dashboard',            'observability', 'observability.dashboard',  0.95),
    (r'monitoring|observability',
     r'metricdescriptor|metric(?!s)', 'observability', 'observability.metricDescriptor', 0.92),
    (r'monitoring|observability',
     r'uptimecheckconfig|uptimecheck|uptime', 'observability', 'observability.uptimeCheck', 0.92),
    (r'monitoring|observability',
     r'notificationchannel(?!descriptor)', 'observability', 'observability.alertPolicy', 0.90),
    (r'monitoring|observability',
     r'servicelevelobjective|slo',  'observability', 'observability.uptimeCheck', 0.87),
    (r'monitoring|observability',
     r'snooze|group|member|service|monitoredresource|notificationchanneldescriptor|timeseries|uptimecheckip', 'observability', 'observability.alertPolicy', 0.85),
    (r'monitoring|observability',
     r'.*',                   'observability', 'observability.alertPolicy', 0.78),
    (r'cloudtrace|cloudprofiler|clouderrorreporting',
     r'.*',                   'observability', 'observability.logSink',    0.78),
    # ── devops ───────────────────────────────────────────────────────────────
    (r'artifactregistry',
     r'.*',                   'devops',    'devops.artifactRepo',     0.95),
    (r'cloudbuild',
     r'trigger',              'devops',    'devops.buildTrigger',     0.95),
    (r'cloudbuild',
     r'build',                'devops',    'devops.buildTrigger',     0.88),
    (r'cloudbuild',
     r'.*',                   'devops',    'devops.buildTrigger',     0.82),
    (r'clouddeploy',
     r'.*',                   'devops',    'devops.deployPipeline',   0.93),
    (r'developerconnect|securesourcemanager',
     r'.*',                   'devops',    'devops.sourceRepo',       0.90),
    (r'composer',
     r'.*',                   'devops',    'devops.composerEnvironment', 0.93),
    (r'deploymentmanager',
     r'.*',                   'devops',    'devops.buildTrigger',     0.78),
    (r'config',
     r'.*',                   'devops',    'devops.deployPipeline',   0.75),
    # ── governance ───────────────────────────────────────────────────────────
    (r'cloudresourcemanager',
     r'project',              'governance', 'governance.project',      0.97),
    (r'cloudresourcemanager',
     r'folder',               'governance', 'governance.folder',       0.97),
    (r'cloudresourcemanager',
     r'organization',         'governance', 'governance.organization', 0.97),
    (r'cloudresourcemanager',
     r'.*',                   'governance', 'governance.project',      0.80),
    (r'cloudbilling',
     r'.*',                   'governance', 'governance.billingAccount', 0.90),
    (r'recommender',
     r'.*',                   'governance', 'governance.recommendation', 0.90),
    (r'cloudasset',
     r'.*',                   'governance', 'governance.assetFeed',    0.88),
    (r'policyanalyzer|policysimulator',
     r'.*',                   'governance', 'governance.orgPolicy',    0.82),
    (r'assuredworkloads',
     r'.*',                   'governance', 'governance.orgPolicy',    0.80),
    (r'serviceusage|servicemanagement|serviceconsumermanagement|servicenetworking',
     r'.*',                   'governance', 'governance.project',      0.75),
    (r'cloudcommerceprocurement|reseller|licensing',
     r'.*',                   'governance', 'governance.billingAccount', 0.72),
    # ── network (compute-based network resources) ─────────────────────────
    # subnetwork MUST come before the broader "network" rule
    (r'compute',
     r'subnetwork',           'network',   'network.subnet',          0.97),
    (r'compute',
     r'network(?!endpoint|profile|attachment|subnet)',  'network',   'network.vpc', 0.95),
    (r'compute|dns',
     r'route|router',         'network',   'network.route',           0.93),
    (r'compute',
     r'forwardingrule|targethttp|targethttps|urlmap|backendservice|backendbalancer|targetpool|targetinstance|healthcheck',
                              'network',   'network.loadBalancer',    0.90),
    (r'compute',
     r'vpngateway|vpntunnel|externalvpn|targetvpn', 'network', 'network.vpn', 0.95),
    (r'compute',
     r'interconnect',         'network',   'network.interconnect',    0.95),
    (r'compute',
     r'address|globaladdress', 'network',  'network.address',         0.93),
    (r'compute',
     r'networkendpoint',      'network',   'network.endpoint',        0.90),
    (r'compute',
     r'serviceattachment|networkattachment', 'network', 'network.endpoint', 0.88),
    (r'compute',
     r'firewallpolicies|networkfirewallpolicies|organizationsecuritypolicies|networkedgesecurity', 'security', 'security.firewallPolicy', 0.92),
    (r'compute',
     r'firewall(?!policies)',  'security',  'security.firewallPolicy', 0.93),
    (r'compute',
     r'securitypolicies|regionsecuritypolicies', 'security', 'security.securityPolicy', 0.92),
    (r'dns',
     r'managedzone|policy|record', 'network', 'network.dnsZone',     0.93),
    (r'networkconnectivity',
     r'hub|spoke',            'network',   'network.hub',             0.93),
    (r'networkconnectivity|networkmanagement|networkservices',
     r'.*',                   'network',   'network.hub',             0.80),
    (r'vpcaccess',
     r'.*',                   'network',   'network.endpoint',        0.85),
    # ── compute (everything else in compute service) ──────────────────────
    (r'compute',
     r'instance(?!group|template|settings)', 'compute', 'compute.instance', 0.95),
    (r'compute',
     r'disk|snapshot|storagepool|disktype|storagepooltype', 'compute', 'compute.disk', 0.93),
    (r'compute',
     r'image|machineimage',   'compute',   'compute.image',           0.93),
    (r'compute',
     r'instancetemplate|regioninstancetemplate', 'compute', 'compute.instanceTemplate', 0.93),
    (r'compute',
     r'instancegroup|managedinstancegroup|resizerequest', 'compute', 'compute.instanceGroup', 0.93),
    (r'compute',
     r'accelerator|tpu',      'compute',   'compute.accelerator',     0.90),
    (r'compute',
     r'reservation(?!block|slot|subblock)|reservationblock|reservationslot|reservationsubblock', 'compute', 'compute.reservation', 0.90),
    (r'compute',
     r'autoscaler|regionautoscaler', 'compute', 'compute.instance',  0.85),
    (r'compute',
     r'nodegroup|nodetemplate|nodetype', 'compute', 'compute.instance', 0.85),
    (r'compute',
     r'packetmirroring|wiregroup', 'network', 'network.vpc',          0.80),
    (r'compute',
     r'machinetype',          'compute',   'compute.instance',        0.85),
    (r'compute',
     r'backendservice|regionbackendservice|backendbucket|healthcheck|httphealthcheck|httpshealthcheck|regionhealthcheck|regionhealthcheckservice', 'network', 'network.loadBalancer', 0.90),
    (r'compute',
     r'sslcertificate|regionsslcertificate', 'cert', 'cert.certificate', 0.92),
    (r'compute',
     r'sslpolicies|regionsslpolicies', 'cert', 'cert.sslPolicy',     0.90),
    (r'compute',
     r'targetgrpcproxies|targetsslproxies|targettcpproxies|regiontargettcpproxies|regiontargethttpproxies|regiontargethttpsproxies', 'network', 'network.loadBalancer', 0.88),
    (r'compute',
     r'regionurlmap|urlurlmap', 'network', 'network.loadBalancer',   0.87),
    (r'compute',
     r'commitment|regioncommitment', 'governance', 'governance.billingAccount', 0.78),
    # operations, zones, regions, projects are metadata
    (r'compute',
     r'operation|globaloperation|zoneoperaton|regionoperation|globalorganizationoperation', 'governance', 'governance.project', 0.72),
    (r'compute',
     r'^zone$|^zones$|^region$|^regions$|^project$|^projects$|region_zones|regionzones', 'governance', 'governance.project', 0.75),
    (r'compute',
     r'licensecode|license(?!code)|publicicadvertisedprefix|publicdelegatedprefix|globalpublicdelegatedprefix|previewfeature|networkprofile|instancesetting', 'governance', 'governance.project', 0.72),
    (r'compute',
     r'interconnectlocation|interconnectreomotelocation', 'network', 'network.interconnect', 0.85),
    (r'compute',
     r'notificationendpoint|regionnotificationendpoint', 'observability', 'observability.alertPolicy', 0.78),
    (r'compute',
     r'resourcepolicies|resourcepolicy', 'governance', 'governance.orgPolicy', 0.78),
    (r'compute',
     r'imagefamily|imagefamilyview', 'compute', 'compute.image',     0.87),
    (r'compute',
     r'instantsnapshot|regioninstantsnapshot', 'compute', 'compute.disk', 0.87),
    (r'compute',
     r'futurereservation', 'compute', 'compute.reservation',         0.87),
    (r'compute',
     r'crosssitenetwork', 'network', 'network.vpc',                  0.82),
    (r'compute',
     r'snapshotsetting', 'governance', 'governance.orgPolicy',       0.78),
    (r'compute',
     r'publicadvertisedprefix', 'network', 'network.address',        0.85),
    (r'compute',
     r'.*',                   'compute',   'compute.instance',        0.70),
    (r'tpu',
     r'.*',                   'compute',   'compute.accelerator',     0.90),
    (r'baremetalsolution|hypercomputecluster|parallelstore',
     r'.*',                   'compute',   'compute.instance',        0.82),
    (r'batch',
     r'.*',                   'compute',   'compute.instance',        0.78),
    (r'notebooks|ml',
     r'.*',                   'compute',   'compute.instance',        0.78),
    # ── catch-all for specific tricky services ────────────────────────────
    (r'abusiveexperiencereport|adexperiencereport',
     r'.*',                   'security',  'security.finding',        0.72),
    (r'safebrowsing|webrisk',
     r'.*',                   'security',  'security.finding',        0.72),
    (r'recaptchaenterprise',
     r'.*',                   'security',  'security.finding',        0.70),
    (r'websecurityscanner',
     r'.*',                   'security',  'security.finding',        0.72),
    (r'essentialcontacts',
     r'.*',                   'governance', 'governance.orgPolicy',   0.72),
    (r'cloudsupport',
     r'.*',                   'governance', 'governance.recommendation', 0.70),
    (r'cloudlocationfinder|civicinfo|airquality|pollen|solar|places',
     r'.*',                   'other',     'other.unknown',            0.45),
    (r'maps|pagespeedonline|customsearch|kgsearch|factchecktools|digitalassetlinks|indexing',
     r'.*',                   'other',     'other.unknown',            0.42),
    (r'blogger|books|calendar|classroom|docs|drive|driveactivity|drivelabels|fitness|forms|gmail|keep|people|sheets|slides|tasks|youtube|youtubereporting',
     r'.*',                   'other',     'other.unknown',            0.50),
    (r'admob|analytics|analyticsadmin|androidmanagement|androidpublisher|androidenterprise|androiddeviceprovisioning',
     r'.*',                   'other',     'other.unknown',            0.50),
    (r'adsense|adsenseplatform|displayvideo|doubleclicksearch|searchads360|content|css|manufacturers|merchantapi|walletobjects',
     r'.*',                   'other',     'other.unknown',            0.50),
    (r'games|gamesconfiguration|gamesmanagement',
     r'.*',                   'other',     'other.unknown',            0.48),
    (r'chat|meet|homegraph|smartdevicemanagement|workspaceevents',
     r'.*',                   'other',     'other.unknown',            0.50),
    (r'businessprofileperformance|mybusiness.*|localservices|marketingplatformadmin',
     r'.*',                   'other',     'other.unknown',            0.48),
    (r'paymentsresellersubscription|authorizedbuyersmarketplace|realtimebidding|ces',
     r'.*',                   'other',     'other.unknown',            0.48),
    (r'script|tagmanager|appsmarket|siteVerification|chromepolicy|chromemanagement|chromewebstore',
     r'.*',                   'other',     'other.unknown',            0.50),
    (r'streetviewpublish|versionhistory|discovery|libraryagent',
     r'.*',                   'other',     'other.unknown',            0.45),
    (r'speech|texttospeech|vision|videointelligence|translate|documentai|aiplatform|ml|discoveryengine|retail|recommendationengine',
     r'.*',                   'app',       'app.apiConfig',            0.65),
    (r'healthcare',
     r'.*',                   'data',      'data.firestoreDatabase',   0.70),
    (r'vault',
     r'.*',                   'governance', 'governance.orgPolicy',    0.78),
    (r'checks',
     r'.*',                   'security',  'security.finding',         0.68),
    (r'migrationcenter|rapidmigrationassessment|vmmigration',
     r'.*',                   'governance', 'governance.recommendation', 0.72),
    (r'ondemandscanning|containeranalysis',
     r'.*',                   'security',  'security.finding',         0.80),
    (r'managedidentities',
     r'.*',                   'identity',  'identity.group',           0.80),
    (r'beyondcorp',
     r'.*',                   'access',    'access.policy',            0.80),
    (r'iamcredentials',
     r'token|credential',     'identity',  'identity.serviceAccount',  0.82),
    (r'osconfig|oslogin',
     r'.*',                   'governance', 'governance.orgPolicy',    0.72),
    (r'cloudsearch',
     r'.*',                   'data',      'data.bigqueryDataset',     0.65),
    (r'cloudshell',
     r'.*',                   'compute',   'compute.instance',         0.68),
    (r'testing|toolresults',
     r'.*',                   'devops',    'devops.buildTrigger',      0.68),
    (r'transcoder|videointelligence',
     r'.*',                   'app',       'app.apiConfig',            0.65),
    (r'integrations',
     r'.*',                   'app',       'app.apiConfig',            0.72),
    (r'looker',
     r'.*',                   'data',      'data.bigqueryDataset',     0.72),
    (r'workloadmanager|saasservicemgmt',
     r'.*',                   'governance', 'governance.recommendation', 0.70),
    (r'contentwarehouse',
     r'.*',                   'data',      'data.bigqueryDataset',     0.68),
    (r'datastoremode|dataportability',
     r'.*',                   'data',      'data.firestoreDatabase',   0.65),
    (r'firebaserules|firebaseappcheck',
     r'.*',                   'security',  'security.binaryAuthPolicy', 0.72),
    (r'firebaseappdistribution|firebaseapphosting|firebasehosting|firebasedynamiclinks|firebaseml',
     r'.*',                   'app',       'app.cloudRunService',      0.70),
    (r'firebasedatabase|firebasedataconnect|firebasestorage',
     r'.*',                   'data',      'data.firestoreDatabase',   0.72),
    (r'readerrevenuesubscriptionlinking|playdeveloperreporting',
     r'.*',                   'other',     'other.unknown',            0.48),
    (r'ids',
     r'.*',                   'security',  'security.idsEndpoint',     0.88),
    (r'cloudidentity',
     r'.*',                   'identity',  'identity.group',           0.82),
    (r'domains',
     r'.*',                   'network',   'network.dnsZone',          0.72),
    (r'servicedirectory',
     r'.*',                   'network',   'network.endpoint',         0.78),
    (r'apphub',
     r'.*',                   'governance', 'governance.project',      0.72),
    (r'runtimeconfig',
     r'.*',                   'governance', 'governance.orgPolicy',    0.65),
    (r'pubsub|pubsublite',
     r'.*',                   'messaging', 'messaging.topic',          0.85),
    (r'biglakelake|biglake',
     r'.*',                   'data',      'data.bigqueryDataset',     0.80),
    (r'prod_tt_sasportal|sasportal',
     r'.*',                   'governance', 'governance.project',      0.60),
    # ── GCP infrastructure services missing from above ────────────────────
    (r'dns',
     r'managedzone',          'network',   'network.dnsZone',          0.97),
    (r'dns',
     r'policy|responsepolicy|responsepolicyrule', 'network', 'network.dnsZone', 0.92),
    (r'dns',
     r'change|dnskey|managedzoneopertion|resourcerecordset', 'network', 'network.dnsZone', 0.88),
    (r'dns',
     r'project',              'governance', 'governance.project',      0.75),
    (r'dns',
     r'.*',                   'network',   'network.dnsZone',          0.85),
    (r'gkehub',
     r'membership',           'kubernetes', 'k8s.hubMembership',       0.95),
    (r'gkehub',
     r'feature|scope|fleet',  'kubernetes', 'k8s.hubMembership',       0.88),
    (r'gkehub',
     r'.*',                   'kubernetes', 'k8s.hubMembership',       0.82),
    (r'gkebackup',
     r'backupplan|backup_plan|restore', 'kubernetes', 'k8s.backupPlan', 0.93),
    (r'gkebackup',
     r'.*',                   'kubernetes', 'k8s.backupPlan',          0.85),
    (r'accessapproval',
     r'.*',                   'access',    'access.policy',            0.82),
    (r'workstations',
     r'cluster|config|workstation', 'compute', 'compute.instance',    0.85),
    (r'workstations',
     r'.*',                   'compute',   'compute.instance',         0.80),
    (r'connectors',
     r'connection|provider|connector', 'devops', 'devops.sourceRepo',  0.78),
    (r'connectors',
     r'.*',                   'devops',    'devops.sourceRepo',         0.72),
    (r'apikeys',
     r'.*',                   'access',    'access.policy',             0.80),
    (r'alertcenter',
     r'.*',                   'security',  'security.finding',          0.80),
    (r'advisorynotifications',
     r'.*',                   'governance', 'governance.recommendation', 0.78),
    (r'cloudcontrolspartner',
     r'.*',                   'governance', 'governance.orgPolicy',     0.75),
    (r'jobs',
     r'.*',                   'app',       'app.scheduler',             0.75),
    (r'fcmdata',
     r'.*',                   'messaging', 'messaging.topic',           0.70),
    (r'chromepolicy',
     r'.*',                   'governance', 'governance.orgPolicy',     0.75),
    (r'groupssettings',
     r'.*',                   'identity',  'identity.group',            0.75),
    (r'billingbudgets',
     r'.*',                   'governance', 'governance.billingAccount', 0.82),
    (r'orgpolicy',
     r'.*',                   'governance', 'governance.orgPolicy',     0.90),
    (r'blockchainnodeengine',
     r'.*',                   'compute',   'compute.instance',         0.70),
    (r'vmwareengine',
     r'.*',                   'compute',   'compute.instance',         0.82),
    (r'gkeonprem',
     r'.*',                   'kubernetes', 'k8s.cluster',             0.82),
    (r'threatintelligence',
     r'.*',                   'security',  'security.finding',         0.78),
    (r'kmsinventory',
     r'.*',                   'crypto',    'crypto.kmsKey',            0.85),
]


def _classify(service: str, resource_type: str) -> tuple[str, str, float, str]:
    """
    Classify (service, resource_type) → (category, generic_node_type, confidence, notes).
    """
    svc_l  = service.lower()
    res_l  = resource_type.lower()

    for svc_pat, res_pat, category, node_type, conf in _RULES:
        if re.search(svc_pat, svc_l) and re.search(res_pat, res_l):
            # Boost confidence slightly if both patterns are non-wildcard
            is_both_specific = svc_pat != r'.*' and res_pat != r'.*'
            final_conf = min(conf + (0.02 if is_both_specific else 0.0), 1.0)
            notes = ''
            if final_conf < 0.6:
                notes = f'Low confidence: service={service}, resource={resource_type}'
            elif res_pat == r'.*' and svc_pat != r'.*':
                notes = 'Resource pattern wildcard — classified by service name only.'
            elif svc_pat == r'.*':
                notes = 'Service pattern wildcard — classified by resource name only.'
            return category, node_type, round(final_conf, 3), notes

    return 'other', 'other.unknown', 0.40, \
           f'No matching rule for service={service}, resource_type={resource_type}'


def _id_kind_from_catalog(rdata: dict) -> str:
    """Map catalog identifier.kind → ontology id_kinds value."""
    kind_map = {
        'full_name':   'gcp_full_name',
        'constructed': 'constructed',
        'tuple':       'tuple',
    }
    catalog_kind = rdata.get('identifier', {}).get('kind', 'tuple')

    # Special: if constructed kind is "url" by nature (e.g. reviewedSite)
    transforms = rdata.get('identifier', {}).get('transforms', [])
    if catalog_kind == 'constructed' and transforms:
        for t in transforms:
            if t.get('fn') == 'url_encode':
                return 'constructed'   # URL-encoded constructed

    # Check part_sources for email fields
    parts = rdata.get('identifier', {}).get('parts', [])
    for p in parts:
        if 'email' in p.lower() or 'account' in p.lower():
            # Could be email; defer to service
            pass

    return kind_map.get(catalog_kind, 'gcp_full_name')


# ─────────────────────────────────────────────────────────────────────────────
# MAIN BUILD FUNCTIONS
# ─────────────────────────────────────────────────────────────────────────────

def build_ontology() -> dict:
    return {
        "version": "1.0",
        "generated_at": _now_iso(),
        "categories": sorted(CATEGORIES, key=lambda x: x['category']),
        "generic_node_types": sorted(GENERIC_NODE_TYPES, key=lambda x: x['type']),
        "edge_types": sorted(EDGE_TYPES, key=lambda x: x['type']),
        "id_kinds": ID_KINDS,
    }


def build_taxonomy(base_dir: Path, ontology: dict) -> dict:
    """Read all step5 catalogs and produce the taxonomy mappings."""
    valid_node_types = {n['type'] for n in ontology['generic_node_types']}
    valid_categories = {c['category'] for c in ontology['categories']}

    mappings = []

    catalog_files = sorted(
        f for f in base_dir.rglob('step5_resource_catalog_inventory_enrich.json')
    )

    for cat_path in catalog_files:
        try:
            doc = json.load(open(cat_path))
        except Exception:
            continue

        services_block = doc.get('services', {})
        for svc_name, svc_data in services_block.items():
            resources = svc_data.get('resources', {})
            for rtype, rdata in sorted(resources.items()):
                category, node_type, confidence, notes = _classify(svc_name, rtype)

                # Validate against ontology (safety net)
                if node_type not in valid_node_types:
                    node_type = 'other.unknown'
                    confidence = min(confidence, 0.50)
                if category not in valid_categories:
                    category = 'other'

                # Identifier kind
                id_kind = _id_kind_from_catalog(rdata)

                # Special override: serviceAccounts → email id_kind
                if 'serviceaccount' in rtype.lower() and 'iam' in svc_name.lower():
                    id_kind = 'email'

                # Dataset names — from inventory op keys
                inv_ops    = rdata.get('inventory', {}).get('ops', [])
                enrich_ops = rdata.get('inventory_enrich', {}).get('ops', [])

                inv_datasets    = [op['op'] for op in inv_ops if op.get('op')]
                enrich_datasets = [op['op'] for op in enrich_ops if op.get('op')]

                if not inv_datasets:
                    inv_datasets = [f'gcp.{svc_name}.{rtype}.inventory']
                    if not notes:
                        notes = 'inferred_dataset_name'
                    else:
                        notes += '; inferred_dataset_name'

                if not enrich_datasets:
                    enrich_datasets = [f'gcp.{svc_name}.{rtype}.enrich']

                mappings.append({
                    "provider":               "gcp",
                    "service":                svc_name,
                    "resource_type":          rtype,
                    "category":               category,
                    "generic_node_type":      node_type,
                    "default_identifier_kind": id_kind,
                    "inventory": {
                        "datasets":        sorted(inv_datasets),
                        "enrich_datasets": sorted(enrich_datasets),
                    },
                    "confidence": confidence,
                    "notes":      notes,
                })

    # Sort: service → resource_type
    mappings.sort(key=lambda m: (m['service'], m['resource_type']))

    return {
        "version": "1.0",
        "generated_at": _now_iso(),
        "mappings": mappings,
    }


# ─────────────────────────────────────────────────────────────────────────────
# SUMMARY PRINTER
# ─────────────────────────────────────────────────────────────────────────────

def _print_summary(ontology: dict, taxonomy: dict):
    mappings   = taxonomy['mappings']
    total      = len(mappings)
    low_conf   = [m for m in mappings if m['confidence'] < 0.6]
    categories = {}
    for m in mappings:
        categories[m['category']] = categories.get(m['category'], 0) + 1

    print('=' * 70)
    print('GCP GRAPH ONTOLOGY + TAXONOMY BUILD SUMMARY')
    print('=' * 70)
    print(f'  Generic node types : {len(ontology["generic_node_types"])}')
    print(f'  Edge types         : {len(ontology["edge_types"])}')
    print(f'  Categories         : {len(ontology["categories"])}')
    print(f'  Total mappings     : {total}')
    print()
    print('  Mappings by category:')
    for cat, cnt in sorted(categories.items(), key=lambda x: -x[1]):
        print(f'    {cat:<20} {cnt:4d}')
    print()
    print(f'  Low-confidence mappings (< 0.6): {len(low_conf)}')
    if low_conf:
        print('  Top low-confidence:')
        for m in sorted(low_conf, key=lambda x: x['confidence'])[:15]:
            print(f'    [{m["confidence"]:.2f}]  {m["service"]}.{m["resource_type"]}'
                  f'  →  {m["generic_node_type"]}  | {m["notes"]}')
    print('=' * 70)


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description='Build GCP Graph Ontology + Resource Taxonomy'
    )
    parser.add_argument('--base', type=Path, default=BASE_DIR,
                        help=f'Base GCP data directory (default: {BASE_DIR})')
    args = parser.parse_args()

    base = args.base

    print('Building GCP graph ontology...')
    ontology = build_ontology()
    ont_path = base / 'gcp_graph_ontology.json'
    with open(ont_path, 'w') as f:
        json.dump(ontology, f, indent=2)
    print(f'  Written: {ont_path}')

    print('Building GCP resource taxonomy...')
    taxonomy = build_taxonomy(base, ontology)
    tax_path = base / 'gcp_resource_taxonomy.json'
    with open(tax_path, 'w') as f:
        json.dump(taxonomy, f, indent=2)
    print(f'  Written: {tax_path}')

    _print_summary(ontology, taxonomy)


if __name__ == '__main__':
    main()
