-- =============================================================================
-- AI Security Rules — 30 rules across 6 categories
-- =============================================================================

-- Category: model_security (5 rules)
INSERT INTO ai_security_rules (rule_id, title, description, severity, category, subcategory, condition, condition_type, frameworks, mitre_techniques, remediation) VALUES
('AI-MOD-001', 'ML model artifact not encrypted at rest', 'Model artifacts stored in S3 or equivalent without server-side encryption', 'high', 'model_security', 'encryption', '{"field": "artifact_encrypted", "op": "eq", "value": false}', 'field_check', '{NIST_AI_RMF,ISO_42001}', '{T1565.002}', 'Enable SSE-KMS encryption on model artifact bucket'),
('AI-MOD-002', 'Model missing version control', 'ML model lacks versioning, preventing rollback from poisoned models', 'medium', 'model_security', 'versioning', '{"field": "artifact_versioned", "op": "eq", "value": false}', 'field_check', '{NIST_AI_RMF}', '{T1565.002}', 'Enable S3 versioning on model artifact bucket and use SageMaker Model Registry'),
('AI-MOD-003', 'No model card published', 'Model lacks a model card documenting intended use, limitations, and ethical considerations', 'medium', 'model_security', 'governance', '{"field": "has_model_card", "op": "eq", "value": false}', 'field_check', '{AI_ACT,NIST_AI_RMF,ISO_42001}', '{}', 'Create and publish a model card describing model purpose, performance metrics, and limitations'),
('AI-MOD-004', 'Training data from untrusted source', 'Training data source lacks encryption or access control', 'critical', 'model_security', 'training_data', '{"field": "training_data_encrypted", "op": "eq", "value": false}', 'field_check', '{NIST_AI_RMF,AI_ACT}', '{T1195.003}', 'Encrypt training data at rest and restrict access via IAM policies'),
('AI-MOD-005', 'Training pipeline not VPC isolated', 'Training job runs outside VPC, exposing data to public network', 'high', 'model_security', 'network', '{"field": "training_vpc_isolated", "op": "eq", "value": false}', 'field_check', '{NIST_AI_RMF,SOC2}', '{T1190}', 'Configure training jobs to run within VPC with private subnets');

-- Category: endpoint_security (5 rules)
INSERT INTO ai_security_rules (rule_id, title, description, severity, category, subcategory, condition, condition_type, frameworks, mitre_techniques, remediation) VALUES
('AI-EP-001', 'ML endpoint publicly accessible without authentication', 'Inference endpoint exposed to internet without IAM or API key auth', 'critical', 'endpoint_security', 'access', '{"all": [{"field": "is_public_endpoint", "op": "eq", "value": true}, {"field": "auth_type", "op": "in", "value": ["none", null]}]}', 'composite', '{AI_ACT,NIST_AI_RMF,SOC2}', '{T1190,T1059}', 'Restrict endpoint to VPC or configure IAM/API key authentication'),
('AI-EP-002', 'ML endpoint not VPC isolated', 'Inference endpoint accessible from public internet', 'high', 'endpoint_security', 'network', '{"field": "is_vpc_isolated", "op": "eq", "value": false}', 'field_check', '{NIST_AI_RMF,SOC2}', '{T1190}', 'Deploy endpoint in VPC with private subnets and use VPC endpoints'),
('AI-EP-003', 'Endpoint encryption in transit disabled', 'ML endpoint does not enforce TLS for inference requests', 'high', 'endpoint_security', 'encryption', '{"field": "encryption_in_transit", "op": "eq", "value": false}', 'field_check', '{NIST_AI_RMF,GDPR}', '{T1557}', 'Enable TLS 1.2+ for all endpoint communications'),
('AI-EP-004', 'No data capture enabled for endpoint', 'Inference endpoint lacks data capture for monitoring model drift and abuse', 'medium', 'endpoint_security', 'monitoring', '{"field": "has_data_capture", "op": "eq", "value": false}', 'field_check', '{NIST_AI_RMF,AI_ACT}', '{}', 'Enable SageMaker Data Capture to log inference requests and responses'),
('AI-EP-005', 'No rate limiting on ML endpoint', 'Inference endpoint has no rate limiting, vulnerable to abuse and denial-of-service', 'medium', 'endpoint_security', 'rate_limit', '{"field": "rate_limit_configured", "op": "eq", "value": false}', 'field_check', '{NIST_AI_RMF,SOC2}', '{T1499}', 'Configure API Gateway throttling or endpoint auto-scaling limits');

-- Category: prompt_security (5 rules — LLM specific)
INSERT INTO ai_security_rules (rule_id, title, description, severity, category, subcategory, condition, condition_type, frameworks, mitre_techniques, remediation) VALUES
('AI-PS-001', 'LLM endpoint missing guardrails', 'Generative AI endpoint has no guardrails configured for content filtering', 'critical', 'prompt_security', 'guardrails', '{"all": [{"field": "model_type", "op": "in", "value": ["llm", "generative"]}, {"field": "has_guardrails", "op": "eq", "value": false}]}', 'composite', '{AI_ACT,NIST_AI_RMF}', '{T1059}', 'Enable Bedrock Guardrails or implement custom input/output filters'),
('AI-PS-002', 'No input validation on LLM endpoint', 'LLM endpoint accepts raw input without validation, vulnerable to prompt injection', 'critical', 'prompt_security', 'input_validation', '{"all": [{"field": "model_type", "op": "in", "value": ["llm", "generative"]}, {"field": "has_input_validation", "op": "eq", "value": false}]}', 'composite', '{AI_ACT,NIST_AI_RMF}', '{T1059}', 'Implement input sanitization and prompt injection detection'),
('AI-PS-003', 'No output filtering on generative model', 'Model output is not filtered for PII, harmful content, or hallucinations', 'high', 'prompt_security', 'output_filter', '{"all": [{"field": "model_type", "op": "in", "value": ["llm", "generative"]}, {"field": "has_output_filtering", "op": "eq", "value": false}]}', 'composite', '{AI_ACT,GDPR}', '{}', 'Enable output content filtering to block PII leakage and harmful content'),
('AI-PS-004', 'No content filter on generative model', 'Bedrock or equivalent content filter not enabled', 'high', 'prompt_security', 'content_filter', '{"all": [{"field": "model_type", "op": "in", "value": ["llm", "generative"]}, {"field": "has_content_filter", "op": "eq", "value": false}]}', 'composite', '{AI_ACT}', '{}', 'Enable content filtering (Bedrock Content Filter or custom filter)'),
('AI-PS-005', 'Excessive token limit on LLM', 'Token limit exceeds 8192, increasing cost and exfiltration risk', 'low', 'prompt_security', 'token_limit', '{"field": "max_token_limit", "op": "gt", "value": 8192}', 'threshold', '{NIST_AI_RMF}', '{T1530}', 'Set reasonable max token limit based on use case (typically 2048-4096)');

-- Category: data_pipeline (5 rules)
INSERT INTO ai_security_rules (rule_id, title, description, severity, category, subcategory, condition, condition_type, frameworks, mitre_techniques, remediation) VALUES
('AI-DP-001', 'ML data pipeline lacks encryption', 'Data flowing between training/inference stages is not encrypted', 'high', 'data_pipeline', 'encryption', '{"any": [{"field": "encryption_at_rest", "op": "eq", "value": false}, {"field": "encryption_in_transit", "op": "eq", "value": false}]}', 'composite', '{NIST_AI_RMF,GDPR}', '{T1557}', 'Enable encryption at rest (KMS) and in transit (TLS) for all ML data paths'),
('AI-DP-002', 'SageMaker notebook instance not in VPC', 'Notebook instance runs outside VPC, exposing data and credentials', 'high', 'data_pipeline', 'network', '{"all": [{"field": "resource_type", "op": "eq", "value": "sagemaker_notebook"}, {"field": "is_vpc_isolated", "op": "eq", "value": false}]}', 'composite', '{NIST_AI_RMF,SOC2}', '{T1190}', 'Deploy notebook instances in VPC private subnets with NAT gateway'),
('AI-DP-003', 'Data capture not enabled on pipeline', 'No audit trail for data flowing through ML pipeline', 'medium', 'data_pipeline', 'logging', '{"field": "has_data_capture", "op": "eq", "value": false}', 'field_check', '{AI_ACT,NIST_AI_RMF}', '{}', 'Enable data capture and CloudWatch logging for all pipeline stages'),
('AI-DP-004', 'Feature store lacks access control', 'SageMaker Feature Store or equivalent accessible without fine-grained IAM', 'medium', 'data_pipeline', 'access_control', '{"field": "auth_type", "op": "in", "value": ["none", null]}', 'field_check', '{NIST_AI_RMF,SOC2}', '{T1078}', 'Implement resource-based IAM policies for Feature Store access'),
('AI-DP-005', 'Network isolation disabled for processing', 'Processing job allows internet access, risking data exfiltration', 'high', 'data_pipeline', 'network', '{"field": "network_isolation", "op": "eq", "value": false}', 'field_check', '{NIST_AI_RMF}', '{T1048}', 'Enable network isolation for SageMaker Processing jobs');

-- Category: ai_governance (5 rules)
INSERT INTO ai_security_rules (rule_id, title, description, severity, category, subcategory, condition, condition_type, frameworks, mitre_techniques, remediation) VALUES
('AI-GOV-001', 'No model monitoring configured', 'ML model lacks monitoring for drift, bias, or performance degradation', 'high', 'ai_governance', 'monitoring', '{"field": "has_monitoring", "op": "eq", "value": false}', 'field_check', '{AI_ACT,NIST_AI_RMF,ISO_42001}', '{}', 'Enable SageMaker Model Monitor or equivalent for data quality, model quality, and bias detection'),
('AI-GOV-002', 'Shadow AI detected — unregistered ML endpoint', 'ML inference endpoint found that is not registered in model registry', 'high', 'ai_governance', 'shadow_ai', '{"all": [{"field": "deployment_type", "op": "eq", "value": "realtime"}, {"field": "has_model_card", "op": "eq", "value": false}, {"field": "has_monitoring", "op": "eq", "value": false}]}', 'composite', '{AI_ACT,ISO_42001}', '{T1059}', 'Register all ML models in SageMaker Model Registry with version tracking and model cards'),
('AI-GOV-003', 'ML resource missing required tags', 'AI/ML resource lacks mandatory tags for cost allocation and governance', 'low', 'ai_governance', 'tagging', '{"field": "tags", "op": "missing_keys", "value": ["owner", "project", "classification"]}', 'field_check', '{ISO_42001}', '{}', 'Apply mandatory tags: owner, project, classification, data-sensitivity'),
('AI-GOV-004', 'High error rate on ML endpoint', 'Inference endpoint showing >5% error rate in last 24 hours', 'medium', 'ai_governance', 'reliability', '{"field": "error_rate_pct", "op": "gt", "value": 5.0}', 'threshold', '{NIST_AI_RMF}', '{}', 'Investigate and resolve endpoint errors; consider model rollback if error rate persists'),
('AI-GOV-005', 'Anomalous input patterns detected', 'Endpoint received >100 anomalous inputs in 24h, possible adversarial attack', 'high', 'ai_governance', 'anomaly', '{"field": "anomalous_inputs_24h", "op": "gt", "value": 100}', 'threshold', '{NIST_AI_RMF,AI_ACT}', '{T1059,T1565}', 'Investigate input anomalies for adversarial patterns; enable input validation and rate limiting');

-- Category: access_control (5 rules)
INSERT INTO ai_security_rules (rule_id, title, description, severity, category, subcategory, condition, condition_type, frameworks, mitre_techniques, remediation) VALUES
('AI-AC-001', 'Overly permissive IAM role on ML service', 'ML resource uses IAM role with admin or wildcard permissions', 'critical', 'access_control', 'iam', '{"field": "iam_role_arn", "op": "contains", "value": "Admin"}', 'field_check', '{NIST_AI_RMF,SOC2}', '{T1078}', 'Apply least-privilege IAM policies scoped to required ML actions only'),
('AI-AC-002', 'ML endpoint authentication using API key only', 'API key auth is weaker than IAM SigV4; vulnerable to key leakage', 'medium', 'access_control', 'auth', '{"field": "auth_type", "op": "eq", "value": "api_key"}', 'field_check', '{NIST_AI_RMF,SOC2}', '{T1078}', 'Migrate to IAM-based authentication (SigV4) for inference endpoints'),
('AI-AC-003', 'SageMaker notebook root access enabled', 'Notebook instance allows root access, increasing attack surface', 'high', 'access_control', 'root_access', '{"all": [{"field": "resource_type", "op": "eq", "value": "sagemaker_notebook"}, {"field": "auth_type", "op": "ne", "value": "iam"}]}', 'composite', '{NIST_AI_RMF,SOC2}', '{T1078.003}', 'Disable root access on SageMaker notebook instances'),
('AI-AC-004', 'Cross-account access to ML artifacts', 'Model artifacts accessible from external AWS accounts', 'high', 'access_control', 'cross_account', '{"field": "is_public_endpoint", "op": "eq", "value": true}', 'field_check', '{NIST_AI_RMF}', '{T1078}', 'Restrict S3 bucket policy to same-account principals; use VPC endpoints'),
('AI-AC-005', 'No encryption at rest on ML resource', 'ML resource (model, data, notebook) not encrypted at rest', 'high', 'access_control', 'encryption', '{"field": "encryption_at_rest", "op": "eq", "value": false}', 'field_check', '{NIST_AI_RMF,GDPR,SOC2}', '{T1530}', 'Enable KMS encryption for all ML resources');
