-- =============================================================================
-- DataSec Enhanced Rules — 35 rules across 7 categories
-- =============================================================================

-- Category: dlp (5 rules — Data Loss Prevention)
INSERT INTO datasec_enhanced_rules (rule_id, title, description, severity, category, subcategory, condition, condition_type, frameworks, remediation) VALUES
('DSE-DLP-001', 'PII data in unencrypted data store', 'Data store containing PII is not encrypted at rest', 'critical', 'dlp', 'pii_exposure', '{"all": [{"field": "detected_pii_types", "op": "not_empty"}, {"field": "encryption_at_rest", "op": "eq", "value": false}]}', 'composite', '{GDPR,CCPA,LGPD,PIPEDA}', 'Enable encryption at rest using customer-managed KMS key'),
('DSE-DLP-002', 'PHI data in publicly accessible store', 'Data store with PHI is publicly accessible', 'critical', 'dlp', 'phi_exposure', '{"all": [{"field": "detected_phi_types", "op": "not_empty"}, {"field": "is_public", "op": "eq", "value": true}]}', 'composite', '{HIPAA,GDPR}', 'Remove public access and enable private endpoint access only'),
('DSE-DLP-003', 'PCI data without CMK encryption', 'Payment card data encrypted with AWS-managed key instead of CMK', 'high', 'dlp', 'pci_exposure', '{"all": [{"field": "detected_pci_types", "op": "not_empty"}, {"field": "kms_key_type", "op": "ne", "value": "customer_managed"}]}', 'composite', '{PCI_DSS}', 'Encrypt PCI data with customer-managed KMS key for key rotation control'),
('DSE-DLP-004', 'Sensitive data with excessive cross-account access', 'Restricted/confidential data accessible from other AWS accounts', 'high', 'dlp', 'cross_account', '{"all": [{"field": "data_classification", "op": "in", "value": ["restricted", "confidential"]}, {"field": "cross_account_access", "op": "eq", "value": true}]}', 'composite', '{GDPR,SOC2}', 'Remove cross-account access policies or use VPC endpoints with conditions'),
('DSE-DLP-005', 'High data egress from sensitive store', 'Restricted data store has >1GB egress in 24h', 'high', 'dlp', 'exfiltration', '{"all": [{"field": "data_classification", "op": "in", "value": ["restricted", "confidential"]}, {"field": "data_egress_bytes_24h", "op": "gt", "value": 1073741824}]}', 'composite', '{SOC2,GDPR}', 'Investigate data egress; enable VPC flow logs and S3 access logging');

-- Category: encryption_posture (5 rules)
INSERT INTO datasec_enhanced_rules (rule_id, title, description, severity, category, subcategory, condition, condition_type, frameworks, remediation) VALUES
('DSE-ENC-001', 'Data store not encrypted at rest', 'Storage resource lacks server-side encryption', 'high', 'encryption_posture', 'at_rest', '{"field": "encryption_at_rest", "op": "eq", "value": false}', 'field_check', '{GDPR,HIPAA,PCI_DSS,SOC2}', 'Enable SSE with KMS or AES-256 encryption'),
('DSE-ENC-002', 'Encryption using AWS-managed key (no rotation control)', 'Data store uses AWS-managed key; customer cannot control rotation', 'medium', 'encryption_posture', 'key_mgmt', '{"field": "kms_key_type", "op": "eq", "value": "aws_managed"}', 'field_check', '{PCI_DSS,NIST}', 'Switch to customer-managed KMS key with annual rotation'),
('DSE-ENC-003', 'KMS key rotation not enabled', 'Customer-managed key lacks automatic annual rotation', 'medium', 'encryption_posture', 'rotation', '{"all": [{"field": "kms_key_type", "op": "eq", "value": "customer_managed"}, {"field": "kms_key_rotation", "op": "eq", "value": false}]}', 'composite', '{PCI_DSS,NIST}', 'Enable automatic annual key rotation on CMK'),
('DSE-ENC-004', 'TLS version below 1.2', 'Data store allows connections with TLS < 1.2', 'high', 'encryption_posture', 'in_transit', '{"field": "tls_version", "op": "in", "value": ["TLS1.0", "TLS1.1", "SSLv3", null]}', 'field_check', '{PCI_DSS,NIST,GDPR}', 'Enforce minimum TLS 1.2 for all connections'),
('DSE-ENC-005', 'Encryption in transit not enforced', 'Data store does not require SSL/TLS for connections', 'high', 'encryption_posture', 'in_transit', '{"field": "encryption_in_transit", "op": "eq", "value": false}', 'field_check', '{GDPR,HIPAA,PCI_DSS}', 'Enable and enforce SSL/TLS for all data connections');

-- Category: data_lineage (5 rules)
INSERT INTO datasec_enhanced_rules (rule_id, title, description, severity, category, subcategory, condition, condition_type, frameworks, remediation) VALUES
('DSE-LIN-001', 'Cross-border data transfer without DPA', 'Data transferred across borders without Data Processing Agreement', 'critical', 'data_lineage', 'cross_border', '{"all": [{"field": "cross_region_transfer", "op": "eq", "value": true}, {"field": "has_dpa", "op": "eq", "value": false}]}', 'composite', '{GDPR,LGPD,PIPEDA}', 'Establish Data Processing Agreements for all cross-border transfers'),
('DSE-LIN-002', 'Cross-cloud data transfer detected', 'Data flowing between different cloud providers without controls', 'high', 'data_lineage', 'cross_cloud', '{"field": "cross_cloud_transfer", "op": "eq", "value": true}', 'field_check', '{GDPR,SOC2}', 'Document and secure cross-cloud data flows with encryption and audit logging'),
('DSE-LIN-003', 'Sensitive data replicated to non-compliant region', 'Restricted data replicated to region without regulatory compliance', 'critical', 'data_lineage', 'residency', '{"all": [{"field": "data_classification", "op": "in", "value": ["restricted"]}, {"field": "data_residency_compliant", "op": "eq", "value": false}]}', 'composite', '{GDPR,LGPD}', 'Remove replication to non-compliant regions; use region-restricted bucket policies'),
('DSE-LIN-004', 'No data lineage tracking for PII store', 'PII-containing store has no documented data sources or destinations', 'medium', 'data_lineage', 'tracking', '{"all": [{"field": "detected_pii_types", "op": "not_empty"}, {"field": "data_sources", "op": "empty"}, {"field": "data_destinations", "op": "empty"}]}', 'composite', '{GDPR,CCPA}', 'Map and document all data flows for PII-containing stores'),
('DSE-LIN-005', 'Data replication without encryption in transit', 'Cross-region replication not using TLS', 'high', 'data_lineage', 'replication', '{"all": [{"field": "replication_enabled", "op": "eq", "value": true}, {"field": "encryption_in_transit", "op": "eq", "value": false}]}', 'composite', '{GDPR,PCI_DSS}', 'Enable TLS for all replication traffic');

-- Category: data_minimization (5 rules)
INSERT INTO datasec_enhanced_rules (rule_id, title, description, severity, category, subcategory, condition, condition_type, frameworks, remediation) VALUES
('DSE-MIN-001', 'Stale data store not accessed in 90+ days', 'Data store has not been accessed in over 90 days', 'medium', 'data_minimization', 'stale_data', '{"field": "last_accessed_days_ago", "op": "gt", "value": 90}', 'threshold', '{GDPR,CCPA}', 'Review and archive or delete stale data per retention policy'),
('DSE-MIN-002', 'No lifecycle policy on data store', 'Data store lacks lifecycle/retention policy for automated cleanup', 'medium', 'data_minimization', 'lifecycle', '{"field": "lifecycle_policy_exists", "op": "eq", "value": false}', 'field_check', '{GDPR,CCPA,LGPD}', 'Implement lifecycle policy with transition to Glacier and expiration rules'),
('DSE-MIN-003', 'No retention policy defined', 'Data store has no defined retention period', 'medium', 'data_minimization', 'retention', '{"field": "retention_days", "op": "eq", "value": null}', 'field_check', '{GDPR,HIPAA,PCI_DSS}', 'Define retention period based on regulatory requirements and business need'),
('DSE-MIN-004', 'Sensitive data without versioning cleanup', 'Versioned store with sensitive data has no lifecycle for old versions', 'low', 'data_minimization', 'versioning', '{"all": [{"field": "versioning_enabled", "op": "eq", "value": true}, {"field": "lifecycle_policy_exists", "op": "eq", "value": false}, {"field": "data_classification", "op": "in", "value": ["restricted", "confidential"]}]}', 'composite', '{GDPR}', 'Add lifecycle rule to expire non-current versions after retention period'),
('DSE-MIN-005', 'Retention period exceeds regulatory maximum', 'Data retained longer than necessary per applicable regulation', 'medium', 'data_minimization', 'over_retention', '{"field": "retention_compliant", "op": "eq", "value": false}', 'field_check', '{GDPR,CCPA,LGPD}', 'Reduce retention period to align with regulatory requirements');

-- Category: classification (5 rules)
INSERT INTO datasec_enhanced_rules (rule_id, title, description, severity, category, subcategory, condition, condition_type, frameworks, remediation) VALUES
('DSE-CLS-001', 'Data store not classified', 'No data classification assigned to data store', 'high', 'classification', 'unclassified', '{"field": "data_classification", "op": "in", "value": [null, ""]}', 'field_check', '{GDPR,SOC2,ISO_27001}', 'Run data classification scan and assign appropriate classification level'),
('DSE-CLS-002', 'Low confidence classification on sensitive data', 'ML classification confidence below 70% for potentially sensitive data', 'medium', 'classification', 'confidence', '{"all": [{"field": "sample_matched_count", "op": "gt", "value": 0}, {"field": "classification_confidence", "op": "lt", "value": 70}]}', 'composite', '{GDPR}', 'Manually verify classification or increase sampling rate'),
('DSE-CLS-003', 'PII detected but not classified as restricted', 'Store contains PII but classification is not restricted/confidential', 'high', 'classification', 'misclassified', '{"all": [{"field": "detected_pii_types", "op": "not_empty"}, {"field": "data_classification", "op": "not_in", "value": ["restricted", "confidential"]}]}', 'composite', '{GDPR,CCPA,HIPAA}', 'Upgrade classification to restricted or confidential'),
('DSE-CLS-004', 'PHI detected in non-HIPAA-tagged store', 'Store contains PHI but lacks HIPAA framework tagging', 'critical', 'classification', 'compliance_gap', '{"all": [{"field": "detected_phi_types", "op": "not_empty"}, {"field": "applicable_regulations", "op": "not_contains", "value": "HIPAA"}]}', 'composite', '{HIPAA}', 'Add HIPAA compliance tagging and apply HIPAA-required controls'),
('DSE-CLS-005', 'Missing required compliance tags', 'Data store lacks mandatory data-classification and compliance tags', 'medium', 'classification', 'tagging', '{"field": "tags", "op": "missing_keys", "value": ["data-classification", "compliance"]}', 'field_check', '{SOC2,ISO_27001}', 'Apply mandatory tags: data-classification, compliance, data-owner');

-- Category: access_audit (5 rules)
INSERT INTO datasec_enhanced_rules (rule_id, title, description, severity, category, subcategory, condition, condition_type, frameworks, remediation) VALUES
('DSE-ACC-001', 'Public access on sensitive data store', 'Restricted or confidential data store is publicly accessible', 'critical', 'access_audit', 'public_access', '{"all": [{"field": "data_classification", "op": "in", "value": ["restricted", "confidential"]}, {"field": "is_public", "op": "eq", "value": true}]}', 'composite', '{GDPR,HIPAA,PCI_DSS,SOC2}', 'Block all public access immediately; enable S3 Block Public Access'),
('DSE-ACC-002', 'Access logging not enabled', 'Data store lacks access logging for audit trail', 'high', 'access_audit', 'logging', '{"field": "access_logging_enabled", "op": "eq", "value": false}', 'field_check', '{GDPR,HIPAA,SOC2,PCI_DSS}', 'Enable server access logging or CloudTrail data events'),
('DSE-ACC-003', 'Unusual access pattern detected', 'More than 50 failed access attempts in 24 hours', 'high', 'access_audit', 'anomaly', '{"field": "failed_access_24h", "op": "gt", "value": 50}', 'threshold', '{SOC2}', 'Investigate failed access attempts; review IAM policies and bucket policies'),
('DSE-ACC-004', 'Bucket policy allows public access', 'S3 bucket policy explicitly grants public read/write', 'critical', 'access_audit', 'policy', '{"field": "bucket_policy_allows_public", "op": "eq", "value": true}', 'field_check', '{GDPR,SOC2,PCI_DSS}', 'Remove public access grants from bucket policy; enable S3 Block Public Access'),
('DSE-ACC-005', 'No backup configured for sensitive data', 'Restricted data store has no backup or point-in-time recovery', 'high', 'access_audit', 'backup', '{"all": [{"field": "data_classification", "op": "in", "value": ["restricted", "confidential"]}, {"field": "backup_enabled", "op": "eq", "value": false}]}', 'composite', '{SOC2,HIPAA}', 'Enable automated backups with appropriate retention period');

-- Category: cross_border (5 rules)
INSERT INTO datasec_enhanced_rules (rule_id, title, description, severity, category, subcategory, condition, condition_type, frameworks, remediation) VALUES
('DSE-XB-001', 'Data residency violation detected', 'Data stored in non-compliant region per regulation', 'critical', 'cross_border', 'residency', '{"field": "data_residency_compliant", "op": "eq", "value": false}', 'field_check', '{GDPR,LGPD,PIPEDA}', 'Migrate data to compliant region; use S3 Object Lock or region restrictions'),
('DSE-XB-002', 'EU data stored outside EEA without adequacy', 'GDPR-subject data stored outside European Economic Area', 'critical', 'cross_border', 'gdpr_transfer', '{"all": [{"field": "applicable_regulations", "op": "contains", "value": "GDPR"}, {"field": "data_residency_compliant", "op": "eq", "value": false}]}', 'composite', '{GDPR}', 'Transfer data to EEA region or establish Standard Contractual Clauses (SCCs)'),
('DSE-XB-003', 'Cross-region replication to non-approved region', 'Data replicated to region not in approved residency list', 'high', 'cross_border', 'replication', '{"all": [{"field": "replication_enabled", "op": "eq", "value": true}, {"field": "data_residency_compliant", "op": "eq", "value": false}]}', 'composite', '{GDPR,LGPD}', 'Remove non-compliant replication rules; restrict to approved regions'),
('DSE-XB-004', 'Brazilian data outside Brazil (LGPD)', 'LGPD-subject data processed outside Brazil without authorization', 'high', 'cross_border', 'lgpd_transfer', '{"all": [{"field": "applicable_regulations", "op": "contains", "value": "LGPD"}, {"field": "cross_region_transfer", "op": "eq", "value": true}]}', 'composite', '{LGPD}', 'Ensure LGPD cross-border transfer requirements are met with documented basis'),
('DSE-XB-005', 'Canadian data processed outside Canada (PIPEDA)', 'PIPEDA-subject data transferred outside Canadian jurisdiction', 'high', 'cross_border', 'pipeda_transfer', '{"all": [{"field": "applicable_regulations", "op": "contains", "value": "PIPEDA"}, {"field": "cross_region_transfer", "op": "eq", "value": true}]}', 'composite', '{PIPEDA}', 'Ensure PIPEDA-compliant cross-border transfer agreements are in place');
