# Generated by Django 5.2.10 on 2026-01-16 19:07

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProvider',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Onboarding Provider',
                'verbose_name_plural': 'Onboarding Providers',
                'db_table': 'onboarding_providers',
            },
        ),
        migrations.CreateModel(
            name='OnboardingAccount',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('onboarding_status', models.CharField(default='pending', max_length=50)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='onboarding_management.onboardingprovider')),
            ],
            options={
                'verbose_name': 'Onboarding Account',
                'verbose_name_plural': 'Onboarding Accounts',
                'db_table': 'onboarding_accounts',
            },
        ),
        migrations.CreateModel(
            name='OnboardingSchedule',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('schedule_type', models.CharField(choices=[('cron', 'Cron'), ('interval', 'Interval'), ('one_time', 'One Time')], max_length=20)),
                ('cron_expression', models.CharField(blank=True, max_length=255, null=True)),
                ('interval_seconds', models.IntegerField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('services', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('exclude_services', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('status', models.CharField(default='active', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('notify_on_success', models.BooleanField(default=False)),
                ('notify_on_failure', models.BooleanField(default=True)),
                ('notification_channels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='onboarding_management.onboardingaccount')),
            ],
            options={
                'verbose_name': 'Onboarding Schedule',
                'verbose_name_plural': 'Onboarding Schedules',
                'db_table': 'onboarding_schedules',
            },
        ),
        migrations.CreateModel(
            name='OnboardingExecution',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=50)),
                ('scan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total_checks', models.IntegerField(blank=True, null=True)),
                ('passed_checks', models.IntegerField(blank=True, null=True)),
                ('failed_checks', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('triggered_by', models.CharField(default='scheduler', max_length=50)),
                ('execution_time_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='onboarding_management.onboardingaccount')),
                ('schedule', models.ForeignKey(db_column='schedule_id', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='onboarding_management.onboardingschedule')),
            ],
            options={
                'verbose_name': 'Onboarding Execution',
                'verbose_name_plural': 'Onboarding Executions',
                'db_table': 'onboarding_executions',
            },
        ),
        migrations.CreateModel(
            name='OnboardingTenant',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Onboarding Tenant',
                'verbose_name_plural': 'Onboarding Tenants',
                'db_table': 'onboarding_tenants',
                'indexes': [models.Index(fields=['tenant_name'], name='onboarding__tenant__528884_idx'), models.Index(fields=['status'], name='onboarding__status_5efad5_idx')],
            },
        ),
        migrations.AddField(
            model_name='onboardingschedule',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='onboarding_management.onboardingtenant'),
        ),
        migrations.AddField(
            model_name='onboardingprovider',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='onboarding_management.onboardingtenant'),
        ),
        migrations.AddField(
            model_name='onboardingaccount',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='onboarding_management.onboardingtenant'),
        ),
        migrations.CreateModel(
            name='OnboardingScanResult',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_scan_results', to='onboarding_management.onboardingaccount')),
                ('execution', models.ForeignKey(blank=True, db_column='execution_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_scan_results', to='onboarding_management.onboardingexecution')),
            ],
            options={
                'verbose_name': 'Onboarding Scan Result',
                'verbose_name_plural': 'Onboarding Scan Results',
                'db_table': 'onboarding_scan_results',
                'indexes': [models.Index(fields=['account', 'started_at'], name='onboarding__account_035d8b_idx'), models.Index(fields=['status', 'started_at'], name='onboarding__status_6a6575_idx'), models.Index(fields=['execution'], name='onboarding__executi_cfcc62_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='onboardingexecution',
            index=models.Index(fields=['schedule', 'started_at'], name='onboarding__schedul_9a0399_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingexecution',
            index=models.Index(fields=['account', 'started_at'], name='onboarding__account_5b31d2_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingexecution',
            index=models.Index(fields=['status'], name='onboarding__status_666675_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingexecution',
            index=models.Index(fields=['scan_id'], name='onboarding__scan_id_bc4969_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingschedule',
            index=models.Index(fields=['tenant', 'id'], name='onboarding__tenant__810fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingschedule',
            index=models.Index(fields=['account', 'id'], name='onboarding__account_07eccd_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingschedule',
            index=models.Index(fields=['enabled', 'next_run_at'], name='onboarding__enabled_5c5caf_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingschedule',
            index=models.Index(fields=['status'], name='onboarding__status_38ee9c_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingprovider',
            index=models.Index(fields=['tenant', 'provider_type'], name='onboarding__tenant__2f411f_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingprovider',
            index=models.Index(fields=['provider_type'], name='onboarding__provide_79aebf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onboardingprovider',
            unique_together={('tenant', 'provider_type')},
        ),
        migrations.AddIndex(
            model_name='onboardingaccount',
            index=models.Index(fields=['tenant', 'status'], name='onboarding__tenant__d3764a_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingaccount',
            index=models.Index(fields=['provider', 'status'], name='onboarding__provide_a91629_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingaccount',
            index=models.Index(fields=['account_number'], name='onboarding__account_99ca51_idx'),
        ),
    ]
