version: '1.0'
rule_id: alicloud.ecs.security_group.kafka_port_public_ingress_blocked
for_each: alicloud.ecs.DescribeAutoProvisioningGroupInstances
severity: HIGH
conditions:
  all:
  - var: item.security_group_rules
    op: exists
  - var: item.security_group_rules[].SourceCidrIp
    op: not_contains
    value: 0.0.0.0/0
  - var: item.security_group_rules[].PortRange
    op: not_contains
    value: 9092/9092
