version: '1.0'
rule_id: alicloud.hbr.backup_recovery_job.monitoring_alert_rules_for_job_failures_configured
for_each: alicloud.hbr.backup_recovery_job
severity: MEDIUM
conditions:
  var: item.status
  op: equals
  value: ACTIVE
