version: '1.0'
rule_id: gcp.monitoring.alert_policy.monitoring_alerts_for_rpo_rto_breach_configured
for_each: gcp.monitoring.projects.alertPolicies.list
severity: MEDIUM
conditions:
  var: item
  op: not_empty
