version: '1.0'
rule_id: aws.guardduty.finding.guardduty_finding_export_destinations_private_configured
for_each: aws.guardduty.get_detector
severity: HIGH
conditions:
  var: item.FindingPublishingFrequency
  op: exists
