version: '1.0'
rule_id: aws.guardduty.custom_identifier.guardduty_source_trusted_configured
for_each: aws.guardduty.get_detector
severity: MEDIUM
conditions:
  var: item.Status
  op: equals
  value: ENABLED
