version: '1.0'
rule_id: aws.emr.cluster.master_nodes_no_public_ip_configured
for_each: aws.emr.describe_cluster
severity: HIGH
conditions:
  var: item.Cluster.Ec2InstanceAttributes.EmrManagedMasterSecurityGroup
  op: exists
