version: '1.0'
rule_id: oci.data_flow.application.cluster_admin_access_least_privilege_required
for_each: oci.data_flow.list_runs
severity: CRITICAL
conditions:
  all:
  - var: item.freeform_tags.Environment
    op: exists
  - var: item.defined_tags.Environment
    op: exists
