version: '1.0'
provider: k8s
service: policy
services:
  client: policy
  module: kubernetes.client
discovery:
- discovery_id: k8s.policy.list_network_policy_for_all_namespaces
  calls:
  - action: list_network_policy_for_all_namespaces
    save_as: response
    on_error: continue
  emit:
    as: item
    items_for: '{{ response }}'
- discovery_id: k8s.policy.list_pod_disruption_budget_for_all_namespaces
  calls:
  - action: list_pod_disruption_budget_for_all_namespaces
    save_as: response
    on_error: continue
  emit:
    as: item
    items_for: '{{ response }}'
