rule_id: alicloud.actiontrail.multi_region_logging_enabled.configured
title: 'ALICLOUD ACTIONTRAIL Multi Region Logging Enabled: Configured'
scope: actiontrail.multi_region_logging_enabled
domain: logging_monitoring_and_alerting
subcategory: audit_logging
severity: medium
service: actiontrail
resource: multi_region_logging_enabled
requirement: Configured
description: Validates that ALICLOUD actiontrail multi region logging enabled has
  configured configured according to security best practices. Proper configuration
  reduces security risks, prevents unauthorized access, and ensures compliance with
  industry standards and regulations.
rationale: Ensures ALICLOUD actiontrail multi region logging enabled has configured
  properly configured for security compliance. This control is essential for maintaining
  a strong security posture and meeting regulatory requirements.
remediation: Review and remediate the Configured configuration according to ALICLOUD
  security best practices and organisational policy. Refer to the ALICLOUD documentation
  for step-by-step remediation guidance.
references:
- https://www.alibabacloud.com/help/actiontrail
compliance:
- fedramp_moderate_AU_4
- fedramp_moderate_AU_7
- fedramp_moderate_AU_7_1
- fedramp_moderate_AU_9
- fedramp_moderate_AU_9_2
- fedramp_moderate_AU_9_3
- fedramp_moderate_AU_9_4
- nist_800_53_rev5_AC_16_1
- nist_800_53_rev5_AC_16_10
- nist_800_53_rev5_AC_16_2
- nist_800_53_rev5_AC_16_3
- nist_800_53_rev5_AC_16_4
- nist_800_53_rev5_AC_16_5
- nist_800_53_rev5_AC_16_6
- nist_800_53_rev5_AC_16_7
- nist_800_53_rev5_AC_16_8
- nist_800_53_rev5_AC_16_9
- nist_800_53_rev5_AC_16_a
- nist_800_53_rev5_AC_16_b
- nist_800_53_rev5_AC_16_c
- nist_800_53_rev5_AC_16_d
- nist_800_53_rev5_AC_16_e
- nist_800_53_rev5_AC_16_f
- nist_800_53_rev5_AU_16_1
- nist_800_53_rev5_AU_16_2
- nist_800_53_rev5_AU_16_3
- nist_800_53_rev5_AU_4_1
- nist_800_53_rev5_AU_4_2
- nist_800_53_rev5_AU_7_1
- nist_800_53_rev5_AU_7_2
- nist_800_53_rev5_AU_7_a
- nist_800_53_rev5_AU_7_b
- nist_800_53_rev5_AU_9_1
- nist_800_53_rev5_AU_9_2
- nist_800_53_rev5_AU_9_3
- nist_800_53_rev5_AU_9_4
- nist_800_53_rev5_AU_9_5
- nist_800_53_rev5_AU_9_6
- nist_800_53_rev5_AU_9_7
- nist_800_53_rev5_AU_9_a
- nist_800_53_rev5_AU_9_b
- nist_800_53_rev5_PM_21_a
- nist_800_53_rev5_PM_21_b
- nist_800_53_rev5_PM_21_c
source: auto_generated
metadata_source: auto_generated
generated_by: alicloud_rule_generator
