version: '1.0'
rule_id: oci.streaming.stream.streaming_security_video_retention_days_minimum_configured
for_each: oci.streaming.stream.list
severity: LOW
conditions:
  all:
  - var: item.retention_in_hours
    op: gte
    value: '168'
