version: '1.0'
rule_id: k8s.secret.secret.git_repo_url_no_sensitive_credentials_configured
for_each: k8s.secret.list
severity: LOW
conditions:
  all:
  - var: item.data
    op: exists
  - var: item.data[].git_repo_url
    op: exists
  - any:
    - var: item.data[].git_repo_url
      op: not_contains
      value: ://
    - all:
      - var: item.data[].git_repo_url
        op: contains
        value: ://
      - var: item.data[].git_repo_url
        op: not_contains
        value: '@'
