# Discovery YAML — apm_config (OCI)
# Generated: 2026-02-21T04:45:38Z
version: '1.0'
provider: oci
service: apm_config
services:
  client: apm_config
  module: oci.apm_config
discovery:
  # ── get_config [dependent] ──
  - discovery_id: oci.apm_config.get_config
    calls:
      - action: get_config
        save_as: response
        on_error: continue
    emit:
      as: item
      item:
        compartment_id: '{{ response.data.compartment_id }}'
        defined_tags: '{{ response.data.defined_tags }}'
        freeform_tags: '{{ response.data.freeform_tags }}'
        name: '{{ response.data.name }}'
        time_created: '{{ response.data.time_created }}'
        ocid: '{{ response.data.ocid }}'
        status: '{{ response.data.status }}'
    # required_params: ['ConfigId']
  # ── get_match_agents_with_attribute_key [dependent] ──
  - discovery_id: oci.apm_config.get_match_agents_with_attribute_key
    calls:
      - action: get_match_agents_with_attribute_key
        save_as: response
        on_error: continue
    emit:
      as: item
      item:
        compartment_id: '{{ response.data.compartment_id }}'
        defined_tags: '{{ response.data.defined_tags }}'
        freeform_tags: '{{ response.data.freeform_tags }}'
        name: '{{ response.data.name }}'
        time_created: '{{ response.data.time_created }}'
        ocid: '{{ response.data.ocid }}'
        status: '{{ response.data.status }}'
    # required_params: ['MatchAgentsWithAttributeKeyId']
  # ── list_configs [dependent] ──
  - discovery_id: oci.apm_config.list_configs
    calls:
      - action: list_configs
        save_as: response
        on_error: continue
    emit:
      as: item
      items_for: '{{ response.data }}'
      item:
        compartment_id: '{{ item.compartment_id }}'
        defined_tags: '{{ item.defined_tags }}'
        freeform_tags: '{{ item.freeform_tags }}'
        name: '{{ item.name }}'
        time_created: '{{ item.time_created }}'
        ocid: '{{ item.ocid }}'
        status: '{{ item.status }}'
    # required_params: ['compartmentId']
