"""
Orchestration Service — Full CSPM Pipeline
===========================================

Pipeline flow:
  Discovery → Check → Inventory → Threat → (Compliance + IAM + DataSec)

Each engine writes to its own PostgreSQL database. Downstream engines receive
upstream scan IDs as foreign keys so they can read from upstream DBs.

=== SCAN ID ARCHITECTURE ===

Every engine generates its OWN scan ID (UUID) as the primary key in its
*_report table. These are NEVER shared or reused across engines.

  orchestration_id  — UUID, generated HERE by the api_gateway.
                      Ties the full pipeline run together.
                      Stored in shared DB `scan_orchestration` table AND
                      passed to every engine so they store it in their *_report.

  discovery_scan_id — UUID, generated by Discovery engine api_server.
                      FK passed to: Check, Inventory, Threat

  check_scan_id     — UUID, generated by Check engine api_server.
                      FK passed to: Threat, Compliance

  inventory_scan_id — UUID, generated by Inventory engine orchestrator.
                      (no downstream consumers currently)

  threat_scan_id    — UUID, returned by Threat engine.
                      FK passed to: IAM, DataSec

  compliance_scan_id, iam_scan_id, datasec_scan_id — UUIDs from respective engines.
                      Terminal engines, no further downstream.

Data flow (arrows show which scan IDs are passed):

  Discovery ──discovery_scan_id──► Check ──check_scan_id──► Threat ──threat_scan_id──► IAM
       │                              │                         │                      ► DataSec
       │                              └──check_scan_id────────► Compliance
       └──discovery_scan_id──────► Inventory
       └──discovery_scan_id──────► Threat

Each engine's *_report table has:
  - Its own PK: {engine}_scan_id
  - orchestration_id: links back to this pipeline run
  - Upstream FKs: discovery_scan_id, check_scan_id, threat_scan_id (as applicable)

=== END SCAN ID ARCHITECTURE ===
"""
import asyncio
import httpx
import os
import uuid
from typing import Dict, Any, Optional
from datetime import datetime
from pydantic import BaseModel
import logging

logger = logging.getLogger(__name__)


class OrchestrationRequest(BaseModel):
    """Request model for orchestration"""
    customer_id: str
    tenant_id: str
    provider: str = "aws"
    hierarchy_id: Optional[str] = None
    hierarchy_type: str = "account"
    include_services: Optional[list] = None
    include_regions: Optional[list] = None
    credentials: Optional[Dict[str, Any]] = None
    use_database: bool = True


class OrchestrationService:
    """Orchestrates Discovery → Check → Inventory → Threat → (Compliance + IAM + DataSec) pipeline.

    Each engine generates its own UUID scan ID. This orchestrator passes
    upstream scan IDs as foreign keys to downstream engines and records
    ALL per-engine scan IDs in the shared `scan_orchestration` table.
    """

    def __init__(self):
        # Engine URLs from environment or defaults
        self.discoveries_engine_url = os.getenv(
            "DISCOVERIES_ENGINE_URL",
            "http://localhost:8001"
        )
        self.check_engine_url = os.getenv(
            "CHECK_ENGINE_URL",
            "http://localhost:8002"
        )
        self.threat_engine_url = os.getenv(
            "THREAT_ENGINE_URL",
            "http://localhost:8020"
        )
        self.compliance_engine_url = os.getenv(
            "COMPLIANCE_ENGINE_URL",
            "http://localhost:8010"
        )
        self.iam_engine_url = os.getenv(
            "IAM_ENGINE_URL",
            "http://localhost:8003"
        )
        self.datasec_engine_url = os.getenv(
            "DATASEC_ENGINE_URL",
            "http://localhost:8004"
        )
        self.inventory_engine_url = os.getenv(
            "INVENTORY_ENGINE_URL",
            "http://localhost:8022"
        )

    async def run_orchestration(
        self,
        request: OrchestrationRequest
    ) -> Dict[str, Any]:
        """
        Run complete orchestration pipeline.

        Flow:
          1. Discovery  → produces discovery_scan_id
          2. Check      → receives discovery_scan_id (FK), produces check_scan_id
          3. Inventory  → receives discovery_scan_id (FK), produces inventory_scan_id
          4. Threat     → receives discovery_scan_id + check_scan_id (FKs), produces threat_scan_id
          5. Parallel:
             - Compliance → receives check_scan_id (FK), produces compliance_scan_id
             - IAM        → receives threat_scan_id (FK), produces iam_scan_id
             - DataSec    → receives threat_scan_id (FK), produces datasec_scan_id

        All engines also receive orchestration_id to store in their *_report tables.
        """
        # Generate the pipeline-wide orchestration ID (UUID)
        orchestration_id = str(uuid.uuid4())

        results = {
            "orchestration_id": orchestration_id,
            "customer_id": request.customer_id,
            "tenant_id": request.tenant_id,
            "provider": request.provider,
            "hierarchy_id": request.hierarchy_id,
            "started_at": datetime.utcnow().isoformat(),
            "steps": {}
        }

        try:
            # ── Step 1: Discovery ──
            # No upstream FKs — this is the root of the pipeline.
            # Produces: discovery_scan_id
            logger.info(f"[{orchestration_id}] Step 1: Starting discovery scan")
            discovery_result = await self._run_discovery(request, orchestration_id)
            results["steps"]["discovery"] = discovery_result

            if discovery_result.get("status") != "completed":
                results["status"] = "failed"
                results["error"] = "Discovery step failed"
                results["completed_at"] = datetime.utcnow().isoformat()
                return results

            discovery_scan_id = discovery_result.get("discovery_scan_id")
            logger.info(f"[{orchestration_id}] Step 1: Discovery completed — "
                        f"discovery_scan_id={discovery_scan_id}")

            # ── Step 2: Check ──
            # Upstream FK: discovery_scan_id (reads discovery_findings from discoveries DB)
            # Produces: check_scan_id
            logger.info(f"[{orchestration_id}] Step 2: Starting check scan")
            check_result = await self._run_check(
                request=request,
                orchestration_id=orchestration_id,
                discovery_scan_id=discovery_scan_id
            )
            results["steps"]["check"] = check_result

            if check_result.get("status") != "completed":
                logger.warning(f"[{orchestration_id}] Step 2: Check step failed, continuing")

            check_scan_id = check_result.get("check_scan_id")
            logger.info(f"[{orchestration_id}] Step 2: Check completed — "
                        f"check_scan_id={check_scan_id}")

            # ── Step 3: Inventory ──
            # Upstream FK: discovery_scan_id (reads discovery_findings from discoveries DB)
            # Produces: inventory_scan_id (scan_run_id)
            logger.info(f"[{orchestration_id}] Step 3: Starting inventory scan")
            inventory_result = await self._run_inventory(
                request=request,
                orchestration_id=orchestration_id,
                discovery_scan_id=discovery_scan_id
            )
            results["steps"]["inventory"] = inventory_result

            if inventory_result.get("status") != "completed":
                logger.warning(f"[{orchestration_id}] Step 3: Inventory step failed, continuing")

            inventory_scan_id = inventory_result.get("scan_run_id")
            logger.info(f"[{orchestration_id}] Step 3: Inventory completed — "
                        f"inventory_scan_id={inventory_scan_id}")

            # ── Step 4: Threat ──
            # Upstream FKs: discovery_scan_id + check_scan_id
            # Produces: threat_scan_id
            logger.info(f"[{orchestration_id}] Step 4: Starting threat analysis")
            threat_result = await self._run_threat(
                request=request,
                orchestration_id=orchestration_id,
                discovery_scan_id=discovery_scan_id,
                check_scan_id=check_scan_id
            )
            results["steps"]["threat"] = threat_result

            if threat_result.get("status") != "completed":
                logger.warning(f"[{orchestration_id}] Step 4: Threat step failed, continuing")

            threat_scan_id = threat_result.get("threat_scan_id")
            logger.info(f"[{orchestration_id}] Step 4: Threat completed — "
                        f"threat_scan_id={threat_scan_id}")

            # ── Step 5: Parallel — Compliance, IAM, DataSec ──
            # Compliance upstream FK: check_scan_id
            # IAM upstream FK:        threat_scan_id
            # DataSec upstream FK:    threat_scan_id
            logger.info(f"[{orchestration_id}] Step 5: Starting compliance/IAM/data security (parallel)")
            parallel_tasks = [
                self._run_compliance(request, orchestration_id, check_scan_id),
                self._run_iam_security(request, orchestration_id, threat_scan_id),
                self._run_data_security(request, orchestration_id, threat_scan_id)
            ]

            parallel_results = await asyncio.gather(*parallel_tasks, return_exceptions=True)
            compliance_result, iam_result, datasec_result = parallel_results

            results["steps"]["compliance"] = (
                compliance_result if not isinstance(compliance_result, Exception)
                else {"status": "failed", "error": str(compliance_result)}
            )
            results["steps"]["iam_security"] = (
                iam_result if not isinstance(iam_result, Exception)
                else {"status": "failed", "error": str(iam_result)}
            )
            results["steps"]["data_security"] = (
                datasec_result if not isinstance(datasec_result, Exception)
                else {"status": "failed", "error": str(datasec_result)}
            )

            # Extract per-engine scan IDs from parallel results
            compliance_scan_id = (
                compliance_result.get("compliance_scan_id")
                if isinstance(compliance_result, dict) else None
            )
            iam_scan_id = (
                iam_result.get("iam_scan_id")
                if isinstance(iam_result, dict) else None
            )
            datasec_scan_id = (
                datasec_result.get("datasec_scan_id")
                if isinstance(datasec_result, dict) else None
            )

            logger.info(f"[{orchestration_id}] Step 5: Parallel engines completed — "
                        f"compliance={compliance_scan_id}, iam={iam_scan_id}, datasec={datasec_scan_id}")

            # ── Final: Collect all per-engine scan IDs ──
            results["status"] = "completed"
            results["discovery_scan_id"] = discovery_scan_id
            results["check_scan_id"] = check_scan_id
            results["inventory_scan_id"] = inventory_scan_id
            results["threat_scan_id"] = threat_scan_id
            results["compliance_scan_id"] = compliance_scan_id
            results["iam_scan_id"] = iam_scan_id
            results["datasec_scan_id"] = datasec_scan_id
            results["completed_at"] = datetime.utcnow().isoformat()

            logger.info(f"[{orchestration_id}] Orchestration completed successfully")

        except Exception as e:
            logger.error(f"[{orchestration_id}] Orchestration failed: {e}", exc_info=True)
            results["status"] = "failed"
            results["error"] = str(e)
            results["completed_at"] = datetime.utcnow().isoformat()

        return results

    # ──────────────────────────────────────────────────────────────────────
    # Engine runners — each passes orchestration_id + upstream FK scan IDs
    # ──────────────────────────────────────────────────────────────────────

    async def _run_discovery(
        self,
        request: OrchestrationRequest,
        orchestration_id: str
    ) -> Dict[str, Any]:
        """Run discovery scan.

        Upstream FKs: none (root engine)
        Produces: discovery_scan_id
        """
        try:
            async with httpx.AsyncClient(timeout=3600.0) as client:
                discovery_request = {
                    "orchestration_id": orchestration_id,
                    "customer_id": request.customer_id,
                    "tenant_id": request.tenant_id,
                    "provider": request.provider,
                    "hierarchy_id": request.hierarchy_id,
                    "hierarchy_type": request.hierarchy_type,
                    "include_services": request.include_services,
                    "include_regions": request.include_regions,
                    "credentials": request.credentials,
                    "use_database": request.use_database
                }

                response = await client.post(
                    f"{self.discoveries_engine_url}/api/v1/discovery",
                    json=discovery_request
                )
                response.raise_for_status()
                result = response.json()

                # Poll for completion
                discovery_scan_id = result.get("discovery_scan_id")
                if discovery_scan_id:
                    status = await self._poll_discovery_status(client, discovery_scan_id)
                    return {
                        "status": status.get("status", "unknown"),
                        "discovery_scan_id": discovery_scan_id,
                        "message": status.get("message", "Discovery scan completed")
                    }

                return {
                    "status": "failed",
                    "error": "No discovery_scan_id returned"
                }

        except Exception as e:
            logger.error(f"Discovery step failed: {e}", exc_info=True)
            return {
                "status": "failed",
                "error": str(e)
            }

    async def _poll_discovery_status(
        self,
        client: httpx.AsyncClient,
        scan_id: str,
        max_wait: int = 3600
    ) -> Dict[str, Any]:
        """Poll discovery scan status until completion."""
        start_time = datetime.utcnow().timestamp()

        while True:
            elapsed = datetime.utcnow().timestamp() - start_time
            if elapsed > max_wait:
                return {"status": "timeout", "message": "Discovery scan timed out"}

            try:
                response = await client.get(
                    f"{self.discoveries_engine_url}/api/v1/scan/{scan_id}/status"
                )
                response.raise_for_status()
                status_data = response.json()

                status = status_data.get("status")
                if status in ["completed", "failed", "cancelled"]:
                    return status_data

                await asyncio.sleep(10)

            except Exception as e:
                logger.error(f"Error polling discovery status: {e}")
                return {"status": "error", "error": str(e)}

    async def _run_check(
        self,
        request: OrchestrationRequest,
        orchestration_id: str,
        discovery_scan_id: str
    ) -> Dict[str, Any]:
        """Run check scan.

        Upstream FKs: discovery_scan_id (reads discovery_findings)
        Produces: check_scan_id
        """
        try:
            async with httpx.AsyncClient(timeout=3600.0) as client:
                check_request = {
                    "orchestration_id": orchestration_id,
                    # FK — upstream scan ID for reading discovery results
                    "discovery_scan_id": discovery_scan_id,
                    "customer_id": request.customer_id,
                    "tenant_id": request.tenant_id,
                    "provider": request.provider,
                    "hierarchy_id": request.hierarchy_id,
                    "hierarchy_type": request.hierarchy_type,
                    "include_services": request.include_services,
                    "check_source": "default",
                    "use_ndjson": False  # Use database mode
                }

                response = await client.post(
                    f"{self.check_engine_url}/api/v1/check",
                    json=check_request
                )
                response.raise_for_status()
                result = response.json()

                # Poll for completion
                check_scan_id = result.get("check_scan_id")
                if check_scan_id:
                    status = await self._poll_check_status(client, check_scan_id)
                    return {
                        "status": status.get("status", "unknown"),
                        "check_scan_id": check_scan_id,
                        "message": status.get("message", "Check scan completed")
                    }

                return {
                    "status": "failed",
                    "error": "No check_scan_id returned"
                }

        except Exception as e:
            logger.error(f"Check step failed: {e}", exc_info=True)
            return {
                "status": "failed",
                "error": str(e)
            }

    async def _poll_check_status(
        self,
        client: httpx.AsyncClient,
        scan_id: str,
        max_wait: int = 3600
    ) -> Dict[str, Any]:
        """Poll check scan status until completion."""
        start_time = datetime.utcnow().timestamp()

        while True:
            elapsed = datetime.utcnow().timestamp() - start_time
            if elapsed > max_wait:
                return {"status": "timeout", "message": "Check scan timed out"}

            try:
                response = await client.get(
                    f"{self.check_engine_url}/api/v1/scan/{scan_id}/status"
                )
                response.raise_for_status()
                status_data = response.json()

                status = status_data.get("status")
                if status in ["completed", "failed", "cancelled"]:
                    return status_data

                await asyncio.sleep(10)

            except Exception as e:
                logger.error(f"Error polling check status: {e}")
                return {"status": "error", "error": str(e)}

    async def _run_threat(
        self,
        request: OrchestrationRequest,
        orchestration_id: str,
        discovery_scan_id: str,
        check_scan_id: str
    ) -> Dict[str, Any]:
        """Run threat analysis.

        Upstream FKs: discovery_scan_id + check_scan_id
        Produces: threat_scan_id
        """
        try:
            async with httpx.AsyncClient(timeout=3600.0) as client:
                threat_request = {
                    "orchestration_id": orchestration_id,
                    "tenant_id": request.tenant_id,
                    # FKs — upstream scan IDs
                    "discovery_scan_id": discovery_scan_id,
                    "check_scan_id": check_scan_id,
                    "scan_run_id": check_scan_id,  # Threat engine uses this as its input scan ref
                    "cloud": request.provider,
                    "trigger_type": "orchestrated",
                    "accounts": [request.hierarchy_id] if request.hierarchy_id else [],
                    "regions": request.include_regions or [],
                    "services": request.include_services or [],
                    "started_at": datetime.utcnow().isoformat(),
                    "completed_at": None,
                }

                response = await client.post(
                    f"{self.threat_engine_url}/api/v1/threat/generate",
                    json=threat_request
                )
                response.raise_for_status()
                result = response.json()

                # Threat engine returns its own scan ID as scan_run_id or report_id
                threat_scan_id = (
                    result.get("threat_scan_id")
                    or result.get("scan_run_id")
                    or result.get("report_id")
                )

                return {
                    "status": "completed",
                    "threat_scan_id": threat_scan_id,
                    "message": "Threat analysis completed",
                    "total_threats": result.get("threat_summary", {}).get("total_threats", 0)
                }
        except Exception as e:
            logger.error(f"Threat step failed: {e}", exc_info=True)
            return {
                "status": "failed",
                "error": str(e)
            }

    async def _run_compliance(
        self,
        request: OrchestrationRequest,
        orchestration_id: str,
        check_scan_id: str
    ) -> Dict[str, Any]:
        """Run compliance engine.

        Upstream FK: check_scan_id (reads check_findings)
        Produces: compliance_scan_id
        """
        try:
            async with httpx.AsyncClient(timeout=600.0) as client:
                compliance_request = {
                    "orchestration_id": orchestration_id,
                    "tenant_id": request.tenant_id,
                    # FK — upstream check scan ID
                    "scan_id": check_scan_id,
                    "csp": request.provider
                }

                response = await client.post(
                    f"{self.compliance_engine_url}/api/v1/compliance/generate/from-check-db",
                    json=compliance_request
                )
                response.raise_for_status()
                result = response.json()

                return {
                    "status": "completed",
                    "compliance_scan_id": result.get("report_id") or result.get("compliance_scan_id"),
                    "message": "Compliance report generated"
                }

        except Exception as e:
            logger.error(f"Compliance step failed: {e}", exc_info=True)
            return {
                "status": "failed",
                "error": str(e)
            }

    async def _run_iam_security(
        self,
        request: OrchestrationRequest,
        orchestration_id: str,
        threat_scan_id: str
    ) -> Dict[str, Any]:
        """Run IAM security engine.

        Upstream FK: threat_scan_id (reads threat_findings from threat DB)
        Produces: iam_scan_id
        """
        try:
            async with httpx.AsyncClient(timeout=600.0) as client:
                iam_request = {
                    "orchestration_id": orchestration_id,
                    "csp": request.provider,
                    # FK — upstream threat scan ID
                    "scan_id": threat_scan_id,
                    "tenant_id": request.tenant_id
                }

                response = await client.post(
                    f"{self.iam_engine_url}/api/v1/iam-security/scan",
                    json=iam_request
                )
                response.raise_for_status()
                result = response.json()

                return {
                    "status": "completed",
                    "iam_scan_id": result.get("iam_scan_id") or result.get("report_id"),
                    "message": "IAM security report generated",
                    "findings_count": result.get("summary", {}).get("total_findings", 0)
                }

        except Exception as e:
            logger.error(f"IAM security step failed: {e}", exc_info=True)
            return {
                "status": "failed",
                "error": str(e)
            }

    async def _run_data_security(
        self,
        request: OrchestrationRequest,
        orchestration_id: str,
        threat_scan_id: str
    ) -> Dict[str, Any]:
        """Run data security engine.

        Upstream FK: threat_scan_id (reads threat_findings from threat DB)
        Produces: datasec_scan_id

        NOTE: This was previously named 'check_scan_id' param but actually
        received threat_report_id. Fixed to use correct name: threat_scan_id.
        """
        try:
            async with httpx.AsyncClient(timeout=600.0) as client:
                datasec_request = {
                    "orchestration_id": orchestration_id,
                    "csp": request.provider,
                    # FK — upstream threat scan ID
                    "scan_id": threat_scan_id,
                    "tenant_id": request.tenant_id,
                    "include_classification": True,
                    "include_lineage": True,
                    "include_residency": True,
                    "include_activity": True
                }

                response = await client.post(
                    f"{self.datasec_engine_url}/api/v1/data-security/scan",
                    json=datasec_request
                )
                response.raise_for_status()
                result = response.json()

                return {
                    "status": "completed",
                    "datasec_scan_id": result.get("datasec_scan_id") or result.get("report_id"),
                    "message": "Data security report generated",
                    "findings_count": result.get("summary", {}).get("total_findings", 0)
                }

        except Exception as e:
            logger.error(f"Data security step failed: {e}", exc_info=True)
            return {
                "status": "failed",
                "error": str(e)
            }

    async def _run_inventory(
        self,
        request: OrchestrationRequest,
        orchestration_id: str,
        discovery_scan_id: str
    ) -> Dict[str, Any]:
        """Run inventory scan.

        Upstream FK: discovery_scan_id (reads discovery_findings from discoveries DB)
        Produces: inventory_scan_id (returned as scan_run_id)
        """
        try:
            async with httpx.AsyncClient(timeout=3600.0) as client:
                inventory_request = {
                    "orchestration_id": orchestration_id,
                    "tenant_id": request.tenant_id,
                    # FK — upstream discovery scan ID
                    "configscan_scan_id": discovery_scan_id,
                    "providers": [request.provider],
                    "accounts": [request.hierarchy_id] if request.hierarchy_id else None,
                    "previous_scan_id": None
                }

                response = await client.post(
                    f"{self.inventory_engine_url}/api/v1/inventory/scan/discovery",
                    json=inventory_request
                )
                response.raise_for_status()
                result = response.json()

                return {
                    "status": "completed",
                    "scan_run_id": result.get("scan_run_id"),
                    "message": "Inventory scan completed",
                    "total_assets": result.get("total_assets", 0),
                    "total_relationships": result.get("total_relationships", 0)
                }

        except Exception as e:
            logger.error(f"Inventory step failed: {e}", exc_info=True)
            return {
                "status": "failed",
                "error": str(e)
            }
