version: '1.0'
rule_id: aws.cloudfront.distributions_multiple_origin_failover_configured.distributions_origin_failover_configured
for_each: aws.cloudfront.get_distribution_config
severity: MEDIUM
conditions:
  var: item.OriginGroups
  op: not_empty
