# Generated by Django 5.2.10 on 2026-01-16 19:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('severity', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='tenant_management.tenants')),
            ],
            options={
                'db_table': 'threats',
            },
        ),
        migrations.CreateModel(
            name='ThreatRelatedFinding',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_id', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_findings', to='threats_management.threat')),
            ],
            options={
                'db_table': 'threat_related_findings',
            },
        ),
        migrations.CreateModel(
            name='ThreatRemediationStep',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.IntegerField(blank=True, null=True)),
                ('step_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_steps', to='threats_management.threat')),
            ],
            options={
                'db_table': 'threat_remediation_steps',
            },
        ),
        migrations.AddIndex(
            model_name='threat',
            index=models.Index(fields=['tenant', 'severity'], name='threats_tenant__eed8e2_idx'),
        ),
        migrations.AddIndex(
            model_name='threat',
            index=models.Index(fields=['tenant', 'status'], name='threats_tenant__24ae0f_idx'),
        ),
        migrations.AddIndex(
            model_name='threat',
            index=models.Index(fields=['name'], name='threats_name_58d70f_idx'),
        ),
        migrations.AddIndex(
            model_name='threatrelatedfinding',
            index=models.Index(fields=['threat'], name='threat_rela_threat__9d0b29_idx'),
        ),
        migrations.AddIndex(
            model_name='threatrelatedfinding',
            index=models.Index(fields=['finding_id'], name='threat_rela_finding_452bfd_idx'),
        ),
        migrations.AddConstraint(
            model_name='threatrelatedfinding',
            constraint=models.UniqueConstraint(fields=('threat', 'finding_id'), name='unique_threat_finding'),
        ),
        migrations.AddIndex(
            model_name='threatremediationstep',
            index=models.Index(fields=['threat', 'step_order'], name='threat_reme_threat__4b32a0_idx'),
        ),
    ]
