"""
Orchestration Client - Interface to scan_orchestration table in shared database.

This module provides functions to:
1. Retrieve scan context (provider, account, services, regions, etc.) by scan_run_id
2. Read orchestration metadata for pipeline coordination

The scan_run_id is generated by the scheduler and serves as the pipeline-wide
identifier for a complete scan workflow across all engines.

Self-Service Pattern:
- Engines receive ONLY scan_run_id in their API requests
- Engines call get_scan_context(scan_run_id) to hydrate all parameters
"""

import logging
from typing import Dict, Optional, Any
import psycopg2
from psycopg2.extras import RealDictCursor

logger = logging.getLogger(__name__)


def _get_onboarding_db_connection():
    """
    Get connection to the onboarding database containing scan_orchestration table.

    MOVED: scan_orchestration table moved from threat_engine_shared to threat_engine_onboarding
    for better data locality and simpler architecture.
    """
    try:
        from .config.database_config import get_onboarding_config

        config = get_onboarding_config()
        conn = psycopg2.connect(
            host=config.host,
            port=config.port,
            database=config.database,
            user=config.username,
            password=config.password,
            connect_timeout=10
        )
        return conn
    except Exception as e:
        logger.error(f"Failed to connect to onboarding database: {e}")
        raise


def get_scan_context(scan_run_id: str) -> Optional[Dict[str, Any]]:
    """
    Retrieve scan context from scan_orchestration table by scan_run_id.

    Self-Service Pattern: Engines call this to hydrate all scan parameters.

    Args:
        scan_run_id: The pipeline-wide scan run UUID

    Returns:
        Dict containing:
            - customer_id: Customer identifier
            - tenant_id: Tenant identifier
            - provider: Cloud service provider (aws, azure, gcp, oci, alicloud, ibm, k8s)
            - account_id: Cloud account/subscription/project identifier
            - credential_type: Authentication method ('iam_role' or 'access_key')
            - credential_ref: IAM role ARN or Secrets Manager path
            - include_services: List of services to scan (JSONB array) - null = all
            - include_regions: List of regions to scan (JSONB array) - null = all
            - exclude_services: List of services to exclude (JSONB array) - null = none
            - exclude_regions: List of regions to exclude (JSONB array) - null = none
            - execution_id: Links to executions table (scheduler)
            - schedule_id: Links to schedules table
            - Other orchestration metadata

        None if scan_run_id not found or error occurs

    Example:
        >>> ctx = get_scan_context("550e8400-e29b-41d4-a716-446655440000")
        >>> ctx['provider']
        'aws'
        >>> ctx['include_services']  # None = scan all services
        None
        >>> ctx['include_regions']
        ['ap-south-1']
    """
    if not scan_run_id:
        logger.warning("get_scan_context called with empty scan_run_id")
        return None

    conn = None
    try:
        conn = _get_onboarding_db_connection()

        with conn.cursor(cursor_factory=RealDictCursor) as cursor:
            query = """
                SELECT
                    scan_run_id,
                    execution_id,
                    schedule_id,
                    tenant_id,
                    customer_id,
                    provider,
                    account_id,
                    credential_type,
                    credential_ref,
                    include_services,
                    include_regions,
                    exclude_services,
                    exclude_regions,
                    engines_requested,
                    overall_status,
                    created_at,
                    started_at,
                    completed_at
                FROM scan_orchestration
                WHERE scan_run_id = %s
            """
            cursor.execute(query, (scan_run_id,))
            row = cursor.fetchone()

            if row:
                logger.info(
                    f"Retrieved scan context for scan_run_id={scan_run_id}",
                    extra={"extra_fields": {
                        "provider": row.get("provider"),
                        "account_id": row.get("account_id")
                    }}
                )
                return dict(row)
            else:
                logger.warning(f"No scan context found for scan_run_id={scan_run_id}")
                return None

    except Exception as e:
        logger.error(
            f"Failed to retrieve scan context for scan_run_id={scan_run_id}: {e}",
            exc_info=True
        )
        return None
    finally:
        if conn:
            conn.close()
