rule_id: azure.synapse.workspaces.configure_azure_synapse_workspaces_to_disable_public_network_access
service: synapse
resource: workspaces
title: Configure Azure Synapse workspaces to disable public network access
description: 'Disable public network access for your Synapse workspace so that it is not accessible over the public internet.
  This can reduce data leakage risks. Learn more at: https://docs.microsoft.com/azure/synapse-analytics/security/connectivity-settings.'
domain: storage_and_database_security
severity: medium
scope: synapse.workspaces
assertion_id: synapse.configure_azure_synapse_workspaces_to_disable_public_network_access
effect: Modify
resource_type: Microsoft.Synapse/workspaces
policy_id: 5c8cad01-ef30-4891-b230-652dadb4876a
source: azure_policy_builtin
