version: '1.0'
rule_id: k8s.pod.seccomp.profile_runtime_default_check
for_each: k8s.pod.list_pods
severity: LOW
conditions:
  var: item.spec.securityContext.seccompProfile.type
  op: equals
  value: RuntimeDefault
