version: '1.0'
rule_id: azure.appservice.deployment.slot.vnet.integration.check
for_each: azure.appservice.list_web_apps
severity: MEDIUM
conditions:
  all:
  - var: item.SiteConfig.VnetRouteAllEnabled
    op: is_true
  - var: item.VirtualNetworkSubnetId
    op: exists
