version: '1.0'
rule_id: k8s.ingress.controller.ssl_protocols_check
for_each: k8s.ingress.list_ingresses
severity: HIGH
conditions:
  var: item.spec.tls[].spec.ssl_protocols
  op: contains
  value: TLSv1.2
