version: '1.0'
rule_id: aws.cloudwatch.metric.alerts_for_anomalies_configured
for_each: aws.cloudwatch.describe_anomaly_detectors
severity: MEDIUM
conditions:
  var: item.AnomalyDetectors
  op: not_empty
