version: '1.0'
rule_id: aws.route53.recordset.route53_no_broad_wildcards_sensitive_zones_configured
for_each: aws.route53.list_hosted_zones
severity: MEDIUM
conditions:
  all:
  - var: item.Name
    op: not_contains
    value: sensitive
  - var: item.ResourceRecordSetCount
    op: gt
    value: 0
