version: '1.0'
rule_id: aws.route53.healthcheck.https_or_tls_used_configured
for_each: aws.route53.list_health_checks
severity: HIGH
conditions:
  any:
  - var: item.HealthCheckConfig.Type
    op: equals
    value: HTTPS
  - var: item.HealthCheckConfig.Type
    op: equals
    value: HTTPS_STR_MATCH
  - var: item.HealthCheckConfig.Type
    op: equals
    value: TLS
  - var: item.HealthCheckConfig.Type
    op: equals
    value: TLS_STR_MATCH
fixture_validated: false
fixture_note: 'PASS fixture returned FAIL — wrong field or operator (pass_fixture keys: [''CallerReference'', ''CloudWatchAlarmConfiguration'',
  ''Enabled'', ''HealthCheckConfig'', ''HealthCheckVersion'', ''Id'', ''LinkedService''])'
