CREATE TABLE IF NOT EXISTS cdr_findings (
    finding_id          VARCHAR(16) PRIMARY KEY,
    scan_run_id         VARCHAR(255),
    tenant_id           VARCHAR(255) NOT NULL,
    rule_id             VARCHAR(255),
    rule_source         VARCHAR(50),   -- 'log' | 'log_correlation' | 'baseline'
    severity            VARCHAR(20),
    status              VARCHAR(20) DEFAULT 'open',
    primary_engine      VARCHAR(50),
    engines             JSONB,
    action_category     VARCHAR(100),
    resource_uid        VARCHAR(1024),
    resource_type       VARCHAR(255),
    resource_name       VARCHAR(512),
    account_id          VARCHAR(512),
    region              VARCHAR(100),
    provider            VARCHAR(50),
    actor_principal     TEXT,
    actor_principal_type VARCHAR(50),  -- 'iam_user' | 'iam_role' | 'service_account' | 'root' | 'anonymous'
    actor_ip            VARCHAR(45),
    event_id            VARCHAR(255),
    event_time          TIMESTAMPTZ,
    event_hour          SMALLINT GENERATED ALWAYS AS (EXTRACT(HOUR FROM event_time)::smallint) STORED,
    service             VARCHAR(100),
    operation           VARCHAR(255),
    title               TEXT,
    description         TEXT,
    remediation         TEXT,
    mitre_tactics       JSONB,
    mitre_techniques    JSONB,
    risk_indicators     JSONB,
    compliance_frameworks JSONB,
    finding_data        JSONB,
    credential_ref      VARCHAR(255),
    credential_type     VARCHAR(50),
    first_seen_at       TIMESTAMPTZ DEFAULT NOW(),
    last_seen_at        TIMESTAMPTZ DEFAULT NOW(),
    created_at          TIMESTAMPTZ DEFAULT NOW()
);
