version: '1.0'
rule_id: k8s.network.networkpolicy.namespace_isolation_enforced
for_each: k8s.network.list_network_policy_for_all_namespaces
severity: LOW
conditions:
  var: item.metadata.annotations.cspm.k8s.io/networkpolicy-isolate-healthcare-clearinghouse-configured
  op: exists
