version: '1.0'
rule_id: k8s.network.networkpolicy.network_policies_enforced
for_each: k8s.network.list_network_policy_for_all_namespaces
severity: MEDIUM
conditions:
  var: item.metadata.annotations.cspm.k8s.io/networkpolicy-dns-filtering-enabled
  op: is_true
