version: '1.0'
provider: azure
service: guestconfig
services:
  client: guestconfig
  module: azure.mgmt.guestconfig
discovery:
- discovery_id: azure.guestconfig.guestconfigurationassignments.subscription_list
  calls:
  - action: subscription_list
    save_as: response
    on_error: continue
  emit:
    as: item
    items_for: '{{ response.value }}'
- discovery_id: azure.guestconfig.guestconfigurationassignments.subscription_list
  calls:
  - action: subscription_list
    save_as: response
    on_error: continue
  emit:
    as: item
    items_for: '{{ response.value }}'
- discovery_id: azure.guestconfig.guestconfigurationassignmentreports.list
  calls:
  - action: list
    save_as: response
    on_error: continue
  emit:
    as: item
    items_for: '{{ response.value }}'
checks: []
