# Generated by Django 6.0.1 on 2026-02-28 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0002_initial'),
        ('user_auth', '0005_rename_name_first_users_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenants',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tenantusers',
            options={},
        ),
        migrations.RemoveField(
            model_name='tenantusers',
            name='status',
        ),
        migrations.AddField(
            model_name='tenants',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantusers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantusers',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_auth.roles'),
        ),
        migrations.AlterField(
            model_name='tenantusers',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenant_management.tenants'),
        ),
        migrations.AlterField(
            model_name='tenantusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tenants',
            index=models.Index(fields=['name'], name='tenants_name_bc4541_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantusers',
            index=models.Index(fields=['tenant'], name='tenant_user_tenant__192555_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantusers',
            index=models.Index(fields=['user'], name='tenant_user_user_id_f93ec7_idx'),
        ),
    ]
