"""
Git Patcher — clones repo, applies fixes, pushes a new branch.

Flow:
  1. Clone repo into a temp directory.
  2. Checkout source branch.
  3. Create fix branch: secops-fix/{secops_scan_id[:8]}
  4. For each FixResult where can_auto_patch=True:
       - Replace offending line with suggested_fix.
       - Stage the file.
  5. Commit all changes.
  6. Push fix branch to origin.
  7. Clean up temp directory.
"""

import logging
import os
import re
import shutil
import tempfile
from typing import List, Optional, Tuple

logger = logging.getLogger(__name__)

try:
    import git as gitpython
    _GIT_AVAILABLE = True
except ImportError:
    _GIT_AVAILABLE = False
    logger.warning("GitPython not installed — git patching disabled. Install: pip install gitpython")


def apply_fixes(
    repo_url: str,
    repo_token: str,
    secops_scan_id: str,
    source_branch: str,
    fix_results: list,  # List[FixResult]
) -> Tuple[Optional[str], str, int]:
    """
    Clone repo, apply all auto-patchable fixes, push fix branch.

    Returns:
        (fix_branch, local_repo_path, patched_count)
        local_repo_path is returned so the caller can read original lines.
        Caller is responsible for calling cleanup(local_repo_path) after use.
    """
    if not _GIT_AVAILABLE:
        raise RuntimeError("GitPython is not installed. Run: pip install gitpython")

    fix_branch = f"secops-fix/{secops_scan_id[:8]}"
    auth_url = _inject_token(repo_url, repo_token)
    tmp_dir = tempfile.mkdtemp(prefix="secops_fix_")

    try:
        logger.info(f"Cloning {repo_url} branch={source_branch} → {tmp_dir}")
        repo = gitpython.Repo.clone_from(
            auth_url,
            tmp_dir,
            branch=source_branch,
            depth=1,
        )

        # Create and checkout the fix branch
        fix_ref = repo.create_head(fix_branch)
        fix_ref.checkout()

        # Apply fixes
        patched_files = set()
        patched_count = 0
        for fix in fix_results:
            if not fix.can_auto_patch:
                continue
            if not fix.file_path or not fix.line_number or not fix.suggested_fix:
                continue
            success = _patch_line(tmp_dir, fix.file_path, fix.line_number, fix.suggested_fix)
            if success:
                patched_files.add(fix.file_path)
                patched_count += 1

        if not patched_files:
            logger.info("No auto-patchable fixes — fix branch not pushed")
            cleanup(tmp_dir)
            return None, tmp_dir, 0

        # Stage and commit
        repo.index.add(list(patched_files))
        commit_msg = (
            f"fix(secops-fix): automated remediation for scan {secops_scan_id[:8]}\n\n"
            f"Auto-patched {patched_count} finding(s) identified by SecOps scanner.\n"
            f"Review each change before merging — validate fixes in your test environment.\n\n"
            f"Generated by secops-fix engine."
        )
        repo.index.commit(commit_msg)

        # Push fix branch
        origin = repo.remotes.origin
        origin.set_url(auth_url)
        origin.push(refspec=f"{fix_branch}:{fix_branch}")
        logger.info(f"Pushed fix branch {fix_branch} with {patched_count} patches")

        # Reset auth URL to avoid leaking token in repo config
        origin.set_url(repo_url)

        return fix_branch, tmp_dir, patched_count

    except Exception:
        cleanup(tmp_dir)
        raise


def clone_readonly(repo_url: str, repo_token: str, source_branch: str) -> str:
    """
    Clone repo read-only (no fix branch). Used so fix_generator can read
    original source lines before deciding on patches.

    Returns local path. Caller must call cleanup(path) when done.
    """
    if not _GIT_AVAILABLE:
        raise RuntimeError("GitPython is not installed. Run: pip install gitpython")

    auth_url = _inject_token(repo_url, repo_token)
    tmp_dir = tempfile.mkdtemp(prefix="secops_readonly_")
    gitpython.Repo.clone_from(auth_url, tmp_dir, branch=source_branch, depth=1)
    return tmp_dir


def cleanup(local_path: str) -> None:
    """Remove the cloned temp directory."""
    if local_path and os.path.exists(local_path):
        shutil.rmtree(local_path, ignore_errors=True)
        logger.debug(f"Cleaned up {local_path}")


# ── Helpers ───────────────────────────────────────────────────────────────────

def _inject_token(repo_url: str, token: str) -> str:
    """Embed PAT into HTTPS URL for authenticated push/pull."""
    if not token:
        return repo_url
    # https://github.com/... → https://TOKEN@github.com/...
    return re.sub(r"^https://", f"https://{token}@", repo_url)


def _patch_line(
    repo_root: str,
    file_path: str,
    line_number: int,
    suggested_fix: str,
) -> bool:
    """
    Replace line at line_number (1-based) in file_path with suggested_fix.
    Returns True if successful.
    """
    full_path = os.path.join(repo_root, file_path.lstrip("/"))
    if not os.path.isfile(full_path):
        logger.warning(f"File not found for patching: {full_path}")
        return False
    try:
        with open(full_path, "r", encoding="utf-8", errors="replace") as f:
            lines = f.readlines()
        idx = line_number - 1
        if idx < 0 or idx >= len(lines):
            logger.warning(f"Line {line_number} out of range in {file_path} ({len(lines)} lines)")
            return False
        # Preserve original indentation
        original = lines[idx]
        indent = len(original) - len(original.lstrip())
        lines[idx] = " " * indent + suggested_fix.lstrip() + "\n"
        with open(full_path, "w", encoding="utf-8") as f:
            f.writelines(lines)
        logger.debug(f"Patched {file_path}:{line_number}")
        return True
    except Exception as e:
        logger.error(f"Failed to patch {file_path}:{line_number}: {e}")
        return False
