version: '1.0'
rule_id: k8s.audit.policy.change_detection_enabled
for_each: k8s.audit.list_event_for_all_namespaces
severity: MEDIUM
conditions:
  var: item.metadata.annotations.cspm.k8s.io/configuration-change-detection-enabled
  op: is_true
