version: '1.0'
rule_id: aws.shield.protection.shield_ip_rate_limit_rules_configured_if_supported
for_each: aws.shield.list_protections
severity: MEDIUM
conditions:
  var: item.ApplicationLayerAutomaticResponseConfiguration
  op: exists
