version: '1.0'
rule_id: gcp.security_command_center.finding.breach_detection_alert_destinations_configured
for_each: gcp.security_command_center.list_sources
severity: HIGH
conditions:
  var: item.alert_destinations
  op: not_empty
