rule_id: azure.managed_grafana.grafana.azure_managed_grafana_workspaces_should_disable_email_settings
service: managed_grafana
resource: grafana
title: Azure Managed Grafana workspaces should disable email settings
description: Disables SMTP settings configuration of email contact point for alerting
  in Grafana workspace.
domain: logging_monitoring_and_alerting
severity: medium
scope: managed_grafana.grafana
assertion_id: managed_grafana.azure_managed_grafana_workspaces_should_disable_email_settings
effect: Audit
resource_type: Microsoft.Dashboard/grafana
policy_id: b6752a42-6fc3-46cb-8a15-33aa109407b1
source: azure_policy_builtin
mitre_techniques:
- T1562.008
mitre_tactics:
- defense-evasion
threat_tags:
- logging-disabled
threat_category: defense_evasion
