#!/usr/bin/env python3
"""
Comprehensive OCI Service Mappings - Final Phase
"""

# Complete OCI Service Mapping Dictionary
COMPREHENSIVE_OCI_SERVICE_MAPPINGS = {
    # === Phase 1: CSP Mappings (AWS/Azure/GCP → OCI) ===
    'acm': 'certificates',
    'api': 'apigateway',
    'apigatewayv2': 'apigateway',
    'app': 'functions',
    'appsync': 'apigateway',
    'autoscaling': 'compute',
    'cloudwatch': 'monitoring',
    'codebuild': 'devops',
    'config': 'cloud_guard',
    'defender': 'cloud_guard',
    'directconnect': 'virtual_network',
    'dms': 'database',
    'ebs': 'block_storage',
    'efs': 'file_storage',
    'emr': 'bds',
    'eventbridge': 'events',
    'guardduty': 'cloud_guard',
    'kafka': 'streaming',
    'kinesis': 'streaming',
    'load': 'load_balancer',
    'mq': 'streaming',
    'neptune': 'database',
    'networkfirewall': 'network_firewall',
    'no': 'identity',
    'object': 'object_storage',
    'opensearch': 'analytics',
    'organizations': 'identity',
    'os': 'compute',
    'route53': 'dns',
    'sagemaker': 'data_science',
    'secretsmanager': 'vault',
    'securityhub': 'cloud_guard',
    'servicecatalog': 'resource_manager',
    'sqs': 'queue',
    'ssm': 'compute',
    'stepfunctions': 'data_integration',
    'storagegateway': 'object_storage',
    'transfer': 'object_storage',
    'wafv2': 'waf',
    'workspaces': 'compute',
    
    # === Phase 2: Additional CSP Services ===
    'athena': 'analytics',
    'awslambda': 'functions',
    'bedrock': 'ai_language',
    'cloudtrail': 'audit',
    'glue': 'data_catalog',
    'bigquery': 'analytics',
    'cloudsql': 'mysql',
    'cloudstorage': 'object_storage',
    'dataproc': 'bds',
    'gcr': 'artifacts',
    'cosmosdb': 'database',
    'entra': 'identity',
    'keyvault': 'key_management',
    'postgresql': 'mysql',
    'sqlserver': 'database',
    'vm': 'compute',
    
    # === Phase 3: OKE/Kubernetes Services ===
    'kubernetes': 'container_engine',
    'oke_add_ons_coredns_metrics_server_etc': 'container_engine',
    'oke_admission_controllers_webhooks': 'container_engine',
    'oke_calico_cilium_networkpolicies': 'container_engine',
    'oke_control_plane_api_server': 'container_engine',
    'oke_controller_manager': 'container_engine',
    'oke_core_services_ingress_lb': 'container_engine',
    'oke_deployment_statefulset_daemonset_jobs': 'container_engine',
    'oke_etcd_managed': 'container_engine',
    'oke_namespaces': 'container_engine',
    'oke_node_pools': 'container_engine',
    'oke_rbac': 'container_engine',
    'oke_scheduler': 'container_engine',
    'oke_service_account_k8s_dynamic_group_mapping': 'container_engine',
    'oke_service_lb_nlb_integration': 'container_engine',
    'oke_serviceaccount_token_projection': 'container_engine',
    'oke_workload_identity': 'container_engine',
    
    # === Phase 4: OCI Prefixed Services (manually reviewed) ===
    'oci_api_gateway_request_response_validation_openapi': 'apigateway',
    'oci_api_gateway_throttling_rate_limits': 'apigateway',
    'oci_apm_distributed_tracing': 'monitoring',
    'oci_apm_trace_sampling_rules': 'monitoring',
    'oci_application_configuration_parameters': 'functions',  # App config → Functions
    'oci_audit_always_on': 'audit',
    'oci_audit_control_plane_source': 'audit',
    'oci_backup_block_volume_boot_volume_jobs': 'block_storage',  # Backup for block volumes
    'oci_backup_policies_scheduled': 'block_storage',
    'oci_block_volumes_bv_boot_volume': 'block_storage',  # Block volumes
    'oci_cdn_rules_cache_settings': 'edge_services',  # CDN → Edge Services
    'oci_certificates_managed_certs': 'certificates',
    'oci_certificates_private_ca': 'certificates',
    'oci_cloud_guard_configuration_change_detections': 'cloud_guard',
    'oci_cloud_guard_detector_responder_recipes_baselines': 'cloud_guard',
    'oci_cloud_guard_detector_rules': 'cloud_guard',
    'oci_cloud_guard_incidents': 'cloud_guard',
    'oci_cloud_guard_posture': 'cloud_guard',
    'oci_cloud_guard_posture_compliance': 'cloud_guard',
    'oci_cloud_guard_responders': 'cloud_guard',
    'oci_cloud_guard_targets_compartments_tenancy': 'cloud_guard',
    'oci_compute_capacity_reservations': 'compute',
    'oci_compute_instances_vm_bm_flex': 'compute',
    'oci_container_registry_ocir_retention_lifecycle_rules': 'artifacts',
    'oci_cost_analysis_custom_groups_by_tags': 'identity',  # Cost → Usage/Identity
    'oci_cost_analysis_tags_compartments': 'identity',
    'oci_custom_images_boot_volume_backups': 'compute',
    'oci_data_flow_apache_spark': 'data_flow',
    'oci_data_flow_flink_via_spark_alternatives': 'data_flow',
    'oci_data_flow_serverless_spark': 'data_flow',
    'oci_data_integration_data_flow': 'data_integration',
    'oci_data_integration_pipeline': 'data_integration',
    'oci_data_integration_pipeline_definition': 'data_integration',
    'oci_data_safe_data_masking': 'data_safe',
    'oci_data_safe_masking': 'data_safe',
    'oci_data_safe_sensitive_types': 'data_safe',
    'oci_data_science_automl_via_notebooks': 'data_science',
    'oci_data_science_automl_via_sdk_notebooks': 'data_science',
    'oci_data_science_custom_feature_store_pattern': 'data_science',
    'oci_data_science_https_endpoint': 'data_science',
    'oci_data_science_jobs': 'data_science',
    'oci_data_science_model_deployment': 'data_science',
    'oci_data_science_model_versions': 'data_science',
    'oci_data_science_project': 'data_science',
    'oci_drg_dynamic_routing_gateway': 'virtual_network',
    'oci_drg_route_rules_attachments_upgrade_path': 'virtual_network',
    'oci_functions_fn_project': 'functions',
    'oci_hsm_dedicated': 'key_management',
    'oci_iam_dynamic_groups': 'identity',
    'oci_iam_groups': 'identity',
    'oci_iam_policies': 'identity',
    'oci_iam_users': 'identity',
    'oci_ip_sec_vpn_tunnels': 'virtual_network',
    'oci_lakehouse_data_fabric': 'data_catalog',
    'oci_load_balancer_lb': 'load_balancer',
    'oci_local_peering_gateway_lpg': 'virtual_network',
    'oci_logging_log_groups_logs': 'logging',
    'oci_mysql_heatwave_analytics': 'mysql',
    'oci_mysql_heatwave_lakehouse': 'mysql',
    'oci_nat_gateway': 'virtual_network',
    'oci_network_firewall': 'network_firewall',
    'oci_network_path_analyzer': 'virtual_network',
    'oci_nosql_table': 'nosql',
    'oci_notification_service': 'ons',
    'oci_observability_management_dashboards': 'monitoring',
    'oci_object_storage_bucket': 'object_storage',
    'oci_private_endpoint_pe_for_services': 'virtual_network',
    'oci_queue_service': 'queue',
    'oci_remote_peering_connection_rpc': 'virtual_network',
    'oci_resource_manager_stack_job': 'resource_manager',
    'oci_rover_rugged_portable_hsms': 'key_management',
    'oci_security_lists_sl': 'virtual_network',
    'oci_security_zones': 'cloud_guard',
    'oci_service_connector_hub_sch': 'events',
    'oci_service_gateway': 'virtual_network',
    'oci_service_mesh_istio_patterns': 'container_engine',
    'oci_streaming_apache_kafka_api': 'streaming',
    'oci_streaming_stream_pools': 'streaming',
    'oci_tagging_tag_namespaces_keys_defaults': 'identity',
    'oci_tenancy_cost_billing': 'identity',
    'oci_tenancy_limits_quota': 'identity',
    'oci_tenancy_wide_policies': 'identity',
    'oci_vault_cryptographic_key_hsm': 'key_management',
    'oci_vault_kms_object_storage_encryption': 'key_management',
    'oci_vault_secrets': 'vault',
    'oci_vcn_route_tables': 'virtual_network',
    'oci_vcn_subnets': 'virtual_network',
    'oci_vcn_virtual_cloud_network': 'virtual_network',
    'oci_vcn_vnics': 'virtual_network',
    'oci_vulnerability_scanning_service': 'cloud_guard',
    'oci_waf_address_lists': 'waf',
    'oci_waf_policy_rule_groups': 'waf',
    'oci_waf_regex_filters': 'waf',
    'oci_waf_rule': 'waf',
    'oci_web_application_firewall_waf': 'waf',
    'oci_workload_monitoring_alarms_topics': 'monitoring',
    
    # === Phase 5: Composite/Descriptive Services ===
    'cdn_origin_rules_policies': 'edge_services',
    'committed_use_universal_credits': 'identity',  # Billing/Usage
    'compartments_hierarchy': 'identity',
    'compartments_policies': 'identity',
    'compute_ssh_keys_metadata': 'compute',
    'customer_prem_router_cpe_in_ipsec': 'virtual_network',
    'deployment_versions_resource_manager_devops': 'devops',
    'devops_projects_data_science_projects': 'devops',
    'di_pipeline_parameter': 'data_integration',
    'dynamic_groups_for_instances_functions': 'identity',
    'event_rules_sch_logs_object_storage_streams': 'events',
    'fastconnect_expressroute_interconnect': 'virtual_network',
    'file_systems_mount_targets': 'file_storage',
    'functions_fn': 'functions',
    'golden_gate_stream_replication_patterns': 'data_integration',
    'gpu_shapes_a100_h100': 'compute',
    'hpc_high_performance_computing_cluster_network_rdma': 'compute',
    'http_https_path_route_set': 'load_balancer',
    'iam_identity_domains_idcs': 'identity',
    'instances_shapes_vm_bm_flex': 'compute',
    'integration_cloud_oci_integration': 'data_integration',
    'internet_gateway': 'virtual_network',
    'kms_envelope_encryption_pattern': 'key_management',
    'limits_tenancy_and_compartment_quotas': 'identity',
    'marketplace_apps_images': 'compute',
    'mfa_for_iam_users': 'identity',
    'namespace_container_image_stream': 'artifacts',
    'network_load_balancer_nlb': 'load_balancer',
    'network_security_groups_nsg': 'virtual_network',
    'nlb_backend_set_servers': 'load_balancer',
    'oracle_autonomous_transaction_processing_atp_warehouse_adw_json': 'database',
    'oracle_base_database_service_bm_vm_exadata': 'database',
    'oracle_database_operator_for_kubernetes': 'database',
    'private_dns_views_zones_records': 'dns',
    'rdbms_mysql_postgresql_patterns': 'mysql',
    'reachability_vnics_instances': 'virtual_network',
    'service_limits_quotas': 'identity',
    'shared_responsibility_model_compliance': 'cloud_guard',
    'subscriptions_universal_credits': 'identity',
    'tag_based_cost_tracking': 'identity',
    'terraform_resource_manager': 'resource_manager',
    'user_credentials_api_keys': 'identity',
    'vaults_cryptographic_keys_hsm': 'key_management',
    'vcn_flow_logs': 'virtual_network',
    'virtual_firewall_appliances_partner_marketplace': 'network_firewall',
    'waf_backend_origin_groups': 'waf',
    
    # === Phase 6: Oracle/Exadata Services ===
    'exadata_adb_backup': 'database',
    'exadata_cloud_service_autonomous_db_serverless_dedicated': 'database',
    'oracle_application_container_oracle_app_dev_on_oke_functions': 'functions',
    'oracle_weblogic_on_oci': 'compute',
    
    # === Phase 7: Remaining Unknown Services (best guess) ===
    'accessanalyzer': 'cloud_guard',  # AWS IAM Access Analyzer → Cloud Guard
    'account': 'identity',
    'aisearch': 'ai_language',
    'apikeys': 'identity',
    'appstream': 'compute',
    'autonomous': 'database',  # Autonomous DB
    'big': 'bds',  # Big Data Service
    'block': 'block_storage',
    'budget': 'identity',  # Usage/Billing
    'bv': 'block_storage',  # Boot Volume
    'certificate': 'certificates',
    'cloud': 'identity',  # Generic cloud
    'data': 'data_catalog',
    'db': 'database',
    'dedicated': 'compute',  # Dedicated hosts
    'dr': 'database',  # Disaster Recovery
    'ecr': 'artifacts',
    'ecs': 'container_instances',
    'elb': 'load_balancer',
    'event': 'events',
    'file': 'file_storage',
    'flow': 'virtual_network',  # Flow logs
    'gateway': 'virtual_network',
    'heatwave': 'mysql',
    'helm': 'container_engine',
    'hosted': 'virtual_network',
    'internet': 'virtual_network',
    'kms': 'key_management',
    'log': 'logging',
    'logging': 'logging',
    'marketplace': 'compute',
    'mesh': 'container_engine',
    'metadata': 'compute',
    'mysql': 'mysql',
    'namespace': 'artifacts',
    'network': 'virtual_network',
    'nlb': 'load_balancer',
    'nsg': 'virtual_network',
    'ocir': 'artifacts',
    'param': 'functions',  # Parameters
    'pod': 'container_engine',
    'project': 'data_science',
    'public': 'virtual_network',
    'redshift': 'database',
    'remote': 'virtual_network',
    'replica': 'database',
    'resolver': 'dns',
    'runtime': 'functions',
    'secret': 'vault',
    's3': 'object_storage',
    'stack': 'resource_manager',
    'state': 'resource_manager',
    'subnet': 'virtual_network',
    'tag': 'identity',
    'transit': 'virtual_network',
    'vcn': 'virtual_network',
    'volume': 'block_storage',
    'web': 'waf',
    'zone': 'dns',
    
    # === Phase 8: Remaining Unknown Services (from analysis) ===
    'cdn': 'edge_services',
    'cdn_rule': 'waf',
    'codeartifact': 'artifacts',
    'container': 'container_engine',
    'containerregistry': 'artifacts',
    'core': 'compute',  # OCI Core compute services
    'custom_dq_rules_di': 'data_integration',
    'datasync': 'data_integration',
    'di_param_attributes': 'data_integration',
    'di_param_constraints': 'data_integration',
    'di_parameter_object': 'data_integration',
    'directoryservice': 'identity',
    'documentdb': 'nosql',
    'edge_services': 'edge_services',
    'eip': 'virtual_network',  # Elastic IP
    'elasticbeanstalk': 'compute',
    'elasticache': 'database',
    'event_rule': 'events',
    'event_rules_service': 'events',
    'eventbridge_rule': 'events',
    'fsx': 'file_storage',
    'grafana': 'monitoring',
    'iam_role': 'identity',
    'incident_management': 'monitoring',
    'insight_type_in_resource_analyzer': 'cloud_guard',
    'lakehouse_dbms': 'database',
    'lakehouse_features_heatwave_lakehouse_bq': 'database',
    'lb_backend_set': 'load_balancer',
    'lb_listener': 'load_balancer',
    'linux_windows_baremetal_vm': 'compute',
    'macie': 'data_safe',
    'mfa_iam': 'identity',
    'nat': 'virtual_network',
    'nat_gw': 'virtual_network',
    'network_acl': 'virtual_network',
    'nlb_listener': 'load_balancer',
    'nsg_security_group': 'virtual_network',
    'observability_and_monitoring': 'monitoring',
    'oke_cluster': 'container_engine',
    'os_management_patch_schedules': 'compute',
    'osms': 'compute',  # OS Management Service
    'policy': 'identity',
    'private_endpoints_pep_service_gateway': 'virtual_network',
    'recovery_service_restore': 'database',
    'resource_manager_ansible': 'resource_manager',
    'resource_manager_stacks': 'resource_manager',
    'search': 'identity',
    'security_lists_subnet_level': 'virtual_network',
    'security_zones': 'cloud_guard',
    'security_zones_policy_guardrails': 'cloud_guard',
    'service_connector_hub': 'events',
    'service_connector_hub_fan_out_delivery': 'events',
    'service_connector_hub_functions': 'events',
    'service_connector_hub_to_object_storage_functions_stream': 'events',
    'shield': 'cloud_guard',  # AWS Shield → Cloud Guard
    'storage': 'object_storage',
    'streaming_consumer_group': 'streaming',
    'subnet_regional_ad': 'virtual_network',
    'vault_key_alias': 'key_management',
    'vault_key_grants_iam_permissions': 'key_management',
    'vcn_route_table': 'virtual_network',
    'vcn_subnet_nsg_security_lists': 'virtual_network',
    'vcn_subnet_segmentation_nsg': 'virtual_network',
    'vcn_subnets_db_subnet_group': 'virtual_network',
    'vcn_virtual_cloud_network': 'virtual_network',
    'vnic_virtual_nic': 'virtual_network',
    'vpc': 'virtual_network',
    'vss_host_container_image_scans': 'cloud_guard',
    'vss_scan_recipes_targets': 'cloud_guard',
    'waf_network_firewall_alerts': 'cloud_guard',
    'wellarchitected': 'cloud_guard',
    
    # === Phase 9: Final Unknown Services (OCI-specific descriptive names) ===
    'elbv2': 'load_balancer',
    'events_functions_triggers_api_gateway_object_events': 'events',
    'fastconnect_via_drg_vlan': 'virtual_network',
    'file_storage_snapshots': 'file_storage',
    'firehose': 'streaming',
    'fsdr_dr_drills_test_plans': 'database',
    'fsdr_recovery_compute_db': 'database',
    'fsdr_runbooks': 'database',
    'fsdr_source_assets': 'database',
    'fss_file_system': 'file_storage',
    'fss_snapshots': 'file_storage',
    'full_stack_dr_jobs': 'database',
    'full_stack_dr_plans': 'database',
    'full_stack_dr_workflows': 'database',
    'functions_concurrency_scaling_config': 'functions',
    'functions_events_resource_manager': 'functions',
    'functions_image_version_ocir_deployment_version': 'functions',
    'glacier': 'object_storage',
    'goldengate': 'data_integration',
    'iam_groups': 'identity',
    'iam_policies': 'identity',
    'iam_policies_policy_statements': 'identity',
    'integration': 'data_integration',
    'monitor': 'monitoring',
    'notification': 'ons',
    'objectstorage': 'object_storage',
    'oci_db_systems_mysql_oracle_autonomous_transaction_processing_atp': 'database',
    'oci_dedicated_vm_hosts': 'compute',
    'oci_dns_traffic_management_steering_policies': 'dns',
    'oci_dns_zone': 'dns',
    'oci_events_db_events': 'events',
    'oci_events_to_trigger_harvest': 'events',
    'oci_file_storage_fss': 'file_storage',
    'oci_full_stack_disaster_recovery_fsdr_runbooks': 'database',
    'oci_functions_events': 'functions',
    'oci_functions_fn': 'functions',
    'oci_functions_ops_automation': 'functions',
    'oci_health_checks': 'monitoring',
    'oci_iam_policies_dynamic_groups_role_like': 'identity',
    'oci_iam_policy_defined_roles_identity_domain_roles': 'identity',
    'oci_iam_users_identity_domains': 'identity',
    'oci_instance_configuration': 'compute',
    'oci_instance_pools': 'compute',
    'oci_load_balancer_lbaas': 'load_balancer',
    'oci_load_balancer_listener_lbaas_nlb': 'load_balancer',
    'oci_media_streams_live': 'streaming',
    'oci_network_load_balancer_nlb': 'load_balancer',
    'oci_nosql_database_global_table': 'nosql',
    'oci_notifications_alarms': 'monitoring',
    'oci_notifications_email_sms': 'ons',
    'oci_notifications_pagerduty_email_sms': 'ons',
    'oci_object_storage_backup_buckets': 'object_storage',
    'oci_object_storage_datasets': 'object_storage',
    'oci_object_storage_retention_rules': 'object_storage',
    'oci_preemptible_instances': 'compute',
    'oci_queue_queue_service': 'queue',
    'oci_recovery_service': 'database',
    'oci_recovery_service_db_backups_vault_like': 'database',
    'oci_resource_manager_iac_docs_wiki_self_managed': 'resource_manager',
    'oci_service_connector_hub': 'events',
    'oci_streaming_kafka_compatible': 'streaming',
    'oci_streaming_topic': 'streaming',
    'oci_tenancy_compartments': 'identity',
    'oci_usage_reports_budgets_alerts': 'identity',
    'oci_vault_hsm': 'key_management',
    'oci_vault_hsm_backed_keys': 'key_management',
    'oci_vault_key': 'key_management',
    'oci_vulnerability_scanning_service_vss': 'cloud_guard',
    'ocir_cross_region_replication': 'artifacts',
    'ocir_repository': 'artifacts',
    'ocir_repository_policies_pull_push': 'artifacts',
    'oke_worker_nodes_kubelet': 'container_engine',
    'oracle_container_engine_for_kubernetes_oke': 'container_engine',
    'os_management_patch_jobs': 'compute',
    
    # === Phase 10: Final SDK Alignment ===
    'redis': 'nosql',  # OCI Redis Cache → NoSQL service
    'ai_anomaly_detection': 'ai_anomaly',  # OCI AI Anomaly Detection service
}

print(f"Total Service Mappings: {len(COMPREHENSIVE_OCI_SERVICE_MAPPINGS)}")
print("✅ Comprehensive OCI Service Mappings Complete!")

