version: '1.0'
rule_id: k8s.storage.volume.backup_policy_defined
for_each: k8s.storage.list_storage_class
severity: MEDIUM
conditions:
  var: item.metadata.annotations.cspm.k8s.io/volume-backup-policy-defined
  op: exists
