# Generated by Django 6.0.1 on 2026-02-24 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_userroles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name_first',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='name_last',
            new_name='last_name',
        ),
    ]
