version: '1.0'
rule_id: azure.policy.rule.configuration_management_config_remediation_targets_bound
for_each: azure.policy.list_policy_assignments
severity: MEDIUM
conditions:
  all:
  - var: item.Properties.PolicyDefinitionId
    op: exists
  - var: item.Properties.Parameters
    op: exists
