version: '1.0'
rule_id: k8s.admission.controller.supplier_service_change_management
for_each: k8s.admission.list_validating_webhook_configuration
severity: LOW
conditions:
  var: item.metadata.annotations.cspm.k8s.io/controller-change-management-enabled
  op: is_true
