version: '1.0'
provider: gcp
service: prod_tt_sasportal
services:
  client: prod_tt_sasportal
  module: googleapiclient.discovery.build('prod_tt_sasportal', 'v1')
discovery:
- discovery_id: gcp.prod_tt_sasportal.deployments.get
  calls:
  - action: get
    save_as: response
    on_error: continue
  emit:
    as: item
    items_for: '{{ response }}'
checks: []
