version: '1.0'
rule_id: azure.kubernetes.agent_pool.containers_node_pool_nodes_no_public_ip
for_each: azure.kubernetes.list_agent_pools
severity: MEDIUM
conditions:
  var: item.Properties.AgentPoolProfiles[].EnableNodePublicIP
  op: is_false
