version: '1.0'
rule_id: azure.kubernetes.admission_controller.containers_admission_pod_security_admission_restricted_default
for_each: azure.kubernetes.managed_clusters.list
severity: MEDIUM
conditions:
  all:
  - var: item.properties.podSecurityProfile.enabled
    op: is_true
  - var: item.properties.podSecurityProfile.defaultMode
    op: equals
    value: Restricted
