version: '1.0'
rule_id: azure.kubernetes.deployment.containers_workload_image_tag_not_latest
for_each: azure.kubernetes.list_containers_workloads
severity: MEDIUM
conditions:
  all:
  - var: item.image_tag
    op: exists
  - var: item.image_tag
    op: not_equals
    value: latest
