version: '1.0'
rule_id: azure.kubernetes.scheduler.k8s_profiling_disabled
for_each: azure.kubernetes.clusters.list
severity: MEDIUM
conditions:
  var: item.addonProfiles.azurePolicy.enabled
  op: is_false
