version: '1.0'
rule_id: azure.kubernetes.scheduler.k8s_leader_election_enabled
for_each: azure.kubernetes.list_clusters
severity: MEDIUM
conditions:
  var: item.Properties.EnableLeaderElection
  op: is_true
