version: '1.0'
rule_id: azure.kubernetes.namespace.containers_pod_security_level_restricted
for_each: azure.kubernetes.namespaces.list
severity: MEDIUM
conditions:
  var: item.podSecurityLevel
  op: equals
  value: restricted
