version: '1.0'
rule_id: azure.kubernetes.kubelet.k8s_protect_kernel_defaults_enabled
for_each: azure.kubernetes.list_clusters
severity: MEDIUM
conditions:
  var: item.properties.agentPoolProfiles[].kubeletConfig.protectKernelDefaults
  op: is_true
