version: '1.0'
rule_id: azure.kubernetes.rbac.containers_authorization_mode_rbac_enabled
for_each: azure.kubernetes.list_clusters
severity: MEDIUM
conditions:
  var: item.properties.securityProfile.azureDefender.securityMonitoring.enabled
  op: is_true
