version: '1.0'
rule_id: azure.kubernetes.scheduler.containers_authentication_kubeconfig_configured
for_each: azure.kubernetes.managed_clusters.list
severity: MEDIUM
conditions:
  var: item.properties.agentPoolProfiles[].kubeletConfig
  op: exists
