rule_id: azure.network.firewall_policies.deprecated_azure_firewall_premium_should_configure_a_valid_intermediate_certific
service: network
resource: firewall_policies
title: '[Deprecated]: Azure Firewall Premium should configure a valid intermediate
  certificate to enable TLS inspection'
description: This policy is deprecated because Microsoft 365 App Compliance Program
  no longer requires Azure Firewall premium as the only network security control solution.
  Learn more details about the latest M365 APP Compliance requirements about network
  security controls at aka.ms/acat-cert2-seg-ops-nsc. Learn more about policy definition
  deprecation at aka.ms/policydefdeprecation.
domain: network_security_and_connectivity
severity: high
scope: network.firewall_policies
assertion_id: network.deprecated_azure_firewall_premium_should_configure_a_valid_intermediate_certific
effect: Disabled
resource_type: Microsoft.Network/firewallPolicies
policy_id: 711c24bb-7f18-4578-b192-81a6161e1f17
source: azure_policy_builtin
mitre_techniques:
- T1562.001
mitre_tactics:
- defense-evasion
threat_tags:
- tls-inspection-disabled
threat_category: defense_evasion
