# Generated by Django 5.2.10 on 2026-01-16 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets_management', '0001_initial'),
        ('tenant_management', '0001_initial'),
        ('threats_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='tenant_management.tenants'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='tenant_management.tenants'),
        ),
        migrations.AddField(
            model_name='assetcompliance',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_links', to='assets_management.asset'),
        ),
        migrations.AddField(
            model_name='assettag',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='assets_management.asset'),
        ),
        migrations.AddField(
            model_name='assetthreat',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_links', to='assets_management.asset'),
        ),
        migrations.AddField(
            model_name='assetthreat',
            name='threat',
            field=models.ForeignKey(blank=True, db_column='threat_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='threats_management.threat'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['tenant', 'status'], name='agents_tenant__fad503_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['agent_id'], name='agents_agent_i_cdfbf2_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'resource_type'], name='assets_tenant__5bdea3_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'environment'], name='assets_tenant__1aeabf_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['resource_id'], name='assets_resourc_57922f_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('tenant', 'resource_id'), name='unique_tenant_resource'),
        ),
        migrations.AddIndex(
            model_name='assetcompliance',
            index=models.Index(fields=['asset'], name='asset_compl_asset_i_afd702_idx'),
        ),
        migrations.AddIndex(
            model_name='assetcompliance',
            index=models.Index(fields=['compliance_id'], name='asset_compl_complia_bd7890_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetcompliance',
            constraint=models.UniqueConstraint(fields=('asset', 'compliance_id'), name='unique_asset_compliance'),
        ),
        migrations.AddIndex(
            model_name='assettag',
            index=models.Index(fields=['asset', 'tag_key'], name='asset_tags_asset_i_52ca7d_idx'),
        ),
        migrations.AddIndex(
            model_name='assettag',
            index=models.Index(fields=['tag_key', 'tag_value'], name='asset_tags_tag_key_e58f79_idx'),
        ),
        migrations.AddConstraint(
            model_name='assettag',
            constraint=models.UniqueConstraint(fields=('asset', 'tag_key'), name='unique_asset_tag_key'),
        ),
        migrations.AddIndex(
            model_name='assetthreat',
            index=models.Index(fields=['asset'], name='asset_threa_asset_i_3a0217_idx'),
        ),
        migrations.AddIndex(
            model_name='assetthreat',
            index=models.Index(fields=['threat'], name='asset_threa_threat__c370b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetthreat',
            constraint=models.UniqueConstraint(fields=('asset', 'threat'), name='unique_asset_threat'),
        ),
    ]
