version: '1.0'
rule_id: alicloud.dts.tables_kms_cmk_encryption_at_rest_enabled.configured
for_each: alicloud.dts.DescribeDataCheckTableDetails
severity: MEDIUM
conditions:
  var: item.encrypted
  op: is_true
