"""
Docker Generic Rule Engine - Enhanced AST Version

A generic rule engine that can apply any rule based on JSON metadata to Dockerfile AST.
Handles AST traversal, rule applicability checking, and pattern matching for Dockerfiles.
Supports various Dockerfile instructions like FROM, RUN, COPY, ADD, USER, WORKDIR, etc.

This engine works with the AST structure generated by docker_ast_parser.py
AST Structure:
    DockerfileNode (root)
     ├── InstructionNode (FROM, RUN, COPY, etc.)
     │     ├── ArgumentNode (arguments/values)
     │     ├── FlagNode (--flag=value)
     │     ├── KeyValueNode (ENV, ARG, LABEL key-value pairs)
     │     └── CommandNode (shell/exec commands)
     └── CommentNode (comments)
"""

import re
import json
import sys
from docker_scanner import logic_implementations
from typing import Any, Dict, List, Optional, Union
try:
    from docker_ast_parser import ASTNode, InstructionNode, DockerfileNode
except ImportError:
    # Fallback if AST parser not available
    ASTNode = None
    InstructionNode = None
    DockerfileNode = None


class DockerGenericRule:
    def __init__(self, metadata):
        self.metadata = metadata
        self.logic = metadata.get("logic", {})
        self.rule_id = metadata.get("rule_id", "unknown_rule")
        self.message = metadata.get("title", "Rule violation")

    def is_applicable(self, ast_tree):
        """
        Check if the rule is applicable to the given Dockerfile AST.
        Returns True if the rule should be applied.
        """
        if not self.metadata or not self.rule_id:
            return False
        
        function_name = None
        if isinstance(self.logic.get('checks'), list):
            for check in self.logic.get('checks', []):
                if isinstance(check, dict):
                    if check.get('type') == 'custom_function':
                        function_name = check.get('function')
                        break
        
        # Also check for custom_function at the root logic level
        if not function_name and self.logic.get('custom_function'):
            function_name = self.logic.get('custom_function')
        
        custom_function = self._get_custom_function(function_name)
        
        # Check for required instruction types at root logic level
        required_instruction_types = self.logic.get("instruction_types", [])
        matching_instructions = []
        
        if required_instruction_types:
            matching_instructions = self._find_instructions_by_type(ast_tree, required_instruction_types)
        
        # Also check instruction_types within individual checks
        if not matching_instructions and isinstance(self.logic.get('checks'), list):
            for check in self.logic.get('checks', []):
                if isinstance(check, dict):
                    check_instruction_types = check.get("instruction_types", [])
                    if check_instruction_types:
                        matching_instructions = self._find_instructions_by_type(ast_tree, check_instruction_types)
                        if matching_instructions:
                            break
        
        return len(matching_instructions) > 0 or custom_function is not None

    def check(self, ast_tree, filename):
        """
        Apply all checks defined in the rule logic to the AST.
        Returns a list of findings.
        """
        try:
            findings = []
            seen_findings = set()
            
            # Apply generic logic checks
            generic_findings = self._apply_generic_logic(ast_tree, filename, seen_findings)
            findings.extend(generic_findings)
            
            # Apply custom function if defined
            custom_function_name = self._get_custom_function_name()
            if custom_function_name:
                custom_function = self._get_custom_function(custom_function_name)
                if custom_function:
                    custom_findings = self._apply_custom_function(ast_tree, filename, custom_function_name, seen_findings)
                    findings.extend(custom_findings)
            
            return findings
        except Exception as e:
            import traceback
            traceback.print_exc()
            return []

    def _get_custom_function_name(self):
        """Extract custom function name from metadata."""
        if isinstance(self.logic.get('checks'), list):
            for check in self.logic.get('checks', []):
                if check.get('type') == 'custom_function' and check.get('function'):
                    return check.get('function')
        
        if self.logic.get('custom_function'):
            return self.logic.get('custom_function')
        
        return None

    def _apply_generic_logic(self, ast_tree, filename, seen_findings):
        """Apply generic logic checks defined in metadata."""
        findings = []
        
        if not isinstance(self.logic.get('checks'), list):
            # Single check at root level
            if self._is_valid_generic_check(self.logic):
                findings.extend(self._apply_single_check(ast_tree, filename, self.logic, seen_findings, is_root_check=True))
        else:
            # Multiple checks
            for check in self.logic.get("checks", []):
                if self._is_valid_generic_check(check):
                    findings.extend(self._apply_single_check(ast_tree, filename, check, seen_findings, is_root_check=False))
        
        return findings

    def _apply_single_check(self, ast_tree, filename, check, seen_findings, is_root_check=False):
        """Apply a single check to the AST."""
        findings = []
        check_type = check.get("type") or check.get("check_type")
        
        # instruction_count checks operate on the entire AST, not per instruction
        if check_type == "instruction_count":
            findings.extend(self._apply_instruction_count_check(check, ast_tree, filename, seen_findings))
            return findings
        
        # Determine which instructions to check
        if is_root_check:
            required_instruction_types = self.logic.get("instruction_types", [])
        else:
            required_instruction_types = check.get("instruction_types", self.logic.get("instruction_types", []))
        
        matching_instructions = self._find_instructions_by_type(ast_tree, required_instruction_types) if required_instruction_types else [ast_tree]
        
        for instruction in matching_instructions:
            instruction_type = instruction.get('instruction', 'unknown') if isinstance(instruction, dict) else 'root'
            instruction_value = instruction.get('value', '') if isinstance(instruction, dict) else ''
            
            if isinstance(check, dict):
                if check_type == "regex_match":
                    findings.extend(self._apply_regex_check(check, instruction, filename, instruction_type, instruction_value, seen_findings))
                elif check_type == "property_comparison":
                    findings.extend(self._apply_property_comparison_check(check, instruction, filename, instruction_type, instruction_value, seen_findings))
                elif check_type == "forbidden_value":
                    findings.extend(self._apply_forbidden_value_check(check, instruction, filename, instruction_type, instruction_value, seen_findings))
                elif check_type == "required_value":
                    findings.extend(self._apply_required_value_check(check, instruction, filename, instruction_type, instruction_value, seen_findings))
                elif check_type == "instruction_exists":
                    findings.extend(self._apply_instruction_exists_check(check, instruction, filename, instruction_type, instruction_value, seen_findings))
        
        return findings

    def _is_valid_generic_check(self, check):
        """Check if this is a valid generic check (not a custom function)."""
        check_type = check.get("type") or check.get("check_type")
        
        if check_type == "custom_function":
            return False
        
        # Support Docker-specific check types
        supported_types = [
            "regex_match", 
            "property_comparison", 
            "forbidden_value", 
            "required_value",
            "instruction_count",
            "instruction_exists",
            "instruction_order",
            "argument_check",
            "flag_check",
            "user_check",
            "permission_check"
        ]
        
        return check_type in supported_types

    def _apply_regex_check(self, check, instruction, filename, instruction_type, instruction_value, seen_findings):
        """Apply regex pattern matching check."""
        findings = []
        patterns = check.get("patterns", [])
        
        # Handle single pattern as well
        single_pattern = check.get("pattern")
        if single_pattern:
            patterns = [single_pattern]
        
        property_path = check.get("property_path")
        if not patterns or not property_path:
            return findings
        
        value = self._get_property(instruction, property_path)
        
        for pattern in patterns:
            # Use DOTALL and MULTILINE flags for Dockerfile content
            if isinstance(value, str) and re.search(pattern, value, re.DOTALL | re.MULTILINE):
                finding = self._make_finding(filename, instruction_type, instruction_value, property_path, value, check.get('message', 'Pattern match'), instruction)
                unique_key = (self.rule_id, filename, finding.get('line', 0), str(property_path))
                if unique_key not in seen_findings:
                    seen_findings.add(unique_key)
                    findings.append(finding)
        
        return findings

    def _apply_property_comparison_check(self, check, instruction, filename, instruction_type, instruction_value, seen_findings):
        """Apply property comparison check."""
        findings = []
        property_path = check.get("property_path")
        operator = check.get("operator")
        value = check.get("value")
        
        instruction_prop_value = self._get_property(instruction, property_path)
        
        if operator and instruction_prop_value is not None:
            if self._evaluate_comparison(instruction_prop_value, operator, value):
                finding = self._make_finding(filename, instruction_type, instruction_value, property_path, instruction_prop_value, check.get('message', self.message), instruction)
                unique_key = (self.rule_id, filename, finding.get('line', 0), str(property_path))
                if unique_key not in seen_findings:
                    seen_findings.add(unique_key)
                    findings.append(finding)
        
        return findings

    def _apply_forbidden_value_check(self, check, instruction, filename, instruction_type, instruction_value, seen_findings):
        """Check if instruction contains forbidden values."""
        findings = []
        property_path = check.get("property_path")
        forbidden_values = check.get("forbidden_values", [])
        
        value = self._get_property(instruction, property_path)
        
        if value in forbidden_values:
            finding = self._make_finding(filename, instruction_type, instruction_value, property_path, value, check.get('message', self.message), instruction)
            unique_key = (self.rule_id, filename, finding.get('line', 0), str(property_path))
            if unique_key not in seen_findings:
                seen_findings.add(unique_key)
                findings.append(finding)
        
        return findings

    def _apply_required_value_check(self, check, instruction, filename, instruction_type, instruction_value, seen_findings):
        """Check if instruction has required values."""
        findings = []
        property_path = check.get("property_path")
        required_values = check.get("required_values", [])
        
        value = self._get_property(instruction, property_path)
        
        if value not in required_values:
            finding = self._make_finding(filename, instruction_type, instruction_value, property_path, value, check.get('message', self.message), instruction)
            unique_key = (self.rule_id, filename, finding.get('line', 0), str(property_path))
            if unique_key not in seen_findings:
                seen_findings.add(unique_key)
                findings.append(finding)
        
        return findings

    def _apply_instruction_count_check(self, check, ast_tree, filename, seen_findings):
        """Check instruction count constraints (e.g., only one ENTRYPOINT or CMD instruction)."""
        findings = []
        instruction_types = check.get("instruction_types", [])
        operator = check.get("operator")
        count_value = check.get("count", 1)
        
        if not instruction_types:
            return findings
        
        # Count matching instructions across the entire AST
        matching = self._find_instructions_by_type(ast_tree, instruction_types)
        actual_count = len(matching)
        
        if self._evaluate_comparison(actual_count, operator, count_value):
            # Create findings for each matching instruction (to show all violations)
            for instruction in matching:
                instruction_type = instruction.get('instruction', 'unknown')
                instruction_value = instruction.get('value', '')
                finding = self._make_finding(filename, instruction_type, instruction_value, "count", actual_count, 
                                             check.get('message', self.message), instruction)
                unique_key = (self.rule_id, filename, finding.get('line', 0), instruction_type)
                if unique_key not in seen_findings:
                    seen_findings.add(unique_key)
                    findings.append(finding)
        
        return findings

    def _apply_instruction_exists_check(self, check, instruction, filename, instruction_type, instruction_value, seen_findings):
        """Flag any instruction that matches the specified types (e.g., for deprecated instructions)."""
        findings = []
        
        # Simply create a finding for the matched instruction
        finding = self._make_finding(filename, instruction_type, instruction_value, "instruction", instruction_type, check.get('message', self.message), instruction)
        unique_key = (self.rule_id, filename, finding.get('line', 0), instruction_type)
        if unique_key not in seen_findings:
            seen_findings.add(unique_key)
            findings.append(finding)
        
        return findings

    def _apply_custom_function(self, ast_tree, filename, function_name, seen_findings):
        """Apply custom function logic."""
        findings = []
        custom_fn = getattr(logic_implementations, function_name, None)
        
        if not custom_fn:
            return findings
        
        # Check if the custom function takes AST and filename parameters
        try:
            import inspect
            sig = inspect.signature(custom_fn)
            params = list(sig.parameters.keys())
            
            if len(params) >= 2 and 'ast_tree' in params and 'filename' in params:
                # Function expects AST and filename
                custom_findings = custom_fn(ast_tree, filename)
                if isinstance(custom_findings, list):
                    findings.extend(custom_findings)
                return findings
        except Exception:
            pass
        
        # Fallback to instruction-based approach
        def visit_instruction(instruction):
            if custom_fn(instruction):
                # Extract line number from Dockerfile AST structure
                line_number = 0
                if isinstance(instruction, dict):
                    line_number = instruction.get('line', 0) or instruction.get('lineno', 0)
                
                # Create finding with proper deduplication
                finding = {
                    "rule_id": self.rule_id,
                    "message": self.message,
                    "file": filename,
                    "line": line_number,
                    "status": "violation"
                }
                
                # Add deduplication logic
                instruction_type = instruction.get('instruction', '')
                value = instruction.get('value', '')
                unique_key = (self.rule_id, filename, line_number, instruction_type)
                if unique_key not in seen_findings:
                    seen_findings.add(unique_key)
                    findings.append(finding)
        
        def traverse(node):
            if isinstance(node, dict):
                visit_instruction(node)
                for v in node.values():
                    traverse(v)
            elif isinstance(node, list):
                for item in node:
                    traverse(item)
        
        traverse(ast_tree)
        return findings

    def _get_custom_function(self, function_name):
        """Retrieve custom function from logic_implementations module."""
        if not function_name:
            return None
        
        if hasattr(logic_implementations, function_name):
            func = getattr(logic_implementations, function_name)
            if callable(func):
                return func
        
        return None

    def _find_instructions_by_type(self, ast_tree, instruction_types):
        """
        Find all Dockerfile instructions matching the specified types.
        Common instruction types: FROM, RUN, COPY, ADD, USER, WORKDIR, ENV, EXPOSE, etc.
        
        Works with both AST objects and dictionary representations.
        """
        found_instructions = []
        stack = [ast_tree]
        seen = set()
        
        while stack:
            node = stack.pop()
            node_id = id(node)
            
            if node_id in seen:
                continue
            seen.add(node_id)
            
            # Handle AST Node objects
            if hasattr(node, 'node_type') and hasattr(node, 'instruction'):
                # This is an InstructionNode from AST parser
                instruction_type = node.instruction
                if instruction_type and instruction_type.upper() in [it.upper() for it in instruction_types]:
                    # Convert to dict for processing
                    found_instructions.append(node.to_dict() if hasattr(node, 'to_dict') else node)
                
                # Traverse children
                if hasattr(node, 'children'):
                    for child in node.children:
                        stack.append(child)
                if hasattr(node, 'instructions'):
                    for inst in node.instructions:
                        stack.append(inst)
            
            # Handle dictionary nodes (backward compatibility)
            elif isinstance(node, dict):
                # Check 'instruction' field (common in Dockerfile parsers)
                instruction_type = node.get('instruction') or node.get('type')
                
                if instruction_type and instruction_type.upper() in [it.upper() for it in instruction_types]:
                    found_instructions.append(node)
                
                # Traverse dict values
                for key, value in node.items():
                    if key not in ['parent']:  # Avoid circular references
                        stack.append(value)
            
            # Handle lists
            elif isinstance(node, list):
                for item in node:
                    stack.append(item)
        
        return found_instructions

    def _get_property(self, node, property_path):
        """
        Navigate property path in node structure.
        Supports both AST objects and dictionaries.
        
        property_path can be:
        - list: ['key_values', 0, 'has_space_before_equal']
        - string: 'instruction' or 'value'
        """
        if not property_path:
            return node
        
        # Ensure property_path is a list
        if isinstance(property_path, str):
            property_path = [property_path]
        
        current = node
        for part in property_path:
            # Handle lists first (when part is an index)
            if isinstance(current, list):
                try:
                    current = current[int(part)]
                except (ValueError, IndexError, TypeError):
                    return None
            # Handle AST Node objects (when part is a string attribute name)
            elif isinstance(part, str) and hasattr(current, part):
                current = getattr(current, part)
            # Handle dictionaries
            elif isinstance(current, dict):
                if part not in current:
                    return None
                current = current[part]
            else:
                return None
        
        return current

    def _evaluate_comparison(self, value, operator, target):
        """Evaluate comparison operations."""
        if value is None:
            return False
        
        if operator == "equals":
            return value == target
        elif operator == "strict_equals":
            return value is target
        elif operator == "contains":
            return str(target) in str(value)
        elif operator == "startswith":
            return str(value).startswith(str(target))
        elif operator == "endswith":
            return str(value).endswith(str(target))
        elif operator == "regex_match":
            try:
                return bool(re.search(str(target), str(value)))
            except re.error:
                return False
        elif operator in [">", "<", ">=", "<="]:
            try:
                val = float(value)
                tgt = float(target)
                if operator == ">": return val > tgt
                if operator == "<": return val < tgt
                if operator == ">=": return val >= tgt
                if operator == "<=": return val <= tgt
            except (ValueError, TypeError):
                return False
        
        return False

    def _make_finding(self, filename, instruction_type, instruction_value, property_path, value, message=None, instruction=None):
        """Create a finding dictionary."""
        finding = {
            "rule_id": self.rule_id,
            "message": message or self.message,
            "instruction": f"{instruction_type}",
            "file": filename,
            "property_path": property_path,
            "value": value,
            "status": "violation"
        }
        
        if instruction:
            finding["line"] = instruction.get('line', 1) or instruction.get('lineno', 1)
        
        if "severity" in self.metadata:
            finding["severity"] = self.metadata["severity"]
        elif "defaultSeverity" in self.metadata:
            finding["severity"] = self.metadata["defaultSeverity"]
        
        return finding


def run_rule(rule_metadata, ast_tree, filename):
    """
    Main entry point for running a Docker rule against a Dockerfile AST.
    
    Args:
        rule_metadata: Dictionary containing rule configuration
        ast_tree: Parsed Dockerfile AST
        filename: Path to the Dockerfile being analyzed
    
    Returns:
        List of findings (violations)
    """
    try:
        rule = DockerGenericRule(rule_metadata)
        
        if not rule.is_applicable(ast_tree):
            return []
        
        findings = rule.check(ast_tree, filename)
        return findings
    except Exception as e:
        import traceback
        traceback.print_exc()
        return []


# For backward compatibility and consistency
GenericRule = DockerGenericRule
DockerfileGenericRule = DockerGenericRule
