version: '1.0'
rule_id: alicloud.general.no_critical_findings.configured
for_each: alicloud.general.DescribeAvailableResource
severity: MEDIUM
conditions:
  all:
  - var: item.encrypted
    op: is_true
  - var: item.mfa_enabled
    op: is_true
  - var: item.backup_enabled
    op: is_true
  - var: item.logging_enabled
    op: is_true
  - var: item.ssl_enabled
    op: is_true
  - var: item.versioning_enabled
    op: is_true
