#!/usr/bin/env python3
"""
Seed Azure check rules into rule_metadata.

Covers 9 service categories: compute, network, storage, keyvault, sql,
iam/authorization, containerservice (AKS), web (AppService), monitor.

Target: >= 500 rules total. Safe to re-run — uses ON CONFLICT DO UPDATE.

Usage:
    CHECK_DB_HOST=localhost CHECK_DB_PORT=5432 \
    CHECK_DB_NAME=threat_engine_check CHECK_DB_USER=postgres \
    CHECK_DB_PASSWORD=xxx python seed_azure_check_rules.py
"""

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..'))

import psycopg2
from psycopg2.extras import Json


def _conn():
    return psycopg2.connect(
        host=os.getenv("CHECK_DB_HOST", "localhost"),
        port=int(os.getenv("CHECK_DB_PORT", "5432")),
        dbname=os.getenv("CHECK_DB_NAME", "threat_engine_check"),
        user=os.getenv("CHECK_DB_USER", "postgres"),
        password=os.getenv("CHECK_DB_PASSWORD", ""),
    )


def _r(
    rule_id, service, resource, severity, title, description,
    remediation, cis=None, nist=None, mitre_tactics=None,
    mitre_techniques=None, threat_category=None,
):
    """Helper to build a rule dict with all required fields."""
    cf = {}
    if cis:
        cf["cis_azure_1_5"] = cis if isinstance(cis, list) else [cis]
    if nist:
        cf["nist_800_53"] = nist if isinstance(nist, list) else [nist]
    return {
        "rule_id": rule_id,
        "service": service,
        "provider": "azure",
        "resource": resource,
        "severity": severity,
        "title": title,
        "description": description,
        "remediation": remediation,
        "compliance_frameworks": cf,
        "mitre_tactics": mitre_tactics or [],
        "mitre_techniques": mitre_techniques or [],
        "threat_category": threat_category or "misconfiguration",
    }


# ── STORAGE (StorageAccount, BlobContainer) ──────────────────────────────────

STORAGE_RULES = [
    _r("azure_storage_https_only", "storage", "StorageAccount", "high",
       "Ensure storage account enforces HTTPS-only traffic",
       "Storage accounts should enforce HTTPS to protect data in transit. HTTP connections expose credentials and data to network interception.",
       "In the Azure Portal: Storage account → Configuration → Secure transfer required → Enabled.",
       cis="3.1", nist=["SC-8", "SC-28"],
       mitre_tactics=["Collection"], mitre_techniques=["T1040"], threat_category="network_exposure"),
    _r("azure_storage_access_key_rotation", "storage", "StorageAccount", "medium",
       "Ensure storage account access keys are periodically regenerated",
       "Access keys should be rotated regularly to limit the window of exposure if a key is compromised.",
       "Regenerate storage account access keys at least every 90 days via the Azure Portal or CLI.",
       cis="3.2", nist=["IA-5"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1552"], threat_category="iam_misconfiguration"),
    _r("azure_storage_queue_logging_read", "storage", "StorageAccount", "medium",
       "Ensure storage logging is enabled for Queue service read requests",
       "Enabling Queue service logging allows detection of unauthorized read operations.",
       "Enable Queue storage logging for read operations via Storage Analytics.",
       cis="3.3", nist=["AU-2", "AU-12"],
       mitre_tactics=["Defense Evasion"], mitre_techniques=["T1562"], threat_category="data_exposure"),
    _r("azure_storage_queue_logging_write", "storage", "StorageAccount", "medium",
       "Ensure storage logging is enabled for Queue service write requests",
       "Enabling Queue service logging allows detection of unauthorized write operations.",
       "Enable Queue storage logging for write operations via Storage Analytics.",
       cis="3.3", nist=["AU-2"],
       mitre_tactics=["Defense Evasion"], mitre_techniques=["T1562"], threat_category="data_exposure"),
    _r("azure_storage_queue_logging_delete", "storage", "StorageAccount", "medium",
       "Ensure storage logging is enabled for Queue service delete requests",
       "Enabling Queue service logging allows detection of unauthorized delete operations.",
       "Enable Queue storage logging for delete operations via Storage Analytics.",
       cis="3.3", nist=["AU-2"],
       mitre_tactics=["Impact"], mitre_techniques=["T1485"], threat_category="data_exposure"),
    _r("azure_storage_public_access_disabled", "storage", "StorageAccount", "critical",
       "Ensure storage account public blob access is disabled",
       "Publicly accessible blob containers expose data to the internet without authentication. All storage accounts should block public access unless explicitly required.",
       "Storage account → Configuration → Allow Blob public access → Disabled.",
       cis="3.5", nist=["AC-3", "AC-17"],
       mitre_tactics=["Collection", "Exfiltration"], mitre_techniques=["T1530", "T1537"],
       threat_category="data_exposure"),
    _r("azure_storage_network_default_deny", "storage", "StorageAccount", "high",
       "Ensure storage account default network action is set to Deny",
       "Restricting network access to storage accounts reduces the attack surface. Default deny with explicit allowlist is the secure configuration.",
       "Storage account → Networking → Firewalls and virtual networks → Default action: Deny.",
       cis="3.6", nist=["SC-7", "AC-3"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"], threat_category="network_exposure"),
    _r("azure_storage_trusted_microsoft_services", "storage", "StorageAccount", "low",
       "Ensure trusted Microsoft services are allowed to bypass storage firewall",
       "Some Azure services need to access storage accounts. Allowing trusted services prevents disruption while maintaining security.",
       "Storage account → Networking → Exceptions → Allow trusted Microsoft services.",
       cis="3.7", nist=["SC-7"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
    _r("azure_storage_blob_soft_delete", "storage", "StorageAccount", "medium",
       "Ensure soft delete is enabled for Azure blob storage",
       "Soft delete allows recovery of accidentally deleted blobs within the retention period, protecting against ransomware and accidental deletion.",
       "Storage account → Data protection → Enable soft delete for blobs → set retention to at least 7 days.",
       cis="3.8", nist=["CP-9", "SI-12"],
       mitre_tactics=["Impact"], mitre_techniques=["T1485"], threat_category="data_exposure"),
    _r("azure_storage_container_soft_delete", "storage", "StorageAccount", "medium",
       "Ensure soft delete is enabled for Azure blob containers",
       "Container-level soft delete provides recovery for entire container deletions.",
       "Storage account → Data protection → Enable soft delete for containers → set retention.",
       cis="3.8", nist=["CP-9"],
       mitre_tactics=["Impact"], mitre_techniques=["T1485"], threat_category="data_exposure"),
    _r("azure_storage_cmk_encryption", "storage", "StorageAccount", "medium",
       "Ensure critical storage accounts use Customer Managed Key encryption",
       "CMK encryption gives you control over the encryption key lifecycle. If a key is compromised, you can revoke access immediately.",
       "Storage account → Encryption → Customer-managed keys → configure Key Vault.",
       cis="3.9", nist=["SC-28", "SC-12"],
       mitre_tactics=["Collection"], mitre_techniques=["T1530"], threat_category="data_exposure"),
    _r("azure_storage_blob_logging_read", "storage", "StorageAccount", "medium",
       "Ensure storage logging is enabled for Blob service read requests",
       "Blob service read logging enables detection of unauthorized data access.",
       "Enable Azure Storage Blob Analytics logging for read operations.",
       cis="3.10", nist=["AU-2", "AU-12"],
       mitre_tactics=["Collection"], mitre_techniques=["T1530"], threat_category="data_exposure"),
    _r("azure_storage_blob_logging_write", "storage", "StorageAccount", "medium",
       "Ensure storage logging is enabled for Blob service write requests",
       "Blob service write logging enables detection of unauthorized data modification.",
       "Enable Azure Storage Blob Analytics logging for write operations.",
       cis="3.10", nist=["AU-2"],
       mitre_tactics=["Collection"], mitre_techniques=["T1530"], threat_category="data_exposure"),
    _r("azure_storage_blob_logging_delete", "storage", "StorageAccount", "medium",
       "Ensure storage logging is enabled for Blob service delete requests",
       "Blob service delete logging enables detection of data destruction events.",
       "Enable Azure Storage Blob Analytics logging for delete operations.",
       cis="3.10", nist=["AU-2"],
       mitre_tactics=["Impact"], mitre_techniques=["T1485"], threat_category="data_exposure"),
    _r("azure_storage_table_logging_read", "storage", "StorageAccount", "low",
       "Ensure storage logging is enabled for Table service read requests",
       "Table service read logging supports forensic investigation of data access.",
       "Enable Azure Storage Table Analytics logging for read operations.",
       cis="3.11", nist=["AU-2"],
       mitre_tactics=["Collection"], mitre_techniques=["T1530"], threat_category="data_exposure"),
    _r("azure_storage_table_logging_write", "storage", "StorageAccount", "low",
       "Ensure storage logging is enabled for Table service write requests",
       "Table service write logging supports forensic investigation.",
       "Enable Azure Storage Table Analytics logging for write operations.",
       cis="3.11", nist=["AU-2"],
       mitre_tactics=["Collection"], mitre_techniques=["T1530"], threat_category="data_exposure"),
    _r("azure_storage_table_logging_delete", "storage", "StorageAccount", "low",
       "Ensure storage logging is enabled for Table service delete requests",
       "Table service delete logging supports detection of data destruction.",
       "Enable Azure Storage Table Analytics logging for delete operations.",
       cis="3.11", nist=["AU-2"],
       mitre_tactics=["Impact"], mitre_techniques=["T1485"], threat_category="data_exposure"),
    _r("azure_storage_tls_version_12", "storage", "StorageAccount", "high",
       "Ensure storage account minimum TLS version is 1.2",
       "TLS 1.0 and 1.1 have known vulnerabilities. Enforcing TLS 1.2 ensures strong transport security.",
       "Storage account → Configuration → Minimum TLS version → TLS 1.2.",
       cis="3.12", nist=["SC-8"],
       mitre_tactics=["Collection"], mitre_techniques=["T1040"], threat_category="network_exposure"),
    _r("azure_storage_infrastructure_encryption", "storage", "StorageAccount", "medium",
       "Ensure infrastructure encryption is enabled for storage accounts",
       "Infrastructure encryption provides an additional layer of encryption using AES-256 at the infrastructure level.",
       "Enable infrastructure encryption when creating a new storage account (cannot be enabled post-creation).",
       cis="3.14", nist=["SC-28"],
       mitre_tactics=["Collection"], mitre_techniques=["T1530"], threat_category="data_exposure"),
    _r("azure_storage_private_endpoint", "storage", "StorageAccount", "medium",
       "Ensure storage account uses private endpoints",
       "Private endpoints eliminate public internet exposure for storage accounts, routing traffic through Azure backbone.",
       "Configure Private Endpoint for storage account and disable public access.",
       cis="3.6", nist=["SC-7", "AC-4"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"], threat_category="network_exposure"),
    _r("azure_storage_sas_expiry_1hour", "storage", "StorageAccount", "medium",
       "Ensure shared access signature tokens expire within one hour",
       "Long-lived SAS tokens increase the risk of credential abuse if leaked.",
       "Generate SAS tokens with expiry set to 1 hour or less for access policy.",
       cis="3.4", nist=["IA-5"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1552"], threat_category="iam_misconfiguration"),
    _r("azure_storage_no_anonymous_access_blobs", "storage", "BlobContainer", "critical",
       "Ensure blob container has no anonymous read access",
       "Blob containers with anonymous access can be read by anyone on the internet without authentication.",
       "Blob container → Change access level → Private (no anonymous access).",
       cis="3.5", nist=["AC-3"],
       mitre_tactics=["Collection", "Exfiltration"], mitre_techniques=["T1530"],
       threat_category="data_exposure"),
    _r("azure_storage_lifecycle_policy", "storage", "StorageAccount", "low",
       "Ensure storage account has a lifecycle policy configured",
       "Lifecycle policies reduce storage costs and enforce retention policies by automatically tiering or deleting data.",
       "Configure lifecycle management policy in storage account → Lifecycle management.",
       cis=None, nist=["SI-12"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
]

# ── NETWORK (NSG, VNet, ApplicationGateway, LoadBalancer) ────────────────────

NETWORK_RULES = [
    _r("azure_nsg_rdp_restricted", "network", "NetworkSecurityGroup", "critical",
       "Ensure RDP port 3389 is not open to the internet",
       "Unrestricted RDP access allows brute-force attacks and exploitation of RDP vulnerabilities directly from the internet.",
       "Update NSG inbound rule for port 3389: restrict source to specific trusted IPs or use Azure Bastion.",
       cis="6.1", nist=["AC-17", "CM-7", "SC-7"],
       mitre_tactics=["Initial Access", "Lateral Movement"], mitre_techniques=["T1110", "T1021.001"],
       threat_category="network_exposure"),
    _r("azure_nsg_ssh_restricted", "network", "NetworkSecurityGroup", "critical",
       "Ensure SSH port 22 is not open to the internet",
       "Unrestricted SSH access from the internet exposes systems to brute-force attacks.",
       "Restrict SSH source to specific IPs or use Azure Bastion. Update NSG inbound rule source from Any to specific CIDR.",
       cis="6.2", nist=["AC-17", "CM-7", "SC-7"],
       mitre_tactics=["Initial Access", "Lateral Movement"], mitre_techniques=["T1110", "T1021.004"],
       threat_category="network_exposure"),
    _r("azure_nsg_udp_restricted", "network", "NetworkSecurityGroup", "high",
       "Ensure UDP ports are not open to the internet",
       "Open UDP ports can be exploited for reflection/amplification attacks or direct exploitation.",
       "Review and restrict UDP inbound rules in NSGs from internet sources.",
       cis="6.3", nist=["CM-7", "SC-7"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="network_exposure"),
    _r("azure_nsg_http_restricted", "network", "NetworkSecurityGroup", "medium",
       "Ensure HTTP/HTTPS ports are intentionally exposed to the internet",
       "Web ports should only be open when explicitly needed. Unexpected exposure increases attack surface.",
       "Review NSG rules allowing port 80 and 443 from internet; ensure they are intentional.",
       cis="6.4", nist=["CM-7"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="network_exposure"),
    _r("azure_nsg_flow_log_retention_90days", "network", "NetworkSecurityGroup", "medium",
       "Ensure NSG flow log retention period is greater than 90 days",
       "Flow logs are essential for incident investigation and network anomaly detection.",
       "NSG → Diagnostic settings → Flow logs → Storage account → Set retention to 90+ days.",
       cis="6.5", nist=["AU-11"],
       mitre_tactics=["Defense Evasion"], mitre_techniques=["T1562"],
       threat_category="misconfiguration"),
    _r("azure_network_watcher_enabled", "network", "NetworkSecurityGroup", "medium",
       "Ensure Network Watcher is enabled in all regions with virtual networks",
       "Network Watcher provides visibility into network traffic flows, connectivity, and security.",
       "Enable Network Watcher in all regions where VNets are deployed via Azure CLI or Portal.",
       cis="6.6", nist=["SI-4", "AU-12"],
       mitre_tactics=["Defense Evasion"], mitre_techniques=["T1562"],
       threat_category="misconfiguration"),
    _r("azure_nsg_no_allow_all_inbound", "network", "NetworkSecurityGroup", "critical",
       "Ensure NSG does not have an allow-all inbound rule from any source",
       "Allow-all inbound rules expose all ports to all traffic, defeating the purpose of network segmentation.",
       "Remove or restrict any NSG rule with source=Any, destination=Any, and Action=Allow on inbound direction.",
       cis="6.1", nist=["SC-7", "CM-7"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="network_exposure"),
    _r("azure_appgw_waf_enabled", "network", "ApplicationGateway", "high",
       "Ensure Application Gateway has WAF enabled",
       "Web Application Firewall protects web applications from common exploits like SQL injection and XSS.",
       "Application Gateway → Settings → Web Application Firewall → Enable WAF.",
       cis="6.6", nist=["SI-3", "SC-7"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="network_exposure"),
    _r("azure_appgw_waf_prevention_mode", "network", "ApplicationGateway", "medium",
       "Ensure Application Gateway WAF is in Prevention mode, not Detection mode",
       "Detection mode only logs but does not block attacks. Prevention mode actively blocks malicious requests.",
       "Application Gateway → WAF → Firewall mode → Prevention.",
       cis="6.6", nist=["SI-3"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="network_exposure"),
    _r("azure_ddos_standard_enabled", "network", "VirtualNetwork", "medium",
       "Ensure DDoS Standard protection is enabled on virtual networks with public IPs",
       "Azure DDoS Standard provides advanced protection against volumetric attacks.",
       "Enable Azure DDoS Standard plan and associate it with the VNet containing public-facing resources.",
       cis="6.4", nist=["SC-5"],
       mitre_tactics=["Impact"], mitre_techniques=["T1498"],
       threat_category="network_exposure"),
    _r("azure_vnet_private_dns_zone", "network", "VirtualNetwork", "low",
       "Ensure virtual networks use private DNS zones for internal resolution",
       "Private DNS zones prevent internal service names from being exposed to the public internet.",
       "Configure Azure Private DNS Zones and associate with VNets for internal DNS resolution.",
       cis=None, nist=["SC-20"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
    _r("azure_vnet_peering_no_gateway_transit", "network", "VirtualNetwork", "medium",
       "Ensure VNet peering does not allow gateway transit from untrusted networks",
       "Gateway transit can expose your VPN or ExpressRoute gateway to peered networks, increasing lateral movement risk.",
       "Review VNet peering settings and disable 'Allow gateway transit' unless explicitly required.",
       cis=None, nist=["SC-7"],
       mitre_tactics=["Lateral Movement"], mitre_techniques=["T1021"],
       threat_category="network_exposure"),
    _r("azure_subnet_no_default_nsg", "network", "Subnet", "medium",
       "Ensure each subnet has a Network Security Group associated",
       "Subnets without NSGs have no inbound/outbound traffic filtering, exposing all resources in the subnet.",
       "Associate a Network Security Group with every subnet.",
       cis=None, nist=["SC-7"],
       mitre_tactics=["Initial Access", "Lateral Movement"], mitre_techniques=["T1190"],
       threat_category="network_exposure"),
    _r("azure_nsg_flow_logs_enabled", "network", "NetworkSecurityGroup", "medium",
       "Ensure NSG flow logs are enabled",
       "NSG flow logs capture network traffic information for security analysis and compliance.",
       "Enable NSG flow logging in Network Watcher for all NSGs.",
       cis="6.5", nist=["AU-12", "SI-4"],
       mitre_tactics=["Defense Evasion"], mitre_techniques=["T1562"],
       threat_category="misconfiguration"),
    _r("azure_network_no_public_lb_with_backend_vms", "network", "LoadBalancer", "medium",
       "Ensure public-facing load balancers have backend pool resources appropriately secured",
       "Backend VMs behind public load balancers should have NSGs and minimal exposure.",
       "Review NSG rules on all VMs in the load balancer backend pool.",
       cis=None, nist=["SC-7", "CM-7"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="network_exposure"),
    _r("azure_public_ip_sku_standard", "network", "PublicIPAddress", "low",
       "Ensure public IP addresses use Standard SKU",
       "Standard SKU public IPs support availability zones and are required for zone-redundant deployments.",
       "Migrate Basic SKU public IPs to Standard SKU.",
       cis=None, nist=["SC-5"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
    _r("azure_network_no_management_ports_exposed", "network", "NetworkSecurityGroup", "high",
       "Ensure management ports (WinRM 5985/5986, Telnet 23) are not open to internet",
       "Management protocols exposed to the internet are high-value targets for attackers.",
       "Remove NSG rules allowing ports 5985, 5986, 23 from internet sources.",
       cis=None, nist=["CM-7", "AC-17"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1110"],
       threat_category="network_exposure"),
    _r("azure_nsg_no_all_outbound", "network", "NetworkSecurityGroup", "low",
       "Ensure NSG does not have unrestricted outbound access",
       "Restricting outbound traffic limits exfiltration and C2 communication if resources are compromised.",
       "Add outbound deny rules for unexpected ports/destinations.",
       cis=None, nist=["SC-7", "CM-7"],
       mitre_tactics=["Exfiltration"], mitre_techniques=["T1041"],
       threat_category="network_exposure"),
    _r("azure_vnet_flow_logs_traffic_analytics", "network", "VirtualNetwork", "low",
       "Ensure traffic analytics is enabled for NSG flow logs",
       "Traffic Analytics provides advanced threat detection and visualization on top of flow logs.",
       "Enable Traffic Analytics in Network Watcher for all NSG flow logs.",
       cis=None, nist=["SI-4"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
    _r("azure_private_endpoint_dns_integration", "network", "VirtualNetwork", "low",
       "Ensure private endpoints are integrated with private DNS zones",
       "Without DNS integration, private endpoints may not resolve correctly, falling back to public DNS.",
       "Integrate private endpoints with Azure Private DNS zones for correct name resolution.",
       cis=None, nist=["SC-20"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
]

# ── COMPUTE (VirtualMachine, VMSS) ────────────────────────────────────────────

COMPUTE_RULES = [
    _r("azure_vm_managed_disk", "compute", "VirtualMachine", "medium",
       "Ensure Virtual Machines use Managed Disks",
       "Managed disks provide higher reliability and simpler management than unmanaged disks (page blobs).",
       "Migrate VMs from unmanaged disks to managed disks via the Azure Portal or CLI.",
       cis="7.1", nist=["CM-6"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
    _r("azure_vm_os_disk_cmk_encryption", "compute", "VirtualMachine", "high",
       "Ensure VM OS disk is encrypted with Customer Managed Key",
       "CMK encryption gives full control over encryption keys and enables key revocation for compliance.",
       "VM → Disks → Encryption → Disk Encryption Set with CMK.",
       cis="7.2", nist=["SC-28", "SC-12"],
       mitre_tactics=["Collection"], mitre_techniques=["T1552"], threat_category="data_exposure"),
    _r("azure_vm_data_disk_cmk_encryption", "compute", "VirtualMachine", "high",
       "Ensure VM data disks are encrypted with Customer Managed Key",
       "Data disks holding sensitive information should use CMK for full control over encryption.",
       "Apply Disk Encryption Set with CMK to all data disks.",
       cis="7.2", nist=["SC-28"],
       mitre_tactics=["Collection"], mitre_techniques=["T1552"], threat_category="data_exposure"),
    _r("azure_vm_unattached_disk_encrypted", "compute", "ManagedDisk", "medium",
       "Ensure unattached managed disks are encrypted with CMK",
       "Unattached disks may contain sensitive data from previous workloads and should be encrypted.",
       "Apply CMK encryption to all unattached managed disks.",
       cis="7.3", nist=["SC-28"],
       mitre_tactics=["Collection"], mitre_techniques=["T1552"], threat_category="data_exposure"),
    _r("azure_vm_approved_extensions_only", "compute", "VirtualMachine", "medium",
       "Ensure only approved extensions are installed on Virtual Machines",
       "Unauthorized extensions can execute arbitrary code on VMs. Only approved extensions should be present.",
       "Review installed extensions and remove any not in the approved list.",
       cis="7.4", nist=["CM-7", "SI-2"],
       mitre_tactics=["Execution"], mitre_techniques=["T1059"],
       threat_category="misconfiguration"),
    _r("azure_vm_latest_os_patches", "compute", "VirtualMachine", "high",
       "Ensure Virtual Machines have latest OS patches applied",
       "Unpatched systems are vulnerable to known exploits. Regular patching reduces exposure.",
       "Enable Azure Update Management or configure automatic patching for VMs.",
       cis="7.5", nist=["SI-2", "RA-5"],
       mitre_tactics=["Privilege Escalation", "Execution"], mitre_techniques=["T1068"],
       threat_category="misconfiguration"),
    _r("azure_vm_endpoint_protection", "compute", "VirtualMachine", "high",
       "Ensure endpoint protection is installed on all Virtual Machines",
       "Endpoint protection is the last line of defence against malware and ransomware.",
       "Enable Microsoft Defender for Endpoint or compatible AV via VM extension.",
       cis="7.6", nist=["SI-3", "SI-2"],
       mitre_tactics=["Execution"], mitre_techniques=["T1059"],
       threat_category="misconfiguration"),
    _r("azure_vm_boot_diagnostics_enabled", "compute", "VirtualMachine", "low",
       "Ensure boot diagnostics is enabled for Virtual Machines",
       "Boot diagnostics captures serial console output and screenshots, enabling faster troubleshooting.",
       "VM → Support + troubleshooting → Boot diagnostics → Enable.",
       cis="7.4", nist=["AU-12"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
    _r("azure_vm_no_public_ip", "compute", "VirtualMachine", "high",
       "Ensure Virtual Machines do not have a directly assigned public IP",
       "VMs with public IPs are directly exposed to the internet. Use load balancers or bastion hosts instead.",
       "Remove public IP from VM NIC; access via internal load balancer or Azure Bastion.",
       cis=None, nist=["SC-7", "AC-17"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="network_exposure"),
    _r("azure_vm_just_in_time_access", "compute", "VirtualMachine", "high",
       "Ensure Just-In-Time access is enabled for Virtual Machines",
       "JIT access reduces attack surface by opening management ports only on demand for a limited time.",
       "Enable JIT VM access in Microsoft Defender for Cloud → Workload protections → Just-in-time VM access.",
       cis=None, nist=["AC-17", "AC-3"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1110"],
       threat_category="network_exposure"),
    _r("azure_vm_managed_identity_no_user_assigned_over_privileged", "compute", "VirtualMachine", "high",
       "Ensure VM-assigned managed identities do not have Owner or Contributor at subscription scope",
       "Overprivileged managed identities on VMs enable lateral movement if the VM is compromised.",
       "Review role assignments of managed identities attached to VMs; apply least privilege.",
       cis=None, nist=["AC-6"],
       mitre_tactics=["Privilege Escalation"], mitre_techniques=["T1078.004"],
       threat_category="iam_misconfiguration"),
    _r("azure_vm_accelerated_networking", "compute", "VirtualMachine", "low",
       "Ensure Accelerated Networking is enabled for supported VM types",
       "Accelerated networking bypasses the host to reduce latency and CPU utilization.",
       "Enable accelerated networking on NIC for supported VM SKUs.",
       cis=None, nist=[],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
    _r("azure_vm_azure_ad_login", "compute", "VirtualMachine", "medium",
       "Ensure VMs are configured to use Azure AD authentication for login",
       "Azure AD-based login eliminates local account passwords and enables conditional access policies.",
       "Install AAD login extension on VM and configure RBAC for SSH/RDP access via Azure AD.",
       cis=None, nist=["IA-2", "AC-3"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1078.004"],
       threat_category="iam_misconfiguration"),
    _r("azure_vm_disk_encryption_azure_disk", "compute", "VirtualMachine", "high",
       "Ensure Azure Disk Encryption (ADE) is enabled for VM disks",
       "ADE encrypts OS and data disks using BitLocker (Windows) or DM-Crypt (Linux) with keys in Key Vault.",
       "Enable Azure Disk Encryption on VM via portal: VM → Disks → Disk encryption.",
       cis="7.2", nist=["SC-28"],
       mitre_tactics=["Collection"], mitre_techniques=["T1552"],
       threat_category="data_exposure"),
    _r("azure_vm_vulnerability_assessment_installed", "compute", "VirtualMachine", "medium",
       "Ensure vulnerability assessment solution is installed on VMs",
       "Continuous vulnerability assessment identifies unpatched vulnerabilities before attackers exploit them.",
       "Enable Defender for Servers vulnerability assessment in Microsoft Defender for Cloud.",
       cis="2.1", nist=["RA-5"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
    _r("azure_vmss_autoscale_enabled", "compute", "VMSS", "low",
       "Ensure VM Scale Sets have autoscaling enabled",
       "Without autoscaling, scale sets cannot respond to demand spikes, causing availability issues.",
       "Configure autoscale rules for VM Scale Sets via Azure Monitor autoscale.",
       cis=None, nist=["CP-2"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
    _r("azure_vmss_automatic_os_upgrades", "compute", "VMSS", "medium",
       "Ensure automatic OS image upgrades are enabled for VM Scale Sets",
       "Automatic OS upgrades ensure VMSS instances receive the latest security patches.",
       "VMSS → Upgrade policy → Enable automatic OS image upgrade.",
       cis=None, nist=["SI-2"],
       mitre_tactics=["Privilege Escalation"], mitre_techniques=["T1068"],
       threat_category="misconfiguration"),
    _r("azure_vm_disk_double_encryption", "compute", "ManagedDisk", "medium",
       "Ensure managed disks use server-side + infrastructure encryption (double encryption)",
       "Double encryption provides an additional encryption layer using platform-managed keys at infrastructure level.",
       "Create Disk Encryption Set with double encryption enabled.",
       cis="7.2", nist=["SC-28"],
       mitre_tactics=["Collection"], mitre_techniques=["T1552"],
       threat_category="data_exposure"),
    _r("azure_vm_no_legacy_authentication", "compute", "VirtualMachine", "medium",
       "Ensure no legacy authentication methods are used to access VM management APIs",
       "Legacy authentication bypasses conditional access policies and MFA enforcement.",
       "Block legacy authentication via Conditional Access policies in Azure AD.",
       cis="1.22", nist=["IA-2", "IA-5"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1078"],
       threat_category="iam_misconfiguration"),
    _r("azure_vm_diagnostic_extension_installed", "compute", "VirtualMachine", "low",
       "Ensure Azure Diagnostics extension is installed and configured on VMs",
       "Diagnostics extension enables collection of metrics, logs, and crash dumps from VMs.",
       "Install Azure Diagnostics extension via VM extensions.",
       cis=None, nist=["AU-12"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
]

# ── KEY VAULT ─────────────────────────────────────────────────────────────────

KEYVAULT_RULES = [
    _r("azure_keyvault_soft_delete_enabled", "keyvault", "KeyVault", "high",
       "Ensure Key Vault soft delete is enabled",
       "Soft delete allows recovery of deleted vaults, keys, secrets, and certificates within the retention period.",
       "az keyvault update --name <vault> --enable-soft-delete true",
       cis="9.3", nist=["CP-9", "SI-12"],
       mitre_tactics=["Impact"], mitre_techniques=["T1485"],
       threat_category="data_exposure"),
    _r("azure_keyvault_purge_protection_enabled", "keyvault", "KeyVault", "high",
       "Ensure Key Vault purge protection is enabled",
       "Purge protection prevents permanent deletion of soft-deleted items before the retention period expires.",
       "az keyvault update --name <vault> --enable-purge-protection true",
       cis="9.4", nist=["CP-9"],
       mitre_tactics=["Impact"], mitre_techniques=["T1485"],
       threat_category="data_exposure"),
    _r("azure_keyvault_key_expiry_set", "keyvault", "KeyVault", "high",
       "Ensure expiration date is set on all keys in Key Vault",
       "Keys without expiry dates never rotate, increasing the risk of long-term key compromise.",
       "Set expiration date on all keys during key creation or via portal.",
       cis="9.1", nist=["SC-12", "IA-5"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1552"],
       threat_category="iam_misconfiguration"),
    _r("azure_keyvault_secret_expiry_set", "keyvault", "KeyVault", "high",
       "Ensure expiration date is set on all secrets in Key Vault",
       "Secrets without expiry remain valid indefinitely, increasing the blast radius of a compromise.",
       "Set expiration date on all secrets during creation or via portal.",
       cis="9.2", nist=["IA-5", "SC-12"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1552"],
       threat_category="iam_misconfiguration"),
    _r("azure_keyvault_certificate_expiry_monitored", "keyvault", "KeyVault", "medium",
       "Ensure Key Vault certificates have expiry dates and monitoring configured",
       "Expired certificates cause service outages and can be exploited if not rotated.",
       "Configure certificate expiry alerts in Key Vault and set expiration dates.",
       cis=None, nist=["IA-5", "SC-17"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1552"],
       threat_category="iam_misconfiguration"),
    _r("azure_keyvault_rbac_authorization", "keyvault", "KeyVault", "medium",
       "Ensure Key Vault uses Azure RBAC authorization model (not legacy access policies)",
       "RBAC authorization model integrates with Azure AD Privileged Identity Management and provides better auditability.",
       "Migrate Key Vault from Access Policies to Azure RBAC model via Portal → Access configuration.",
       cis=None, nist=["AC-3", "AC-6"],
       mitre_tactics=["Privilege Escalation"], mitre_techniques=["T1098"],
       threat_category="iam_misconfiguration"),
    _r("azure_keyvault_private_endpoint", "keyvault", "KeyVault", "medium",
       "Ensure Key Vault has private endpoint configured",
       "Private endpoints prevent Key Vault from being accessible over the public internet.",
       "Add a private endpoint to Key Vault and disable public network access.",
       cis=None, nist=["SC-7", "AC-3"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="network_exposure"),
    _r("azure_keyvault_no_public_network_access", "keyvault", "KeyVault", "medium",
       "Ensure Key Vault public network access is disabled",
       "Disabling public access forces all connections through private endpoints or trusted VNets.",
       "Key Vault → Networking → Public access → Disabled.",
       cis=None, nist=["SC-7"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="network_exposure"),
    _r("azure_keyvault_logging_enabled", "keyvault", "KeyVault", "high",
       "Ensure diagnostic logging is enabled for Key Vault",
       "Key Vault audit logs are critical for detecting unauthorized access to cryptographic material.",
       "Enable AuditEvent diagnostic setting on Key Vault → Diagnostic settings.",
       cis="5.5", nist=["AU-2", "AU-12"],
       mitre_tactics=["Defense Evasion"], mitre_techniques=["T1562"],
       threat_category="misconfiguration"),
    _r("azure_keyvault_key_minimum_length", "keyvault", "KeyVault", "medium",
       "Ensure cryptographic keys in Key Vault meet minimum key length requirements",
       "Weak keys (RSA < 2048 bit, ECC < 256 bit) do not provide adequate protection.",
       "Use RSA 2048+ or EC P-256+ keys. Rotate any non-compliant keys.",
       cis=None, nist=["SC-12", "SC-13"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1552"],
       threat_category="data_exposure"),
    _r("azure_keyvault_key_type_rsa_or_ec", "keyvault", "KeyVault", "low",
       "Ensure Key Vault keys use RSA or EC key type (not legacy symmetric)",
       "Asymmetric keys are preferred for modern cryptographic operations.",
       "Use RSA or EC key types. Avoid legacy symmetric key types for new workloads.",
       cis=None, nist=["SC-12", "SC-13"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
    _r("azure_keyvault_firewall_enabled", "keyvault", "KeyVault", "medium",
       "Ensure Key Vault firewall is enabled and configured with specific allowed CIDRs/VNets",
       "Key Vault firewall prevents unauthorized access from untrusted networks.",
       "Key Vault → Networking → Firewalls and virtual networks → enable and add allowed sources.",
       cis=None, nist=["SC-7"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="network_exposure"),
    _r("azure_keyvault_no_wildcard_access_policy", "keyvault", "KeyVault", "high",
       "Ensure Key Vault access policies do not grant all permissions to identities",
       "Access policies with all permissions violate least privilege and expand blast radius.",
       "Remove wildcard permissions from access policies; grant only required permissions.",
       cis=None, nist=["AC-3", "AC-6"],
       mitre_tactics=["Privilege Escalation", "Credential Access"], mitre_techniques=["T1552", "T1098"],
       threat_category="iam_misconfiguration"),
]

# ── SQL / DATABASE ─────────────────────────────────────────────────────────────

SQL_RULES = [
    _r("azure_sql_auditing_enabled", "sql", "SQLServer", "high",
       "Ensure auditing is enabled for Azure SQL Server",
       "SQL auditing tracks database events and writes them to a log for security analysis.",
       "SQL Server → Security → Auditing → On; configure storage account or Log Analytics workspace.",
       cis="4.1", nist=["AU-2", "AU-12"],
       mitre_tactics=["Defense Evasion"], mitre_techniques=["T1562"],
       threat_category="misconfiguration"),
    _r("azure_sql_tde_enabled", "sql", "SQLDatabase", "critical",
       "Ensure Transparent Data Encryption is enabled for Azure SQL Database",
       "TDE encrypts the database, backups, and transaction logs at rest, protecting against physical access attacks.",
       "SQL Database → Transparent Data Encryption → On.",
       cis="4.2", nist=["SC-28"],
       mitre_tactics=["Collection"], mitre_techniques=["T1530"],
       threat_category="data_exposure"),
    _r("azure_sql_threat_detection_all_types", "sql", "SQLServer", "high",
       "Ensure threat detection is enabled for all threat types on Azure SQL",
       "Threat detection alerts on SQL injection, anomalous access patterns, and other attacks.",
       "SQL Server → Security → Microsoft Defender for SQL → On. Enable all threat types.",
       cis="4.3", nist=["SI-4", "RA-5"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="misconfiguration"),
    _r("azure_sql_threat_alert_emails_set", "sql", "SQLServer", "medium",
       "Ensure threat detection alert recipients are configured for SQL Server",
       "Security alerts must be routed to security team email for timely response.",
       "SQL Server → Defender for SQL → Advanced settings → set alert email recipients.",
       cis="4.4", nist=["IR-6"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
    _r("azure_sql_threat_email_service_admins", "sql", "SQLServer", "medium",
       "Ensure service admins are notified on SQL threat detection alerts",
       "Service admins should be included in SQL threat alert recipients.",
       "Enable 'Email service and co-administrators' in Defender for SQL settings.",
       cis="4.5", nist=["IR-6"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
    _r("azure_sql_audit_retention_90days", "sql", "SQLServer", "medium",
       "Ensure SQL Server audit log retention is greater than 90 days",
       "Audit logs must be retained for forensic investigation. 90 days is the CIS minimum.",
       "Configure storage account retention for SQL audit logs to 90+ days.",
       cis="4.6", nist=["AU-11"],
       mitre_tactics=["Defense Evasion"], mitre_techniques=["T1562"],
       threat_category="misconfiguration"),
    _r("azure_sql_aad_admin_configured", "sql", "SQLServer", "high",
       "Ensure Azure Active Directory admin is configured for SQL Server",
       "AAD admin enables centralized identity management and eliminates local SQL passwords.",
       "SQL Server → Azure Active Directory → Set admin.",
       cis="4.7", nist=["IA-2", "AC-3"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1078"],
       threat_category="iam_misconfiguration"),
    _r("azure_sql_no_public_network_access", "sql", "SQLServer", "critical",
       "Ensure SQL Server public network access is disabled",
       "Disabling public access prevents direct internet connectivity to the SQL Server.",
       "SQL Server → Security → Firewalls and virtual networks → Deny public network access.",
       cis="4.8", nist=["SC-7", "AC-3"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="network_exposure"),
    _r("azure_sql_no_allow_all_firewall", "sql", "SQLServer", "critical",
       "Ensure SQL Server firewall does not allow all IP addresses (0.0.0.0/0)",
       "An allow-all firewall rule exposes the SQL Server to attack from any internet host.",
       "Remove the 0.0.0.0 to 255.255.255.255 firewall rule; add specific IP ranges.",
       cis="4.8", nist=["SC-7"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="network_exposure"),
    _r("azure_sql_mysql_tls_version_12", "sql", "MySQLServer", "high",
       "Ensure MySQL Flexible Server minimum TLS version is 1.2",
       "TLS 1.0 and 1.1 have known vulnerabilities. Enforce TLS 1.2 for all MySQL connections.",
       "MySQL Flexible Server → Server parameters → tls_version → TLSv1.2.",
       cis="4.9", nist=["SC-8"],
       mitre_tactics=["Collection"], mitre_techniques=["T1040"],
       threat_category="network_exposure"),
    _r("azure_sql_vulnerability_assessment_enabled", "sql", "SQLServer", "medium",
       "Ensure SQL vulnerability assessment is enabled and configured with a storage account",
       "Vulnerability assessment scans the database for misconfigurations, exposed data, and missing patches.",
       "SQL Server → Defender for SQL → Vulnerability assessment → Enable with storage account.",
       cis=None, nist=["RA-5", "CA-7"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
    _r("azure_sql_private_endpoint", "sql", "SQLServer", "medium",
       "Ensure SQL Server uses private endpoint for all connections",
       "Private endpoints eliminate public IP exposure, routing all connections through Azure backbone.",
       "Add private endpoint to SQL Server and disable public network access.",
       cis=None, nist=["SC-7"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="network_exposure"),
    _r("azure_sql_connection_policy_redirect", "sql", "SQLServer", "low",
       "Ensure SQL connection policy is set to Redirect",
       "Redirect policy offers lower latency and direct connection to SQL nodes.",
       "SQL Server → Connection policy → Redirect.",
       cis=None, nist=[],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
    _r("azure_sql_defender_advanced_data_security", "sql", "SQLServer", "high",
       "Ensure Microsoft Defender Advanced Data Security is enabled on SQL Server",
       "Advanced Data Security includes vulnerability assessment and Advanced Threat Protection.",
       "Enable Advanced Data Security in SQL Server → Security → Microsoft Defender for SQL.",
       cis="2.3", nist=["SI-4", "RA-5"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
    _r("azure_sql_data_classification_enabled", "sql", "SQLDatabase", "medium",
       "Ensure data classification is enabled on Azure SQL databases",
       "Data classification identifies sensitive columns to prioritize protection and apply appropriate controls.",
       "SQL Database → Data discovery & classification → Classify.",
       cis=None, nist=["RA-2"],
       mitre_tactics=[], mitre_techniques=[], threat_category="data_exposure"),
]

# ── IAM / ENTRA ID / AUTHORIZATION ───────────────────────────────────────────

IAM_RULES = [
    _r("azure_iam_mfa_all_users", "iam", "User", "critical",
       "Ensure MFA is enabled for all Azure AD users",
       "Multi-factor authentication prevents account takeover from compromised passwords. All users should have MFA enabled.",
       "Enable Security Defaults or Conditional Access policy requiring MFA for all users.",
       cis="1.1", nist=["IA-2", "IA-5"],
       mitre_tactics=["Credential Access", "Initial Access"], mitre_techniques=["T1078", "T1566"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_mfa_privileged_users", "iam", "User", "critical",
       "Ensure MFA is required for all privileged users (admin roles)",
       "Privileged accounts are the highest-value targets. MFA is mandatory for all admin roles.",
       "Configure Conditional Access policy requiring MFA for all users with admin roles.",
       cis="1.2", nist=["IA-2"],
       mitre_tactics=["Credential Access", "Privilege Escalation"], mitre_techniques=["T1078", "T1098"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_no_legacy_auth_protocols", "iam", "User", "high",
       "Ensure legacy authentication protocols (Basic, NTLM, IMAP, POP3) are blocked",
       "Legacy authentication bypasses Conditional Access and MFA, enabling credential stuffing attacks.",
       "Create Conditional Access policy blocking legacy authentication. Block basic auth in Exchange Online.",
       cis="1.22", nist=["IA-2", "CM-7"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1078", "T1110"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_no_permanent_global_admin", "iam", "User", "critical",
       "Ensure no users have permanent Global Administrator role",
       "Permanent admin roles increase the risk of privilege abuse. Use PIM for time-bound access.",
       "Enable Privileged Identity Management (PIM) and convert permanent admin roles to eligible assignments.",
       cis="1.25", nist=["AC-6", "AC-2"],
       mitre_tactics=["Privilege Escalation", "Persistence"], mitre_techniques=["T1078.004", "T1098"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_pim_for_privileged_roles", "iam", "User", "high",
       "Ensure Privileged Identity Management (PIM) is enabled for privileged roles",
       "PIM enforces just-in-time access, approval workflows, and audit trails for privileged roles.",
       "Enable Azure AD PIM and migrate all admin role assignments to PIM-managed eligible assignments.",
       cis="1.23", nist=["AC-2", "AC-6"],
       mitre_tactics=["Privilege Escalation"], mitre_techniques=["T1078.004"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_guest_users_reviewed", "iam", "User", "medium",
       "Ensure guest user accounts are reviewed regularly and stale guests removed",
       "Stale guest accounts from former collaborators maintain access they no longer need.",
       "Conduct quarterly guest access reviews via Azure AD → Identity Governance → Access Reviews.",
       cis="1.8", nist=["AC-2"],
       mitre_tactics=["Persistence"], mitre_techniques=["T1136"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_no_guest_invite_without_admin", "iam", "User", "medium",
       "Ensure only admins can invite guest users",
       "Unrestricted guest invitations can lead to phishing through trusted Azure AD tenant.",
       "Azure AD → External Identities → External collaboration settings → restrict invitations to admins.",
       cis="1.14", nist=["AC-2", "AC-21"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1566"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_sp_credential_expiry_set", "authorization", "ServicePrincipal", "medium",
       "Ensure all service principal credentials have expiration dates set",
       "Service principals with non-expiring credentials represent a persistent threat if compromised.",
       "Set expiry dates on all service principal credentials. Use managed identities where possible.",
       cis="1.19", nist=["IA-5"],
       mitre_tactics=["Persistence"], mitre_techniques=["T1098.001"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_sp_no_owner_contributor_subscription", "authorization", "ServicePrincipal", "critical",
       "Ensure service principals do not have Owner or Contributor role at subscription scope",
       "Subscription-scope Owner/Contributor grants blanket access to all resources, violating least privilege.",
       "Remove subscription-scope Owner/Contributor from service principals; assign resource-group-scoped roles.",
       cis="1.20", nist=["AC-6"],
       mitre_tactics=["Privilege Escalation", "Persistence"], mitre_techniques=["T1098.001", "T1078.004"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_subscription_owner_max_3", "authorization", "User", "high",
       "Ensure fewer than 3 users have subscription Owner role",
       "Minimizing subscription owners reduces the blast radius of account compromise.",
       "Remove unnecessary Owner role assignments from the subscription. Use least-privilege roles.",
       cis="1.18", nist=["AC-6", "AC-2"],
       mitre_tactics=["Privilege Escalation"], mitre_techniques=["T1078"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_no_custom_owner_role", "authorization", "User", "high",
       "Ensure no custom subscription owner roles are created",
       "Custom roles with subscription-wide write permissions are difficult to audit and manage.",
       "Remove custom owner-equivalent roles; use built-in Reader/Contributor/Owner roles.",
       cis="1.17", nist=["AC-6"],
       mitre_tactics=["Privilege Escalation"], mitre_techniques=["T1078.004"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_managed_identity_preferred", "msi", "ManagedIdentity", "medium",
       "Ensure managed identities are used instead of service principals with credentials where possible",
       "Managed identities automatically rotate credentials and eliminate the need to manage secrets.",
       "Migrate service principals with credentials to system-assigned or user-assigned managed identities.",
       cis="1.21", nist=["IA-5"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1552"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_no_app_self_service_consent", "iam", "User", "high",
       "Ensure users cannot consent to applications accessing company data",
       "Self-service app consent can grant malicious OAuth apps access to user data.",
       "Azure AD → Enterprise applications → Consent and permissions → Do not allow user consent.",
       cis="1.10", nist=["AC-21"],
       mitre_tactics=["Initial Access", "Collection"], mitre_techniques=["T1550", "T1530"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_no_user_app_registration", "iam", "User", "high",
       "Ensure non-admin users cannot register applications",
       "App registrations create service principals which can be abused for persistence and privilege escalation.",
       "Azure AD → User settings → App registrations → No.",
       cis="1.12", nist=["AC-3"],
       mitre_tactics=["Persistence"], mitre_techniques=["T1136"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_restrict_admin_portal_access", "iam", "User", "high",
       "Ensure non-admins cannot access the Azure AD administration portal",
       "Restricting portal access reduces the attack surface for social engineering and accidental misconfiguration.",
       "Azure AD → User settings → Restrict access to Azure AD administration portal → Yes.",
       cis="1.16", nist=["AC-3"],
       mitre_tactics=["Discovery"], mitre_techniques=["T1580"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_security_defaults_enabled", "iam", "User", "high",
       "Ensure Azure AD security defaults are enabled (or CA policy equivalent exists)",
       "Security defaults provide MFA, block legacy auth, and protect privileged roles automatically.",
       "Enable Security Defaults in Azure AD → Properties → Manage Security defaults → Enabled.",
       cis="1.1", nist=["IA-2", "CM-6"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1078"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_password_protection_enabled", "iam", "User", "medium",
       "Ensure Azure AD password protection is enabled and set to Enforce mode",
       "Password protection blocks weak and commonly breached passwords.",
       "Azure AD → Security → Authentication methods → Password protection → Enable (Enforced).",
       cis="1.7", nist=["IA-5"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1110"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_sspr_two_methods", "iam", "User", "medium",
       "Ensure SSPR requires two authentication methods",
       "Single-method SSPR can be bypassed if one factor is compromised.",
       "Azure AD → Password reset → Authentication methods → Number of methods required: 2.",
       cis="1.6", nist=["IA-5"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1078"],
       threat_category="iam_misconfiguration"),
    _r("azure_rbac_no_direct_user_assignment", "authorization", "User", "medium",
       "Ensure users are assigned RBAC roles through groups, not directly",
       "Direct role assignments are harder to audit and manage at scale. Group-based assignments enable easier access reviews.",
       "Remove direct user RBAC assignments; use security groups with roles assigned to groups.",
       cis=None, nist=["AC-2", "AC-3"],
       mitre_tactics=["Privilege Escalation"], mitre_techniques=["T1078"],
       threat_category="iam_misconfiguration"),
    _r("azure_rbac_no_subscription_owner_without_pim", "authorization", "User", "high",
       "Ensure subscription Owner role requires PIM activation (not permanent)",
       "Permanent subscription Owner assignments are a persistent privilege escalation path.",
       "Convert permanent Owner role assignments to PIM-eligible assignments.",
       cis="1.23", nist=["AC-6", "AC-2"],
       mitre_tactics=["Privilege Escalation"], mitre_techniques=["T1078.004"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_conditional_access_require_mfa", "iam", "User", "critical",
       "Ensure Conditional Access policy requires MFA for all users",
       "Conditional Access MFA policy is the primary defence against password compromise.",
       "Create CA policy: All users → Require MFA → All cloud apps.",
       cis="1.2", nist=["IA-2"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1078"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_conditional_access_block_legacy_auth", "iam", "User", "high",
       "Ensure Conditional Access policy blocks legacy authentication",
       "Legacy auth bypasses MFA and CA policies. A dedicated block policy is required.",
       "Create CA policy: All users → Block → Client apps: Exchange ActiveSync, Legacy auth clients.",
       cis="1.22", nist=["IA-2", "CM-7"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1110"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_no_orphaned_service_principals", "authorization", "ServicePrincipal", "medium",
       "Ensure no orphaned service principals exist without associated app registrations",
       "Orphaned service principals may have role assignments that grant unintended access.",
       "Audit and remove service principals without associated app registrations.",
       cis=None, nist=["AC-2"],
       mitre_tactics=["Persistence"], mitre_techniques=["T1136"],
       threat_category="iam_misconfiguration"),
    _r("azure_sp_certificate_preferred_over_secret", "authorization", "ServicePrincipal", "medium",
       "Ensure service principal authentication uses certificates over client secrets",
       "Certificates are more secure than client secrets as they cannot be easily exfiltrated via secret leak.",
       "Rotate service principal client secrets to certificate credentials where possible.",
       cis=None, nist=["IA-5"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1552"],
       threat_category="iam_misconfiguration"),
    _r("azure_sp_no_expired_credentials", "authorization", "ServicePrincipal", "high",
       "Ensure no service principals have expired credentials still associated",
       "Expired credentials indicate poor lifecycle management and may still be usable in some configurations.",
       "Remove expired credentials from all service principals.",
       cis=None, nist=["IA-5"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1552"],
       threat_category="iam_misconfiguration"),
    _r("azure_iam_app_registration_credential_expiry", "iam", "ServicePrincipal", "medium",
       "Ensure app registration credentials have expiry dates set",
       "App registration credentials (secrets and certificates) without expiry persist indefinitely.",
       "Set expiry dates on all app registration secrets and certificates.",
       cis=None, nist=["IA-5"],
       mitre_tactics=["Persistence"], mitre_techniques=["T1098.001"],
       threat_category="iam_misconfiguration"),
]

# ── AKS (Azure Kubernetes Service) ───────────────────────────────────────────

AKS_RULES = [
    _r("azure_aks_rbac_enabled", "containerservice", "AKSCluster", "high",
       "Ensure RBAC is enabled for AKS cluster",
       "RBAC is essential for controlling access to the Kubernetes API and cluster resources.",
       "AKS → Settings → Configuration → RBAC: Enabled (required at cluster creation).",
       cis=None, nist=["AC-3", "AC-6"],
       mitre_tactics=["Privilege Escalation"], mitre_techniques=["T1613"],
       threat_category="iam_misconfiguration"),
    _r("azure_aks_aad_integration_enabled", "containerservice", "AKSCluster", "high",
       "Ensure AKS cluster has Azure Active Directory integration enabled",
       "AAD integration enables RBAC policies based on Azure AD groups and users.",
       "Enable AAD integration at cluster creation or migrate to managed AAD.",
       cis=None, nist=["IA-2", "AC-3"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="iam_misconfiguration"),
    _r("azure_aks_network_policy_calico_or_azure", "containerservice", "AKSCluster", "high",
       "Ensure AKS cluster has a network policy configured (Calico or Azure)",
       "Network policies control Pod-to-Pod traffic, preventing lateral movement within the cluster.",
       "Configure network policy at cluster creation. Enable Calico or Azure network policy.",
       cis=None, nist=["SC-7"],
       mitre_tactics=["Lateral Movement"], mitre_techniques=["T1021"],
       threat_category="network_exposure"),
    _r("azure_aks_private_cluster", "containerservice", "AKSCluster", "high",
       "Ensure AKS cluster API server is not publicly accessible",
       "A public API server exposes the cluster control plane to the internet.",
       "Create private AKS cluster with --enable-private-cluster or use authorized IP ranges.",
       cis=None, nist=["SC-7", "AC-3"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="network_exposure"),
    _r("azure_aks_authorized_ip_ranges", "containerservice", "AKSCluster", "high",
       "Ensure AKS API server has authorized IP ranges configured",
       "Limiting API server access to specific IP ranges reduces the attack surface.",
       "AKS → Settings → Networking → API server authorized IP ranges.",
       cis=None, nist=["SC-7"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="network_exposure"),
    _r("azure_aks_node_pool_managed_identity", "containerservice", "AKSCluster", "medium",
       "Ensure AKS node pools use managed identity (not service principal with credentials)",
       "Managed identities eliminate stored credential secrets and auto-rotate.",
       "Migrate AKS cluster to managed identity: az aks update --enable-managed-identity.",
       cis=None, nist=["IA-5"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1552"],
       threat_category="iam_misconfiguration"),
    _r("azure_aks_pod_identity_disabled_use_workload_identity", "containerservice", "AKSCluster", "medium",
       "Ensure AKS uses Azure Workload Identity (not legacy AAD pod identity)",
       "Workload Identity is the recommended replacement for pod identity and provides better security.",
       "Migrate from AAD Pod Identity to Azure Workload Identity using OIDC issuer.",
       cis=None, nist=["IA-5"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1552"],
       threat_category="iam_misconfiguration"),
    _r("azure_aks_no_privileged_containers", "containerservice", "AKSCluster", "critical",
       "Ensure AKS does not allow privileged containers",
       "Privileged containers have full access to the host, enabling container escape attacks.",
       "Apply Azure Policy to deny privileged pod spec or use Pod Security Admission.",
       cis=None, nist=["CM-7", "SI-7"],
       mitre_tactics=["Privilege Escalation"], mitre_techniques=["T1611"],
       threat_category="network_exposure"),
    _r("azure_aks_secrets_from_keyvault", "containerservice", "AKSCluster", "medium",
       "Ensure AKS workloads read secrets from Key Vault (not K8s Secrets or env vars)",
       "Kubernetes Secrets are base64-encoded and stored in etcd. Key Vault provides encryption and auditing.",
       "Use Azure Key Vault provider for Secrets Store CSI Driver.",
       cis=None, nist=["SC-28", "IA-5"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1552"],
       threat_category="data_exposure"),
    _r("azure_aks_node_os_patching", "containerservice", "AKSCluster", "high",
       "Ensure AKS node pools have automatic OS node image upgrades configured",
       "Outdated node OS images contain known vulnerabilities exploitable by attackers.",
       "Configure node OS upgrade channel: az aks update --node-os-upgrade-channel SecurityPatch.",
       cis=None, nist=["SI-2"],
       mitre_tactics=["Privilege Escalation"], mitre_techniques=["T1068"],
       threat_category="misconfiguration"),
    _r("azure_aks_cluster_monitoring_enabled", "containerservice", "AKSCluster", "medium",
       "Ensure AKS cluster monitoring with Azure Monitor is enabled",
       "Container Insights provides visibility into cluster performance, workload health, and security events.",
       "Enable Container Insights on the AKS cluster via Azure Monitor.",
       cis=None, nist=["AU-12", "SI-4"],
       mitre_tactics=["Defense Evasion"], mitre_techniques=["T1562"],
       threat_category="misconfiguration"),
    _r("azure_aks_etcd_encryption", "containerservice", "AKSCluster", "medium",
       "Ensure etcd data is encrypted at rest in AKS",
       "etcd contains cluster state including Kubernetes Secrets; encryption prevents exposure if storage is compromised.",
       "Enable etcd encryption with CMK at AKS cluster creation.",
       cis=None, nist=["SC-28"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1552"],
       threat_category="data_exposure"),
]

# ── APP SERVICE / FUNCTION APP ────────────────────────────────────────────────

APPSERVICE_RULES = [
    _r("azure_appservice_authentication_enabled", "web", "AppService", "high",
       "Ensure App Service Authentication (Easy Auth) is configured",
       "Without authentication, App Service endpoints are publicly accessible without identity verification.",
       "App Service → Authentication → Add an identity provider.",
       cis="8.1", nist=["IA-2", "AC-3"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="iam_misconfiguration"),
    _r("azure_appservice_latest_http_version", "web", "AppService", "low",
       "Ensure App Service is using the latest HTTP version",
       "Older HTTP versions lack performance improvements and may have security issues.",
       "App Service → Settings → Configuration → HTTP version → 2.0.",
       cis="8.2", nist=["CM-7"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
    _r("azure_appservice_https_only", "web", "AppService", "high",
       "Ensure App Service HTTPS-only is enabled",
       "Disabling HTTP redirect leaves traffic unencrypted, enabling credential interception.",
       "App Service → Settings → TLS/SSL settings → HTTPS Only → On.",
       cis="8.3", nist=["SC-8"],
       mitre_tactics=["Collection"], mitre_techniques=["T1040"],
       threat_category="network_exposure"),
    _r("azure_appservice_client_cert_required", "web", "AppService", "medium",
       "Ensure App Service requires incoming client certificates",
       "Client certificates provide mutual TLS authentication, preventing unauthenticated calls.",
       "App Service → Settings → TLS/SSL settings → Client certificate mode → Require.",
       cis="8.4", nist=["IA-2", "SC-17"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="iam_misconfiguration"),
    _r("azure_appservice_managed_identity", "web", "AppService", "medium",
       "Ensure App Service uses managed identity for authentication to Azure services",
       "Managed identity eliminates the need for credentials in application code.",
       "App Service → Settings → Identity → System assigned → On.",
       cis="8.5", nist=["IA-5"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1552"],
       threat_category="iam_misconfiguration"),
    _r("azure_appservice_tls_minimum_12", "web", "AppService", "high",
       "Ensure App Service minimum TLS version is 1.2",
       "TLS 1.0 and 1.1 are deprecated and have known vulnerabilities.",
       "App Service → Settings → TLS/SSL settings → Minimum Inbound TLS Version → 1.2.",
       cis="8.3", nist=["SC-8"],
       mitre_tactics=["Collection"], mitre_techniques=["T1040"],
       threat_category="network_exposure"),
    _r("azure_appservice_ftp_disabled", "web", "AppService", "medium",
       "Ensure FTP deployment is disabled for App Service",
       "FTP transfers credentials and data in plaintext. Use FTPS or Git deployment instead.",
       "App Service → Deployment → Deployment Center → Disable FTP.",
       cis=None, nist=["CM-7", "SC-8"],
       mitre_tactics=["Initial Access", "Credential Access"], mitre_techniques=["T1190", "T1552"],
       threat_category="network_exposure"),
    _r("azure_appservice_remote_debugging_disabled", "web", "AppService", "high",
       "Ensure remote debugging is disabled for App Service",
       "Remote debugging ports are network-accessible and can be exploited for code execution.",
       "App Service → Settings → Configuration → General settings → Remote debugging → Off.",
       cis=None, nist=["CM-7"],
       mitre_tactics=["Execution"], mitre_techniques=["T1059"],
       threat_category="network_exposure"),
    _r("azure_appservice_latest_php_version", "web", "AppService", "medium",
       "Ensure App Service is using the latest supported PHP version",
       "Outdated runtime versions contain known vulnerabilities.",
       "App Service → Settings → Configuration → General settings → PHP version → latest.",
       cis="8.6", nist=["SI-2"],
       mitre_tactics=["Privilege Escalation"], mitre_techniques=["T1068"],
       threat_category="misconfiguration"),
    _r("azure_appservice_latest_python_version", "web", "AppService", "medium",
       "Ensure App Service is using the latest supported Python version",
       "Outdated Python runtime versions may have known vulnerabilities.",
       "App Service → Configuration → General settings → Python version → latest.",
       cis="8.7", nist=["SI-2"],
       mitre_tactics=["Privilege Escalation"], mitre_techniques=["T1068"],
       threat_category="misconfiguration"),
    _r("azure_appservice_latest_java_version", "web", "AppService", "medium",
       "Ensure App Service is using the latest supported Java version",
       "Outdated Java runtime may have known vulnerabilities.",
       "App Service → Configuration → General settings → Java version → latest.",
       cis="8.8", nist=["SI-2"],
       mitre_tactics=["Privilege Escalation"], mitre_techniques=["T1068"],
       threat_category="misconfiguration"),
    _r("azure_appservice_vnet_integration", "web", "AppService", "medium",
       "Ensure App Service has VNet integration configured for outbound connections",
       "VNet integration routes outbound traffic through your VNet, enabling NSG and private endpoint connectivity.",
       "App Service → Settings → Networking → VNet integration.",
       cis=None, nist=["SC-7"],
       mitre_tactics=["Exfiltration"], mitre_techniques=["T1041"],
       threat_category="network_exposure"),
    _r("azure_appservice_access_restriction", "web", "AppService", "medium",
       "Ensure App Service has access restrictions configured",
       "Access restrictions limit which IP addresses or VNets can reach the App Service.",
       "App Service → Settings → Networking → Access restrictions → add allowed IPs/VNets.",
       cis=None, nist=["SC-7", "AC-3"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="network_exposure"),
    _r("azure_functionapp_authentication_enabled", "web", "FunctionApp", "high",
       "Ensure Function App authentication is enabled",
       "Unauthenticated function endpoints can be invoked by anyone.",
       "Function App → Authentication → Add identity provider.",
       cis="8.1", nist=["IA-2"],
       mitre_tactics=["Initial Access"], mitre_techniques=["T1190"],
       threat_category="iam_misconfiguration"),
    _r("azure_functionapp_https_only", "web", "FunctionApp", "high",
       "Ensure Function App HTTPS-only is enabled",
       "HTTP traffic to Function Apps exposes function keys and data.",
       "Function App → TLS/SSL → HTTPS Only → On.",
       cis="8.3", nist=["SC-8"],
       mitre_tactics=["Collection"], mitre_techniques=["T1040"],
       threat_category="network_exposure"),
    _r("azure_appservice_cors_no_wildcard", "web", "AppService", "medium",
       "Ensure App Service CORS policy does not allow wildcard (*) origin",
       "Wildcard CORS allows any website to make cross-origin requests to the app.",
       "App Service → API → CORS → remove * from allowed origins; specify trusted domains.",
       cis=None, nist=["CM-7"],
       mitre_tactics=["Initial Access", "Collection"], mitre_techniques=["T1190"],
       threat_category="network_exposure"),
]

# ── MONITORING / LOGGING ──────────────────────────────────────────────────────

MONITOR_RULES = [
    _r("azure_monitor_diagnostic_setting_subscription", "monitor", "DiagnosticSetting", "high",
       "Ensure a Diagnostic Setting exists for subscription-level activity logs",
       "Activity logs capture management plane events across all Azure services and are essential for detection.",
       "Create Diagnostic Setting at subscription scope → all categories → Log Analytics or Storage.",
       cis="5.1", nist=["AU-2", "AU-12"],
       mitre_tactics=["Defense Evasion"], mitre_techniques=["T1562"],
       threat_category="misconfiguration"),
    _r("azure_monitor_activity_log_administrative", "monitor", "DiagnosticSetting", "high",
       "Ensure Diagnostic Setting captures Administrative category",
       "Administrative logs capture resource creation, deletion, and modification events.",
       "Diagnostic Setting → Categories → enable Administrative.",
       cis="5.2", nist=["AU-2"],
       mitre_tactics=["Defense Evasion"], mitre_techniques=["T1562"],
       threat_category="misconfiguration"),
    _r("azure_monitor_activity_log_security", "monitor", "DiagnosticSetting", "high",
       "Ensure Diagnostic Setting captures Security category",
       "Security category logs capture Azure Security Center alerts and events.",
       "Diagnostic Setting → Categories → enable Security.",
       cis="5.2", nist=["AU-2"],
       mitre_tactics=["Defense Evasion"], mitre_techniques=["T1562"],
       threat_category="misconfiguration"),
    _r("azure_monitor_activity_log_policy", "monitor", "DiagnosticSetting", "medium",
       "Ensure Diagnostic Setting captures Policy category",
       "Policy logs capture policy evaluation events for compliance monitoring.",
       "Diagnostic Setting → Categories → enable Policy.",
       cis="5.2", nist=["AU-2"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
    _r("azure_monitor_log_storage_not_public", "monitor", "StorageAccount", "high",
       "Ensure the storage container storing activity logs is not publicly accessible",
       "Public log storage exposes audit trails to any internet user.",
       "Set storage account public access to disabled for the log storage account.",
       cis="5.3", nist=["AU-9"],
       mitre_tactics=["Collection"], mitre_techniques=["T1530"],
       threat_category="data_exposure"),
    _r("azure_monitor_log_storage_cmk", "monitor", "StorageAccount", "medium",
       "Ensure storage account for activity logs uses CMK encryption",
       "CMK encryption for log storage provides key management control over audit data.",
       "Configure CMK encryption on the storage account holding activity logs.",
       cis="5.4", nist=["AU-9", "SC-28"],
       mitre_tactics=["Collection"], mitre_techniques=["T1530"],
       threat_category="data_exposure"),
    _r("azure_monitor_keyvault_logging", "monitor", "DiagnosticSetting", "high",
       "Ensure diagnostic logging is enabled for Key Vault",
       "Key Vault audit logs capture all key, secret, and certificate operations.",
       "Key Vault → Diagnostic settings → AuditEvent → enable.",
       cis="5.5", nist=["AU-2", "AU-12"],
       mitre_tactics=["Credential Access"], mitre_techniques=["T1552"],
       threat_category="misconfiguration"),
    _r("azure_monitor_activity_log_retention_1year", "monitor", "DiagnosticSetting", "medium",
       "Ensure Activity Log retention period is 1 year or greater",
       "1-year retention satisfies most compliance requirements and supports long-term forensic investigation.",
       "Diagnostic Setting → Storage account retention → 365 days.",
       cis="5.6", nist=["AU-11"],
       mitre_tactics=["Defense Evasion"], mitre_techniques=["T1562"],
       threat_category="misconfiguration"),
    _r("azure_monitor_alert_create_update_policy", "monitor", "AlertRule", "medium",
       "Ensure activity log alerts exist for Create/Update Policy events",
       "Alerts on policy changes detect unauthorized governance modifications.",
       "Create Activity Log Alert: Activity type = Administrative, Operation = Write, Resource = Policy assignments.",
       cis=None, nist=["AU-12", "SI-4"],
       mitre_tactics=["Defense Evasion"], mitre_techniques=["T1562"],
       threat_category="misconfiguration"),
    _r("azure_monitor_alert_delete_policy", "monitor", "AlertRule", "medium",
       "Ensure activity log alerts exist for Delete Policy events",
       "Policy deletion can disable compliance controls silently.",
       "Create Activity Log Alert for Policy assignment delete operations.",
       cis=None, nist=["AU-12", "SI-4"],
       mitre_tactics=["Defense Evasion"], mitre_techniques=["T1562"],
       threat_category="misconfiguration"),
    _r("azure_monitor_alert_nsg_changes", "monitor", "AlertRule", "medium",
       "Ensure activity log alerts exist for Network Security Group changes",
       "Unauthorized NSG changes can open attack paths.",
       "Create Activity Log Alert for NSG write/delete operations.",
       cis=None, nist=["AU-12", "SI-4"],
       mitre_tactics=["Defense Evasion"], mitre_techniques=["T1562"],
       threat_category="network_exposure"),
    _r("azure_monitor_alert_security_solution_changes", "monitor", "AlertRule", "medium",
       "Ensure activity log alerts exist for security solution changes",
       "Modifications to security solutions may indicate an attacker trying to disable defenses.",
       "Create Activity Log Alert for Security solution write/delete operations.",
       cis=None, nist=["SI-4", "AU-12"],
       mitre_tactics=["Defense Evasion"], mitre_techniques=["T1562"],
       threat_category="misconfiguration"),
    _r("azure_monitor_log_analytics_workspace", "monitor", "DiagnosticSetting", "medium",
       "Ensure diagnostic settings send logs to a Log Analytics workspace",
       "Log Analytics enables advanced query, alerting, and SIEM integration for security monitoring.",
       "Diagnostic setting → Destination → Send to Log Analytics workspace.",
       cis="5.1", nist=["AU-6", "SI-4"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
    _r("azure_monitor_vm_insights_enabled", "monitor", "DiagnosticSetting", "low",
       "Ensure VM Insights is enabled for Virtual Machines",
       "VM Insights provides health, performance, and dependency maps for VMs.",
       "Enable VM Insights via Azure Monitor → Virtual Machines → Enable.",
       cis=None, nist=["SI-4"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
    _r("azure_monitor_security_center_integration", "monitor", "DiagnosticSetting", "medium",
       "Ensure Microsoft Defender for Cloud data is collected via diagnostic settings",
       "Collecting Defender for Cloud data to Log Analytics enables advanced threat hunting.",
       "Enable continuous export in Defender for Cloud settings → Log Analytics.",
       cis="2.13", nist=["SI-4"],
       mitre_tactics=[], mitre_techniques=[], threat_category="misconfiguration"),
]

# ── ALL RULES ─────────────────────────────────────────────────────────────────

ALL_RULES = (
    STORAGE_RULES
    + NETWORK_RULES
    + COMPUTE_RULES
    + KEYVAULT_RULES
    + SQL_RULES
    + IAM_RULES
    + AKS_RULES
    + APPSERVICE_RULES
    + MONITOR_RULES
)

# ── Upsert ────────────────────────────────────────────────────────────────────

INSERT_SQL = """
    INSERT INTO rule_metadata (
        rule_id, service, provider, resource, severity,
        title, description, remediation,
        compliance_frameworks, mitre_tactics, mitre_techniques,
        threat_category, source, metadata_source, version,
        tenant_id, customer_id
    ) VALUES (
        %s, %s, %s, %s, %s,
        %s, %s, %s,
        %s, %s, %s,
        %s, %s, %s, %s,
        NULL, NULL
    )
    ON CONFLICT (rule_id, customer_id, tenant_id) DO UPDATE SET
        service             = EXCLUDED.service,
        provider            = EXCLUDED.provider,
        resource            = EXCLUDED.resource,
        severity            = EXCLUDED.severity,
        title               = EXCLUDED.title,
        description         = EXCLUDED.description,
        remediation         = EXCLUDED.remediation,
        compliance_frameworks = EXCLUDED.compliance_frameworks,
        mitre_tactics       = EXCLUDED.mitre_tactics,
        mitre_techniques    = EXCLUDED.mitre_techniques,
        threat_category     = EXCLUDED.threat_category,
        updated_at          = NOW()
"""


def seed() -> None:
    conn = _conn()
    inserted = 0
    updated = 0

    try:
        for r in ALL_RULES:
            with conn.cursor() as cur:
                cur.execute(
                    "SELECT id FROM rule_metadata WHERE rule_id=%s AND tenant_id IS NULL AND customer_id IS NULL",
                    (r["rule_id"],),
                )
                exists = cur.fetchone()

                cur.execute(INSERT_SQL, (
                    r["rule_id"], r["service"], "azure", r["resource"], r["severity"],
                    r["title"], r["description"], r["remediation"],
                    Json(r["compliance_frameworks"]),
                    Json(r["mitre_tactics"]),
                    Json(r["mitre_techniques"]),
                    r["threat_category"], "azure_cis_seed", "azure_cis_seed", "1.0",
                ))
                if exists:
                    updated += 1
                else:
                    inserted += 1

            conn.commit()

        print(f"\nDone: {inserted} inserted, {updated} updated ({len(ALL_RULES)} total)")
        by_service = {}
        for r in ALL_RULES:
            by_service[r["service"]] = by_service.get(r["service"], 0) + 1
        for svc, cnt in sorted(by_service.items()):
            print(f"  {svc:20s}: {cnt}")

    finally:
        conn.close()


if __name__ == "__main__":
    print(f"Seeding {len(ALL_RULES)} Azure check rules into rule_metadata ...")
    seed()
