#!/usr/bin/env python3
"""
Generate step4_fields_produced_index.json for OCI, IBM, and AliCloud.

GCP/AWS/Azure already have step4 generated by their respective pipelines.
This script fills the gap for CSPs that have output_fields in step2
but no step4 file yet.

Sources per CSP:
  OCI:      step2.operations[*].output_fields  {field: {type, path, entity}}
  AliCloud: step2.operations[*].output_fields  {field: {type, path, entity}}
  IBM:      ibm_dependencies_with_python_names_fully_enriched.json
              → op.item_fields (per-item fields) + op.main_output_field

Step4 format (GCP-compatible, used by step6 generators):
  {
    "csp": "oci",
    "service": "access_governance_cp",
    "generated_at": "...",
    "total_fields": N,
    "fields": {
      "field_name": {
        "field_path": "field_name",          // flat for get ops
        "field_path": "items[].field_name",  // with [] for list-op items
        "producers": [
          {"op": "op_key", "kind": "...", "independent": bool, "produces_type": "string"}
        ],
        "preferred": {"strategy": "independent_first", "op": "..."}
      }
    }
  }

The step6 generators use _load_step4_op_fields() which inverts this to:
  {op_key: [field_path, ...]}

Usage:
    python3 data_pythonsdk/scripts/generate_step4_for_csp.py --csp oci
    python3 data_pythonsdk/scripts/generate_step4_for_csp.py --csp alicloud
    python3 data_pythonsdk/scripts/generate_step4_for_csp.py --csp ibm
    python3 data_pythonsdk/scripts/generate_step4_for_csp.py --csp all
    python3 data_pythonsdk/scripts/generate_step4_for_csp.py --csp oci --dry-run
"""

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

SDK_ROOT = Path(__file__).parent.parent  # data_pythonsdk/

# Fields to skip — pagination, metadata, not CSPM-relevant
SKIP_FIELDS = {
    "next_token", "next_url", "nextPage", "nextPageToken", "nextToken",
    "pageToken", "pageInfo", "offset", "limit", "total_count", "total",
    "opc_next_page", "opc_request_id",
    # IBM specific
    "next", "previous", "first", "last", "start",
}

READ_KINDS = {"read_list", "read_get"}


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _is_id_field(field_name: str, entity: str = "") -> bool:
    """Heuristic: is this field an identifier?"""
    low = field_name.lower()
    return (low in ("id", "ocid", "crn", "arn", "name", "resource_id", "instance_id")
            or low.endswith("_id") or low.endswith("_ocid") or low.endswith("_crn")
            or "ocid" in entity.lower())


def _preferred_producer(producers: list[dict]) -> dict:
    """Pick best producer: prefer independent, then read_list, then read_get."""
    ind = [p for p in producers if p.get("independent")]
    if ind:
        return {"strategy": "independent_first", "op": ind[0]["op"]}
    return {"strategy": "any", "op": producers[0]["op"] if producers else ""}


# ── OCI / AliCloud: use step2 output_fields ──────────────────────────────────

def build_step4_from_step2(svc_dir: Path, csp: str) -> dict | None:
    """
    Build step4 for OCI or AliCloud from step2.operations[*].output_fields.

    output_fields format: {field_name: {type, path, entity}}

    Field path notation:
      read_list ops: "items[].field_name"  (items are per-element)
      read_get  ops: "field_name"          (response IS the item)
    """
    step2_path = svc_dir / "step2_read_operation_registry.json"
    if not step2_path.exists():
        return None
    with open(step2_path) as f:
        s2 = json.load(f)

    service = s2.get("service", svc_dir.name)
    ops = {k: v for k, v in s2.get("operations", {}).items()
           if v.get("kind", "") in READ_KINDS}
    if not ops:
        return None

    # Build: field_path → [{producer_info}]
    field_producers: dict[str, list[dict]] = {}

    for op_key, op in ops.items():
        kind        = op.get("kind", "read_get")
        independent = op.get("independent", False)
        out_fields  = op.get("output_fields", {})

        if not out_fields:
            continue

        for field_name, field_meta in out_fields.items():
            if field_name in SKIP_FIELDS:
                continue

            # Determine the field_path notation
            if kind == "read_list":
                field_path = f"items[].{field_name}"
            else:
                field_path = field_name

            produces_type = field_meta.get("type", "string") if isinstance(field_meta, dict) else "string"
            entity        = field_meta.get("entity", "") if isinstance(field_meta, dict) else ""

            producer = {
                "op":           op_key,
                "kind":         kind,
                "independent":  independent,
                "produces_type": produces_type,
                "is_id":        _is_id_field(field_name, entity),
            }
            field_producers.setdefault(field_path, []).append(producer)

    if not field_producers:
        return None

    fields_out = {}
    for field_path, producers in sorted(field_producers.items()):
        fields_out[field_path] = {
            "field_path": field_path,
            "producers":  producers,
            "preferred":  _preferred_producer(producers),
        }

    return {
        "csp":          csp,
        "service":      service,
        "generated_at": _now(),
        "total_fields": len(fields_out),
        "fields":       fields_out,
    }


# ── IBM: use ibm_dependencies item_fields ────────────────────────────────────

def build_step4_ibm(svc_dir: Path) -> dict | None:
    """
    Build step4 for IBM from ibm_dependencies_with_python_names_fully_enriched.json.

    The dependencies file has per-op:
      - item_fields: {field_name: {type, description, compliance_category}}
        → per-item fields from the collection (read_list ops)
      - main_output_field: "items"  → collection key in response
      - output_fields: top-level response fields (items, next_token) → skip pagination

    For read_get ops that have output_fields (not item_fields), use those directly.
    """
    dep_path = svc_dir / "ibm_dependencies_with_python_names_fully_enriched.json"
    s2_path  = svc_dir / "step2_read_operation_registry.json"

    if not dep_path.exists() and not s2_path.exists():
        return None

    # Load step2 to get kind and independent flags
    s2_ops: dict = {}
    if s2_path.exists():
        with open(s2_path) as f:
            s2 = json.load(f)
        s2_ops = {
            v.get("operation", k): {"kind": v.get("kind", ""), "independent": v.get("independent", False)}
            for k, v in s2.get("operations", {}).items()
        }
        service = s2.get("service", svc_dir.name)
    else:
        service = svc_dir.name

    if not dep_path.exists():
        return None

    with open(dep_path) as f:
        raw = json.load(f)

    # Unwrap nested format: {service_name: {independent: [...], dependent: [...]}}
    content = raw
    for k, v in raw.items():
        if isinstance(v, dict) and ("independent" in v or "dependent" in v):
            content = v
            service = v.get("service", service)
            break

    field_producers: dict[str, list[dict]] = {}

    for bucket in ("independent", "dependent"):
        for op in content.get(bucket, []):
            op_name = op.get("operation", "")
            if not op_name:
                continue

            s2_meta     = s2_ops.get(op_name, {})
            kind        = s2_meta.get("kind") or ("read_list" if op_name.lower().startswith("list") else "read_get")
            independent = s2_meta.get("independent", bucket == "independent")

            if kind not in READ_KINDS:
                continue

            # Per-item fields from item_fields (for list ops)
            item_fields = op.get("item_fields", {})
            if item_fields and isinstance(item_fields, dict):
                for field_name, field_meta in item_fields.items():
                    if field_name in SKIP_FIELDS:
                        continue
                    field_path    = f"items[].{field_name}"
                    produces_type = field_meta.get("type", "string") if isinstance(field_meta, dict) else "string"
                    producer = {
                        "op":           f"ibm.{service}.{op_name}",
                        "kind":         kind,
                        "independent":  independent,
                        "produces_type": produces_type,
                        "is_id":        _is_id_field(field_name),
                    }
                    field_producers.setdefault(field_path, []).append(producer)

            # For get ops, use output_fields if no item_fields
            elif kind == "read_get":
                out_fields = op.get("output_fields", {})
                for field_name, field_meta in out_fields.items():
                    if field_name in SKIP_FIELDS:
                        continue
                    field_path    = field_name
                    produces_type = field_meta.get("type", "string") if isinstance(field_meta, dict) else "string"
                    producer = {
                        "op":           f"ibm.{service}.{op_name}",
                        "kind":         kind,
                        "independent":  independent,
                        "produces_type": produces_type,
                        "is_id":        _is_id_field(field_name),
                    }
                    field_producers.setdefault(field_path, []).append(producer)

    if not field_producers:
        return None

    fields_out = {}
    for field_path, producers in sorted(field_producers.items()):
        fields_out[field_path] = {
            "field_path": field_path,
            "producers":  producers,
            "preferred":  _preferred_producer(producers),
        }

    return {
        "csp":          "ibm",
        "service":      service,
        "generated_at": _now(),
        "total_fields": len(fields_out),
        "fields":       fields_out,
    }


# ── Runner ────────────────────────────────────────────────────────────────────

CSP_CONFIGS = {
    "oci":      {"builder": "step2", "csp": "oci"},
    "alicloud": {"builder": "step2", "csp": "alicloud"},
    "ibm":      {"builder": "ibm",   "csp": "ibm"},
}


def process_csp(csp: str, dry_run: bool) -> tuple[int, int]:
    """Returns (written, skipped) counts."""
    cfg     = CSP_CONFIGS[csp]
    csp_dir = SDK_ROOT / csp
    if not csp_dir.exists():
        print(f"  {csp}: directory not found — skipping")
        return 0, 0

    SKIP = {"tools", "__pycache__", "temp_code"}
    svc_dirs = sorted(d for d in csp_dir.iterdir() if d.is_dir() and d.name not in SKIP)

    written = skipped = 0
    for svc_dir in svc_dirs:
        if cfg["builder"] == "ibm":
            step4 = build_step4_ibm(svc_dir)
        else:
            step4 = build_step4_from_step2(svc_dir, cfg["csp"])

        if not step4:
            skipped += 1
            continue

        out_path = svc_dir / "step4_fields_produced_index.json"
        action = "Would write" if dry_run else "Written   "
        n_fields = step4["total_fields"]
        print(f"    {svc_dir.name:<40} {action}: {n_fields} fields")
        if not dry_run:
            out_path.write_text(json.dumps(step4, indent=2))
        written += 1

    return written, skipped


def main():
    parser = argparse.ArgumentParser(
        description="Generate step4_fields_produced_index.json for OCI/IBM/AliCloud"
    )
    parser.add_argument("--csp", required=True,
                        choices=["oci", "alicloud", "ibm", "all"],
                        help="CSP to process (or 'all')")
    parser.add_argument("--dry-run", action="store_true",
                        help="Report without writing files")
    args = parser.parse_args()

    csps = list(CSP_CONFIGS.keys()) if args.csp == "all" else [args.csp]
    mode = "DRY RUN" if args.dry_run else "WRITING"
    print(f"step4 generation ({mode}) for: {', '.join(csps)}")
    print()

    for csp in csps:
        print(f"  [{csp.upper()}]")
        written, skipped = process_csp(csp, args.dry_run)
        print(f"  → {written} written, {skipped} skipped")
        print()

    print("Done.")


if __name__ == "__main__":
    main()
