version: '1.0'
rule_id: k8s.persistentvolume.persistentvolume.pv_access_modes_restricted_enabled
for_each: k8s.persistentvolume.persistentvolume.list
severity: HIGH
conditions:
  all:
  - var: item.spec.accessModes[]
    op: in
    value:
    - ReadWriteOnce
    - ReadOnlyMany
  - var: item.spec.accessModes[]
    op: not_in
    value:
    - ReadWriteMany
