rule_id: azure.monitoring.virtual_machines.configure_linux_virtual_machines_to_run_azure_monitor_agent_with_systemassigned_
service: monitoring
resource: virtual_machines
title: Configure Linux virtual machines to run Azure Monitor Agent with system-assigned
  managed identity-based authentication
description: 'Automate the deployment of Azure Monitor Agent extension on your Linux
  virtual machines for collecting telemetry data from the guest OS. This policy will
  install the extension if the OS and region are supported and system-assigned managed
  identity is enabled, and skip install otherwise. Learn more: https://aka.ms/AMAOverview.'
domain: logging_monitoring_and_alerting
severity: medium
scope: monitoring.virtual_machines
assertion_id: monitoring.configure_linux_virtual_machines_to_run_azure_monitor_agent_with_systemassigned_
effect: DeployIfNotExists
resource_type: Microsoft.Compute/virtualMachines
policy_id: a4034bc6-ae50-406d-bf76-50f4ee5a7811
source: azure_policy_builtin
mitre_techniques:
- T1562.008
mitre_tactics:
- defense-evasion
threat_tags:
- logging-disabled
threat_category: defense_evasion
