"""
Orchestration Client - Interface to scan_orchestration table in shared database.

This module provides functions to:
1. Retrieve scan context (provider, hierarchy, services, regions, etc.) by orchestration_id
2. Update engine-specific scan IDs back to the scan_orchestration table

The orchestration_id is generated by the scheduler and serves as the pipeline-wide
identifier for a complete scan workflow across all engines.

Self-Service Pattern:
- Engines receive ONLY orchestration_id in their API requests
- Engines call get_scan_context(orchestration_id) to hydrate all parameters
- After completion, engines call update_engine_scan_id() to record their scan_id
"""

import logging
from typing import Dict, Optional, Any
import psycopg2
from psycopg2.extras import RealDictCursor

logger = logging.getLogger(__name__)


def _get_onboarding_db_connection():
    """
    Get connection to the onboarding database containing scan_orchestration table.
    
    MOVED: scan_orchestration table moved from threat_engine_shared to threat_engine_onboarding
    for better data locality and simpler architecture.
    """
    try:
        from .config.database_config import get_onboarding_config

        config = get_onboarding_config()
        conn = psycopg2.connect(
            host=config.host,
            port=config.port,
            database=config.database,
            user=config.username,
            password=config.password,
            connect_timeout=10
        )
        return conn
    except Exception as e:
        logger.error(f"Failed to connect to onboarding database: {e}")
        raise


def get_scan_context(orchestration_id: str) -> Optional[Dict[str, Any]]:
    """
    Retrieve scan context from scan_orchestration table by orchestration_id.

    Self-Service Pattern: Engines call this to hydrate all scan parameters.

    Args:
        orchestration_id: The pipeline-wide orchestration UUID

    Returns:
        Dict containing:
            - customer_id: Customer identifier
            - tenant_id: Tenant identifier
            - provider: Cloud service provider (aws, azure, gcp, oci, alicloud, ibm, k8s)
            - hierarchy_id: Hierarchy/account/subscription identifier
            - account_id: Cloud account identifier
            - credential_type: Authentication method ('iam_role' or 'access_key')
            - credential_ref: IAM role ARN or Secrets Manager path
            - include_services: List of services to scan (JSONB array) - null = all
            - include_regions: List of regions to scan (JSONB array) - null = all
            - exclude_services: List of services to exclude (JSONB array) - null = none
            - exclude_regions: List of regions to exclude (JSONB array) - null = none
            - execution_id: Links to executions table (scheduler)
            - schedule_id: Links to schedules table
            - discovery_scan_id, check_scan_id, etc. - previous engine results
            - Other orchestration metadata

        None if orchestration_id not found or error occurs

    Example:
        >>> ctx = get_scan_context("550e8400-e29b-41d4-a716-446655440000")
        >>> ctx['provider']
        'aws'
        >>> ctx['include_services']  # None = scan all services
        None
        >>> ctx['include_regions']
        ['ap-south-1']
    """
    if not orchestration_id:
        logger.warning("get_scan_context called with empty orchestration_id")
        return None

    conn = None
    try:
        conn = _get_onboarding_db_connection()

        with conn.cursor(cursor_factory=RealDictCursor) as cursor:
            query = """
                SELECT
                    orchestration_id,
                    execution_id,
                    schedule_id,
                    tenant_id,
                    customer_id,
                    provider,
                    hierarchy_id,
                    account_id,
                    credential_type,
                    credential_ref,
                    include_services,
                    include_regions,
                    exclude_services,
                    exclude_regions,
                    discovery_scan_id,
                    check_scan_id,
                    inventory_scan_id,
                    threat_scan_id,
                    compliance_scan_id,
                    iam_scan_id,
                    datasec_scan_id,
                    engines_requested,
                    overall_status,
                    created_at,
                    started_at,
                    completed_at
                FROM scan_orchestration
                WHERE orchestration_id = %s
            """
            cursor.execute(query, (orchestration_id,))
            row = cursor.fetchone()

            if row:
                logger.info(
                    f"Retrieved scan context for orchestration_id={orchestration_id}",
                    extra={"extra_fields": {
                        "provider": row.get("provider"),
                        "hierarchy_id": row.get("hierarchy_id")
                    }}
                )
                return dict(row)
            else:
                logger.warning(f"No scan context found for orchestration_id={orchestration_id}")
                return None

    except Exception as e:
        logger.error(
            f"Failed to retrieve scan context for orchestration_id={orchestration_id}: {e}",
            exc_info=True
        )
        return None
    finally:
        if conn:
            conn.close()


def update_engine_scan_id(
    orchestration_id: str,
    engine: str,
    scan_id: str
) -> bool:
    """
    Update engine-specific scan_id in scan_orchestration table.

    This is called by each engine after it generates its scan_id to write it back
    to the scan_orchestration table for tracking and cross-engine reference.

    Args:
        orchestration_id: The pipeline-wide orchestration UUID
        engine: Engine name (discovery, check, inventory, threat, compliance, iam, datasec)
        scan_id: The engine-specific scan UUID to record

    Returns:
        True if update succeeded, False otherwise

    Example:
        >>> update_engine_scan_id(
        ...     "550e8400-e29b-41d4-a716-446655440000",
        ...     "discovery",
        ...     "660e8400-e29b-41d4-a716-446655440111"
        ... )
        True
    """
    if not orchestration_id or not engine or not scan_id:
        logger.warning(
            "update_engine_scan_id called with missing parameters: "
            f"orchestration_id={orchestration_id}, engine={engine}, scan_id={scan_id}"
        )
        return False

    # Map engine names to their column names in scan_orchestration
    engine_column_map = {
        "discovery": "discovery_scan_id",
        "check": "check_scan_id",
        "inventory": "inventory_scan_id",
        "threat": "threat_scan_id",
        "compliance": "compliance_scan_id",
        "iam": "iam_scan_id",
        "datasec": "datasec_scan_id",
    }

    column_name = engine_column_map.get(engine)
    if not column_name:
        logger.error(
            f"Invalid engine name '{engine}'. Valid engines: {list(engine_column_map.keys())}"
        )
        return False

    conn = None
    try:
        conn = _get_onboarding_db_connection()

        with conn.cursor() as cursor:
            # Some deployments don't have updated_at on scan_orchestration (live RDS schema).
            # Try updating updated_at if it exists, otherwise fall back to just scan_id.
            cursor.execute(
                """
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = 'scan_orchestration'
                  AND column_name = 'updated_at'
                LIMIT 1
                """
            )
            has_updated_at = cursor.fetchone() is not None

            if has_updated_at:
                query = f"""
                    UPDATE scan_orchestration
                    SET {column_name} = %s,
                        updated_at = NOW()
                    WHERE orchestration_id = %s
                """
                cursor.execute(query, (scan_id, orchestration_id))
            else:
                query = f"""
                    UPDATE scan_orchestration
                    SET {column_name} = %s
                    WHERE orchestration_id = %s
                """
                cursor.execute(query, (scan_id, orchestration_id))

            if cursor.rowcount == 0:
                logger.warning(
                    f"No rows updated for orchestration_id={orchestration_id}. "
                    "Orchestration may not exist."
                )
                conn.rollback()
                return False

            conn.commit()
            logger.info(
                f"Updated {column_name}={scan_id} for orchestration_id={orchestration_id}",
                extra={"extra_fields": {
                    "orchestration_id": orchestration_id,
                    "engine": engine,
                    "scan_id": scan_id
                }}
            )
            return True

    except Exception as e:
        logger.error(
            f"Failed to update {column_name} for orchestration_id={orchestration_id}: {e}",
            exc_info=True
        )
        if conn:
            conn.rollback()
        return False
    finally:
        if conn:
            conn.close()


def get_engine_scan_id(orchestration_id: str, engine: str) -> Optional[str]:
    """
    Retrieve a specific engine's scan_id from scan_orchestration table.

    This allows one engine to look up another engine's scan_id within the same
    orchestration pipeline (e.g., check engine looking up discovery_scan_id).

    Args:
        orchestration_id: The pipeline-wide orchestration UUID
        engine: Engine name (discovery, check, inventory, threat, compliance, iam, datasec)

    Returns:
        The engine's scan_id if found, None otherwise

    Example:
        >>> discovery_id = get_engine_scan_id(
        ...     "550e8400-e29b-41d4-a716-446655440000",
        ...     "discovery"
        ... )
        >>> discovery_id
        '660e8400-e29b-41d4-a716-446655440111'
    """
    if not orchestration_id or not engine:
        logger.warning(
            f"get_engine_scan_id called with missing parameters: "
            f"orchestration_id={orchestration_id}, engine={engine}"
        )
        return None

    # Map engine names to their column names
    engine_column_map = {
        "discovery": "discovery_scan_id",
        "check": "check_scan_id",
        "inventory": "inventory_scan_id",
        "threat": "threat_scan_id",
        "compliance": "compliance_scan_id",
        "iam": "iam_scan_id",
        "datasec": "datasec_scan_id",
    }

    column_name = engine_column_map.get(engine)
    if not column_name:
        logger.error(
            f"Invalid engine name '{engine}'. Valid engines: {list(engine_column_map.keys())}"
        )
        return None

    conn = None
    try:
        conn = _get_onboarding_db_connection()

        with conn.cursor() as cursor:
            query = f"""
                SELECT {column_name}
                FROM scan_orchestration
                WHERE orchestration_id = %s
            """
            cursor.execute(query, (orchestration_id,))
            row = cursor.fetchone()

            if row and row[0]:
                return row[0]
            else:
                logger.debug(
                    f"No {column_name} found for orchestration_id={orchestration_id}"
                )
                return None

    except Exception as e:
        logger.error(
            f"Failed to retrieve {column_name} for orchestration_id={orchestration_id}: {e}",
            exc_info=True
        )
        return None
    finally:
        if conn:
            conn.close()
