rule_id: azure.machine_learning.resource.preview_configure_allowed_python_packages_for_specified_azure_machine_learning_c
service: machine_learning
resource: resource
title: '[Preview]: Configure allowed Python packages for specified Azure Machine Learning computes'
description: Provide allowed Python packages in specified Azure Machine Learning computes and can be assigned at the workspace.
  For more information, visit https://aka.ms/amlpolicydoc.
domain: ai_ml_and_model_security
severity: medium
scope: machine_learning.resource
assertion_id: machine_learning.preview_configure_allowed_python_packages_for_specified_azure_machine_learning_c
effect: enforceSetting
resource_type: ''
policy_id: 77eeea86-7e81-4a7d-9067-de844d096752
source: azure_policy_builtin
