version: '1.0'
rule_id: aws.iam.samlprovider.assertion_lifetime_configured
for_each: aws.iam.get_account_authorization_details
severity: MEDIUM
conditions:
  var: item.SAMLProviderList[].ValidUntil
  op: exists
