version: '1.0'
rule_id: azure.defender.vm.os.updates.configured
for_each: azure.compute.list_virtual_machines
severity: MEDIUM
conditions:
  var: item.properties.osProfile.linuxConfiguration.patchSettings.patchMode
  op: equals
  value: AutomaticByPlatform
