version: '1.0'
rule_id: aws.config.deliverychannel.destination_access_least_privilege
for_each: aws.config.describe_configuration_recorders
severity: HIGH
conditions:
  var: item.roleARN
  op: exists
