version: '1.0'
rule_id: aws.ec2.autoscalinggroup.uses_approved_launch_template_configured
for_each: aws.ec2.describe_auto_scaling_groups
severity: MEDIUM
conditions:
  var: item.LaunchTemplate.LaunchTemplateId
  op: exists
