version: '1.0'
rule_id: aws.ec2.group.cifs_unrestricted_access_configured
for_each: aws.ec2.describe_security_groups
severity: MEDIUM
conditions:
  all:
  - var: item.IpPermissions[].IpRanges[].CidrIp
    op: not_contains
    value: 0.0.0.0/0
  - var: item.IpPermissions[].FromPort
    op: equals
    value: 445
  - var: item.IpPermissions[].ToPort
    op: equals
    value: 445
  - var: item.IpPermissions[].IpProtocol
    op: equals
    value: tcp
fixture_validated: false
fixture_note: 'PASS fixture returned FAIL — wrong field or operator (pass_fixture keys: [''Description'', ''GroupId'', ''GroupName'',
  ''IpPermissions'', ''IpPermissionsEgress'', ''SecurityGroupArn'', ''Tags'', ''VpcId''])'
