version: '1.0'
rule_id: aws.ec2.subnet.public_subnets_use_nacl_restrictions_configured
for_each: aws.ec2.describe_carrier_gateways
severity: HIGH
conditions:
  var: item.CarrierGateways
  op: not_empty
