version: '1.0'
rule_id: aws.lambda.function.environment_variables_kms_encryption_enabled
for_each: aws.lambda.get_function
severity: HIGH
conditions:
  all:
  - var: item.Environment
    op: exists
  - var: item.KMSKeyArn
    op: exists
