version: '1.0'
rule_id: aws.kinesisanalytics.application.network_private_only_configured
for_each: aws.kinesisanalytics.describe_application
severity: HIGH
conditions:
  var: item.ApplicationConfigurationDescription.VpcConfigurationDescriptions
  op: not_empty
