rule_id: azure.azure_arc.private_link_scopes.configure_azure_arc_private_link_scopes_to_disable_public_network_access
service: azure_arc
resource: private_link_scopes
title: Configure Azure Arc Private Link Scopes to disable public network access
description: 'Disable public network access for your Azure Arc Private Link Scope
  so that associated Azure Arc resources cannot connect to Azure Arc services over
  the public internet. This can reduce data leakage risks. Learn more at: https://aka.ms/arc/privatelink.'
domain: configuration_and_change_management
severity: medium
scope: azure_arc.private_link_scopes
assertion_id: azure_arc.configure_azure_arc_private_link_scopes_to_disable_public_network_access
effect: Modify
resource_type: Microsoft.HybridCompute/privateLinkScopes
policy_id: de0bc8ea-76e2-4fe2-a288-a07556d0e9c4
source: azure_policy_builtin
mitre_techniques:
- T1190
mitre_tactics:
- initial-access
threat_tags:
- cloud-exposure
threat_category: initial_access
