rule_id: azure.search.search_services.configure_azure_ai_search_services_with_private_endpoints
service: search
resource: search_services
title: Configure Azure AI Search services with private endpoints
description: 'Private endpoints connect your virtual network to Azure services without a public IP address at the source or
  destination.  By mapping private endpoints to your Azure AI Search service, you can reduce data leakage risks.  Learn more
  at: https://aka.ms/azure-cognitive-search/inbound-private-endpoints.'
domain: configuration_and_change_management
severity: medium
scope: search.search_services
assertion_id: search.configure_azure_ai_search_services_with_private_endpoints
effect: DeployIfNotExists
resource_type: Microsoft.Search/searchServices
policy_id: b698b005-b660-4837-b833-a7aaab26ddba
source: azure_policy_builtin
