version: '1.0'
rule_id: oci.analytics.analytics_instance.api_security_monitoring_access_log_sink_configured_restricted
for_each: oci.analytics.list_analytics_instances
severity: MEDIUM
conditions:
  all:
  - var: item.status
    op: equals
    value: ACTIVE
  - var: item.freeform_tags
    op: exists
  - var: item.freeform_tags.Environment
    op: equals
    value: production
