version: '1.0'
rule_id: k8s.rbac.serviceaccount.management_review
for_each: k8s.rbac.list_cluster_role
severity: LOW
conditions:
  var: item.metadata.annotations.cspm.k8s.io/change-management-policy-configured
  op: exists
