version: '1.0'
rule_id: aws.elasticbeanstalk.application_version.elasticbeanstalk_artifact_encrypted
for_each: aws.elasticbeanstalk.describe_application_versions
severity: HIGH
conditions:
  var: item.SourceBundle.S3Bucket
  op: exists
