"""
Attack Path Engine — DB Writer.

Persists deduplicated paths, per-hop evidence, and history snapshots to:
  - attack_paths          (one row per path; upsert on path_id)
  - attack_path_nodes     (one row per hop per path; DELETE+INSERT)
  - attack_path_history   (INSERT ONLY — immutable history per scan)

Security notes:
  - All writes scoped by tenant_id from scan context.
  - scan_run_id present on every attack_paths row.
  - JSONB values use psycopg2.extras.Json() — NEVER json.dumps().
  - No json.loads() anywhere in this file.
  - attack_path_nodes.tenant_id always matches parent attack_paths.tenant_id.
"""

from __future__ import annotations

import logging
from typing import Any, List, Optional

import psycopg2
import psycopg2.extras

from ..models.attack_path import Path

logger = logging.getLogger("attack-path.writer")

_BATCH_SIZE = 500   # Insert nodes in batches to avoid huge single transactions


def write_paths(
    conn: Any,
    paths: List[Path],
    tenant_id: str,
    scan_run_id: str,
    account_id: Optional[str] = None,
    provider: Optional[str] = None,
) -> None:
    """Upsert attack_paths rows.

    first_seen_at is set on first INSERT and never updated on subsequent scans.
    All other mutable fields are updated on conflict.

    Args:
        conn:        psycopg2 connection (caller manages transaction).
        paths:       Deduplicated Path objects.
        tenant_id:   Tenant identifier from scan context.
        scan_run_id: Current pipeline run UUID.
        account_id:  Cloud account ID (optional).
        provider:    CSP identifier (optional).
    """
    if not paths:
        return

    current_path_ids = [p.path_id for p in paths]

    with conn.cursor() as cur:
        for p in paths:
            # Extract explanation fields (generated by path_explainer.py for top-50 paths;
            # None for lower-ranked paths — columns remain NULL in that case).
            expl = p.explanation or {}
            attack_name = expl.get("title") or None
            attack_story = expl.get("summary") or None
            technique_list = expl.get("mitre_techniques") or p.mitre_techniques or []
            attack_technique_chain = psycopg2.extras.Json(technique_list) if technique_list else None
            confidence_level = p.confidence_level or "speculative"

            cur.execute(
                """
                INSERT INTO attack_paths (
                    path_id, scan_run_id, tenant_id, account_id, provider,
                    node_uids, node_types, edge_types, hop_categories,
                    depth, entry_point_uid, entry_point_type,
                    crown_jewel_uid, crown_jewel_type, chain_type, data_classification,
                    path_score, probability_score, impact_score, severity,
                    max_epss, misconfig_count, threat_count, top_cves,
                    has_active_cdr_actor,
                    group_id, group_size, is_representative,
                    absorbed_count, choke_node_uid,
                    effective_access_principal, access_capability,
                    confidence_level, attack_name, attack_story, attack_technique_chain,
                    status, first_seen_at, last_seen_at, updated_at
                )
                VALUES (
                    %s, %s, %s, %s, %s,
                    %s, %s, %s, %s,
                    %s, %s, %s,
                    %s, %s, %s, %s,
                    %s, %s, %s, %s,
                    %s, %s, %s, %s,
                    %s,
                    %s, %s, %s,
                    %s, %s,
                    %s, %s,
                    %s, %s, %s, %s,
                    'active', NOW(), NOW(), NOW()
                )
                ON CONFLICT (path_id) DO UPDATE SET
                    scan_run_id                 = EXCLUDED.scan_run_id,
                    last_seen_at                = NOW(),
                    updated_at                  = NOW(),
                    path_score                  = EXCLUDED.path_score,
                    probability_score           = EXCLUDED.probability_score,
                    impact_score                = EXCLUDED.impact_score,
                    severity                    = EXCLUDED.severity,
                    status                      = 'active',
                    group_id                    = EXCLUDED.group_id,
                    group_size                  = EXCLUDED.group_size,
                    is_representative           = EXCLUDED.is_representative,
                    absorbed_count              = EXCLUDED.absorbed_count,
                    choke_node_uid              = EXCLUDED.choke_node_uid,
                    effective_access_principal  = EXCLUDED.effective_access_principal,
                    access_capability           = EXCLUDED.access_capability,
                    misconfig_count             = EXCLUDED.misconfig_count,
                    threat_count                = EXCLUDED.threat_count,
                    has_active_cdr_actor        = EXCLUDED.has_active_cdr_actor,
                    max_epss                    = EXCLUDED.max_epss,
                    crown_jewel_uid             = EXCLUDED.crown_jewel_uid,
                    crown_jewel_type            = EXCLUDED.crown_jewel_type,
                    chain_type                  = EXCLUDED.chain_type,
                    entry_point_uid             = EXCLUDED.entry_point_uid,
                    entry_point_type            = EXCLUDED.entry_point_type,
                    data_classification         = EXCLUDED.data_classification,
                    confidence_level            = EXCLUDED.confidence_level,
                    -- only overwrite narrative fields when a new explanation was generated
                    attack_name          = COALESCE(EXCLUDED.attack_name, attack_paths.attack_name),
                    attack_story         = COALESCE(EXCLUDED.attack_story, attack_paths.attack_story),
                    attack_technique_chain = COALESCE(EXCLUDED.attack_technique_chain, attack_paths.attack_technique_chain)
                    -- first_seen_at intentionally NOT updated (AC-8)
                """,
                (
                    p.path_id, scan_run_id, tenant_id, account_id, provider,
                    psycopg2.extras.Json(p.node_uids),
                    psycopg2.extras.Json(p.node_types),
                    psycopg2.extras.Json(p.edge_types),
                    psycopg2.extras.Json(p.hop_categories),
                    p.depth, p.entry_point_uid, p.entry_point_type or "",
                    p.crown_jewel_uid, p.crown_jewel_type, p.chain_type, p.data_classification,
                    p.path_score, p.probability_score, p.impact_score, (p.severity or "medium").lower(),
                    p.max_epss, p.misconfig_count, p.threat_count,
                    psycopg2.extras.Json(p.top_cves or []),
                    p.has_active_cdr_actor,
                    p.group_id, p.group_size, p.is_representative,
                    p.absorbed_count, p.choke_node_uid,
                    p.effective_access_principal, p.access_capability,
                    confidence_level, attack_name, attack_story, attack_technique_chain,
                ),
            )

        # Mark paths not found in current scan as resolved (AC-11)
        if current_path_ids:
            cur.execute(
                """
                UPDATE attack_paths
                SET status = 'resolved', updated_at = NOW()
                WHERE tenant_id = %s
                  AND status = 'active'
                  AND path_id != ALL(%s::varchar[])
                """,
                (tenant_id, current_path_ids),
            )
        else:
            # If no current paths, resolve all active paths for this tenant
            cur.execute(
                """
                UPDATE attack_paths
                SET status = 'resolved', updated_at = NOW()
                WHERE tenant_id = %s AND status = 'active'
                """,
                (tenant_id,),
            )

    conn.commit()
    logger.info(
        '{"engine":"attack-path","stage":"write_paths","tenant_id":"%s",'
        '"paths_written":%d}',
        tenant_id,
        len(paths),
    )


def write_path_nodes(
    conn: Any,
    paths: List[Path],
    tenant_id: str,
    findings_lookup: Optional[Any] = None,
) -> None:
    """Write per-hop evidence to attack_path_nodes.

    Clears existing nodes for each path_id before re-inserting (DELETE+INSERT).
    Nodes may change between scans (different CVEs discovered, misconfigs fixed).

    When findings_lookup is provided (Dict[resource_uid → {misconfigs,cves,threat_detections}]),
    those findings are merged into hop_evidence — SF-P3-01.

    JSONB values: psycopg2.extras.Json() — NEVER json.dumps() or json.loads().

    Args:
        conn:             psycopg2 connection (caller manages transaction).
        paths:            Deduplicated Path objects.
        tenant_id:        Tenant identifier — written to every row.
        findings_lookup:  Optional cross-engine findings keyed by resource_uid.
    """
    if not paths:
        return

    _fl = findings_lookup or {}

    with conn.cursor() as cur:
        # Process in batches to avoid huge transactions
        for batch_start in range(0, len(paths), _BATCH_SIZE):
            batch = paths[batch_start: batch_start + _BATCH_SIZE]

            # Delete existing node rows for this batch of path_ids
            batch_ids = [p.path_id for p in batch]
            cur.execute(
                "DELETE FROM attack_path_nodes WHERE path_id = ANY(%s::varchar[])",
                (batch_ids,),
            )

            # Re-insert hop nodes
            rows = []
            for p in batch:
                # Build hop_index → edge_context from path_explainer output.
                # explanation.steps[i]["step"] is 1-indexed; hop_index is 0-indexed.
                expl_steps = (p.explanation or {}).get("steps", [])
                edge_ctx_by_hop: dict = {
                    s["step"] - 1: s["edge_context"]
                    for s in expl_steps
                    if s.get("edge_context")
                }

                for hop_index, (uid, ntype, etype) in enumerate(
                    zip(p.node_uids, p.node_types, p.edge_types + [""])
                ):
                    # Extract hop-level evidence if available
                    hop_ev = (p.hop_evidence or [])
                    ev = hop_ev[hop_index] if hop_index < len(hop_ev) else {}

                    # Merge security_findings data (SF-P3-01): prefer hop_evidence baseline,
                    # then append any additional items from findings_lookup for this node.
                    fl_node = _fl.get(uid, {})
                    misconfigs = list(ev.get("misconfigs") or []) + [
                        m for m in fl_node.get("misconfigs", [])
                        if m not in (ev.get("misconfigs") or [])
                    ]
                    cves = list(ev.get("cves") or []) + [
                        c for c in fl_node.get("cves", [])
                        if c not in (ev.get("cves") or [])
                    ]
                    threat_detections = list(ev.get("threat_detections") or []) + [
                        t for t in fl_node.get("threat_detections", [])
                        if t not in (ev.get("threat_detections") or [])
                    ]

                    edge_ctx = edge_ctx_by_hop.get(hop_index)

                    rows.append((
                        p.path_id,
                        tenant_id,
                        uid,
                        ev.get("node_name"),
                        ntype,
                        hop_index,
                        etype if etype else None,
                        ev.get("edge_category"),
                        ev.get("traversal_reason"),
                        psycopg2.extras.Json(ev.get("policy_statement")) if ev.get("policy_statement") else None,
                        psycopg2.extras.Json(ev.get("sg_rule")) if ev.get("sg_rule") else None,
                        psycopg2.extras.Json(misconfigs),
                        psycopg2.extras.Json(cves),
                        psycopg2.extras.Json(threat_detections),
                        bool(ev.get("cdr_actor_active", False)),
                        ev.get("cdr_actor_uid"),
                        psycopg2.extras.Json(edge_ctx) if edge_ctx else None,
                    ))

            if rows:
                psycopg2.extras.execute_values(
                    cur,
                    """
                    INSERT INTO attack_path_nodes (
                        path_id, tenant_id, node_uid, node_name, node_type,
                        hop_index, edge_to_next, edge_category, traversal_reason,
                        policy_statement, sg_rule, misconfigs, cves,
                        threat_detections, cdr_actor_active, cdr_actor_uid,
                        edge_context
                    )
                    VALUES %s
                    """,
                    rows,
                    page_size=_BATCH_SIZE,
                )

    conn.commit()
    logger.info(
        '{"engine":"attack-path","stage":"write_nodes","tenant_id":"%s",'
        '"paths_with_nodes":%d}',
        tenant_id,
        len(paths),
    )


def write_history(
    conn: Any,
    paths: List[Path],
    tenant_id: str,
    scan_run_id: str,
) -> None:
    """Write an immutable history snapshot for each surviving path.

    INSERT ONLY — no ON CONFLICT / no UPDATE. Every scan that finds a path
    generates one new history row. Retention managed at infra level.

    Args:
        conn:        psycopg2 connection (caller manages transaction).
        paths:       Deduplicated Path objects (representative paths preferred).
        tenant_id:   Tenant identifier.
        scan_run_id: Current pipeline run UUID.
    """
    if not paths:
        return

    with conn.cursor() as cur:
        rows = [
            (
                p.path_id,
                tenant_id,
                scan_run_id,
                p.path_score,
                (p.severity or "medium").lower(),
                psycopg2.extras.Json(p.node_uids),
                p.misconfig_count,
                p.threat_count,
                p.has_active_cdr_actor,
            )
            for p in paths
        ]
        psycopg2.extras.execute_values(
            cur,
            """
            INSERT INTO attack_path_history (
                path_id, tenant_id, scan_run_id, path_score, severity,
                node_uids, misconfig_count, threat_count, has_active_cdr_actor
            )
            VALUES %s
            """,
            rows,
            page_size=_BATCH_SIZE,
        )

    conn.commit()
    logger.info(
        '{"engine":"attack-path","stage":"write_history","tenant_id":"%s",'
        '"history_rows":%d}',
        tenant_id,
        len(paths),
    )
