apiVersion: v1
kind: Secret
metadata:
  name: threat-engine-db-passwords
  namespace: threat-engine-engines
type: Opaque
stringData:
  CHECK_DB_PASSWORD: "apXuHV%2OSyRWK62"
  DISCOVERIES_DB_PASSWORD: "apXuHV%2OSyRWK62"
  COMPLIANCE_DB_PASSWORD: "apXuHV%2OSyRWK62"
  INVENTORY_DB_PASSWORD: "apXuHV%2OSyRWK62"
  THREAT_DB_PASSWORD: "apXuHV%2OSyRWK62"
  SHARED_DB_PASSWORD: "apXuHV%2OSyRWK62"
  IAM_DB_PASSWORD: "apXuHV%2OSyRWK62"
  DATASEC_DB_PASSWORD: "apXuHV%2OSyRWK62"
